// Generated by candid-core-ts from a candid-core Contract. Do not edit.
import * as $ from "@candid-core/schema";

export type A0 = Array<A1>;
const $A0: $.Schema<A0> = $.c.rec(() => $.c.vec($A1));
export { $A0 as A0 };

export type A1 = Array<A2>;
const $A1: $.Schema<A1> = $.c.rec(() => $.c.vec($A2));
export { $A1 as A1 };

export type A10 = Array<A11>;
const $A10: $.Schema<A10> = $.c.rec(() => $.c.vec($A11));
export { $A10 as A10 };

export type A100 = Array<A101>;
const $A100: $.Schema<A100> = $.c.rec(() => $.c.vec($A101));
export { $A100 as A100 };

export type A101 = Array<A102>;
const $A101: $.Schema<A101> = $.c.rec(() => $.c.vec($A102));
export { $A101 as A101 };

export type A102 = Array<A103>;
const $A102: $.Schema<A102> = $.c.rec(() => $.c.vec($A103));
export { $A102 as A102 };

export type A103 = Array<A104>;
const $A103: $.Schema<A103> = $.c.rec(() => $.c.vec($A104));
export { $A103 as A103 };

export type A104 = Array<A105>;
const $A104: $.Schema<A104> = $.c.rec(() => $.c.vec($A105));
export { $A104 as A104 };

export type A105 = Array<A106>;
const $A105: $.Schema<A105> = $.c.rec(() => $.c.vec($A106));
export { $A105 as A105 };

export type A106 = Array<A107>;
const $A106: $.Schema<A106> = $.c.rec(() => $.c.vec($A107));
export { $A106 as A106 };

export type A107 = Array<A108>;
const $A107: $.Schema<A107> = $.c.rec(() => $.c.vec($A108));
export { $A107 as A107 };

export type A108 = Array<A109>;
const $A108: $.Schema<A108> = $.c.rec(() => $.c.vec($A109));
export { $A108 as A108 };

export type A109 = Array<A110>;
const $A109: $.Schema<A109> = $.c.rec(() => $.c.vec($A110));
export { $A109 as A109 };

export type A11 = Array<A12>;
const $A11: $.Schema<A11> = $.c.rec(() => $.c.vec($A12));
export { $A11 as A11 };

export type A110 = Array<A111>;
const $A110: $.Schema<A110> = $.c.rec(() => $.c.vec($A111));
export { $A110 as A110 };

export type A111 = Array<A112>;
const $A111: $.Schema<A111> = $.c.rec(() => $.c.vec($A112));
export { $A111 as A111 };

export type A112 = Array<A113>;
const $A112: $.Schema<A112> = $.c.rec(() => $.c.vec($A113));
export { $A112 as A112 };

export type A113 = Array<A114>;
const $A113: $.Schema<A113> = $.c.rec(() => $.c.vec($A114));
export { $A113 as A113 };

export type A114 = Array<A115>;
const $A114: $.Schema<A114> = $.c.rec(() => $.c.vec($A115));
export { $A114 as A114 };

export type A115 = Array<A116>;
const $A115: $.Schema<A115> = $.c.rec(() => $.c.vec($A116));
export { $A115 as A115 };

export type A116 = Array<A117>;
const $A116: $.Schema<A116> = $.c.rec(() => $.c.vec($A117));
export { $A116 as A116 };

export type A117 = Array<A118>;
const $A117: $.Schema<A117> = $.c.rec(() => $.c.vec($A118));
export { $A117 as A117 };

export type A118 = Array<A119>;
const $A118: $.Schema<A118> = $.c.rec(() => $.c.vec($A119));
export { $A118 as A118 };

export type A119 = Array<A120>;
const $A119: $.Schema<A119> = $.c.rec(() => $.c.vec($A120));
export { $A119 as A119 };

export type A12 = Array<A13>;
const $A12: $.Schema<A12> = $.c.rec(() => $.c.vec($A13));
export { $A12 as A12 };

export type A120 = Array<A121>;
const $A120: $.Schema<A120> = $.c.rec(() => $.c.vec($A121));
export { $A120 as A120 };

export type A121 = Array<A122>;
const $A121: $.Schema<A121> = $.c.rec(() => $.c.vec($A122));
export { $A121 as A121 };

export type A122 = Array<A123>;
const $A122: $.Schema<A122> = $.c.rec(() => $.c.vec($A123));
export { $A122 as A122 };

export type A123 = Array<A124>;
const $A123: $.Schema<A123> = $.c.rec(() => $.c.vec($A124));
export { $A123 as A123 };

export type A124 = Array<A125>;
const $A124: $.Schema<A124> = $.c.rec(() => $.c.vec($A125));
export { $A124 as A124 };

export type A125 = Array<A126>;
const $A125: $.Schema<A125> = $.c.rec(() => $.c.vec($A126));
export { $A125 as A125 };

export type A126 = Array<A127>;
const $A126: $.Schema<A126> = $.c.rec(() => $.c.vec($A127));
export { $A126 as A126 };

export type A127 = Array<A128>;
const $A127: $.Schema<A127> = $.c.rec(() => $.c.vec($A128));
export { $A127 as A127 };

export type A128 = Array<A129>;
const $A128: $.Schema<A128> = $.c.rec(() => $.c.vec($A129));
export { $A128 as A128 };

export type A129 = Array<A130>;
const $A129: $.Schema<A129> = $.c.rec(() => $.c.vec($A130));
export { $A129 as A129 };

export type A13 = Array<A14>;
const $A13: $.Schema<A13> = $.c.rec(() => $.c.vec($A14));
export { $A13 as A13 };

export type A130 = Array<A131>;
const $A130: $.Schema<A130> = $.c.rec(() => $.c.vec($A131));
export { $A130 as A130 };

export type A131 = Array<A132>;
const $A131: $.Schema<A131> = $.c.rec(() => $.c.vec($A132));
export { $A131 as A131 };

export type A132 = Array<A133>;
const $A132: $.Schema<A132> = $.c.rec(() => $.c.vec($A133));
export { $A132 as A132 };

export type A133 = Array<A134>;
const $A133: $.Schema<A133> = $.c.rec(() => $.c.vec($A134));
export { $A133 as A133 };

export type A134 = Array<A135>;
const $A134: $.Schema<A134> = $.c.rec(() => $.c.vec($A135));
export { $A134 as A134 };

export type A135 = Array<A136>;
const $A135: $.Schema<A135> = $.c.rec(() => $.c.vec($A136));
export { $A135 as A135 };

export type A136 = Array<A137>;
const $A136: $.Schema<A136> = $.c.rec(() => $.c.vec($A137));
export { $A136 as A136 };

export type A137 = Array<A138>;
const $A137: $.Schema<A137> = $.c.rec(() => $.c.vec($A138));
export { $A137 as A137 };

export type A138 = Array<A139>;
const $A138: $.Schema<A138> = $.c.rec(() => $.c.vec($A139));
export { $A138 as A138 };

export type A139 = Array<A140>;
const $A139: $.Schema<A139> = $.c.rec(() => $.c.vec($A140));
export { $A139 as A139 };

export type A14 = Array<A15>;
const $A14: $.Schema<A14> = $.c.rec(() => $.c.vec($A15));
export { $A14 as A14 };

export type A140 = Array<A141>;
const $A140: $.Schema<A140> = $.c.rec(() => $.c.vec($A141));
export { $A140 as A140 };

export type A141 = Array<A142>;
const $A141: $.Schema<A141> = $.c.rec(() => $.c.vec($A142));
export { $A141 as A141 };

export type A142 = Array<A143>;
const $A142: $.Schema<A142> = $.c.rec(() => $.c.vec($A143));
export { $A142 as A142 };

export type A143 = Array<A144>;
const $A143: $.Schema<A143> = $.c.rec(() => $.c.vec($A144));
export { $A143 as A143 };

export type A144 = Array<A145>;
const $A144: $.Schema<A144> = $.c.rec(() => $.c.vec($A145));
export { $A144 as A144 };

export type A145 = Array<A146>;
const $A145: $.Schema<A145> = $.c.rec(() => $.c.vec($A146));
export { $A145 as A145 };

export type A146 = Array<A147>;
const $A146: $.Schema<A146> = $.c.rec(() => $.c.vec($A147));
export { $A146 as A146 };

export type A147 = Array<A148>;
const $A147: $.Schema<A147> = $.c.rec(() => $.c.vec($A148));
export { $A147 as A147 };

export type A148 = Array<A149>;
const $A148: $.Schema<A148> = $.c.rec(() => $.c.vec($A149));
export { $A148 as A148 };

export type A149 = Array<A150>;
const $A149: $.Schema<A149> = $.c.rec(() => $.c.vec($A150));
export { $A149 as A149 };

export type A15 = Array<A16>;
const $A15: $.Schema<A15> = $.c.rec(() => $.c.vec($A16));
export { $A15 as A15 };

export type A150 = Array<A151>;
const $A150: $.Schema<A150> = $.c.rec(() => $.c.vec($A151));
export { $A150 as A150 };

export type A151 = Array<A152>;
const $A151: $.Schema<A151> = $.c.rec(() => $.c.vec($A152));
export { $A151 as A151 };

export type A152 = Array<A153>;
const $A152: $.Schema<A152> = $.c.rec(() => $.c.vec($A153));
export { $A152 as A152 };

export type A153 = Array<A154>;
const $A153: $.Schema<A153> = $.c.rec(() => $.c.vec($A154));
export { $A153 as A153 };

export type A154 = Array<A155>;
const $A154: $.Schema<A154> = $.c.rec(() => $.c.vec($A155));
export { $A154 as A154 };

export type A155 = Array<A156>;
const $A155: $.Schema<A155> = $.c.rec(() => $.c.vec($A156));
export { $A155 as A155 };

export type A156 = Array<A157>;
const $A156: $.Schema<A156> = $.c.rec(() => $.c.vec($A157));
export { $A156 as A156 };

export type A157 = Array<A158>;
const $A157: $.Schema<A157> = $.c.rec(() => $.c.vec($A158));
export { $A157 as A157 };

export type A158 = Array<A159>;
const $A158: $.Schema<A158> = $.c.rec(() => $.c.vec($A159));
export { $A158 as A158 };

export type A159 = Array<A160>;
const $A159: $.Schema<A159> = $.c.rec(() => $.c.vec($A160));
export { $A159 as A159 };

export type A16 = Array<A17>;
const $A16: $.Schema<A16> = $.c.rec(() => $.c.vec($A17));
export { $A16 as A16 };

export type A160 = Array<A161>;
const $A160: $.Schema<A160> = $.c.rec(() => $.c.vec($A161));
export { $A160 as A160 };

export type A161 = Array<A162>;
const $A161: $.Schema<A161> = $.c.rec(() => $.c.vec($A162));
export { $A161 as A161 };

export type A162 = Array<A163>;
const $A162: $.Schema<A162> = $.c.rec(() => $.c.vec($A163));
export { $A162 as A162 };

export type A163 = Array<A164>;
const $A163: $.Schema<A163> = $.c.rec(() => $.c.vec($A164));
export { $A163 as A163 };

export type A164 = Array<A165>;
const $A164: $.Schema<A164> = $.c.rec(() => $.c.vec($A165));
export { $A164 as A164 };

export type A165 = Array<A166>;
const $A165: $.Schema<A165> = $.c.rec(() => $.c.vec($A166));
export { $A165 as A165 };

export type A166 = Array<A167>;
const $A166: $.Schema<A166> = $.c.rec(() => $.c.vec($A167));
export { $A166 as A166 };

export type A167 = Array<A168>;
const $A167: $.Schema<A167> = $.c.rec(() => $.c.vec($A168));
export { $A167 as A167 };

export type A168 = Array<A169>;
const $A168: $.Schema<A168> = $.c.rec(() => $.c.vec($A169));
export { $A168 as A168 };

export type A169 = Array<A170>;
const $A169: $.Schema<A169> = $.c.rec(() => $.c.vec($A170));
export { $A169 as A169 };

export type A17 = Array<A18>;
const $A17: $.Schema<A17> = $.c.rec(() => $.c.vec($A18));
export { $A17 as A17 };

export type A170 = Array<A171>;
const $A170: $.Schema<A170> = $.c.rec(() => $.c.vec($A171));
export { $A170 as A170 };

export type A171 = Array<A172>;
const $A171: $.Schema<A171> = $.c.rec(() => $.c.vec($A172));
export { $A171 as A171 };

export type A172 = Array<A173>;
const $A172: $.Schema<A172> = $.c.rec(() => $.c.vec($A173));
export { $A172 as A172 };

export type A173 = Array<A174>;
const $A173: $.Schema<A173> = $.c.rec(() => $.c.vec($A174));
export { $A173 as A173 };

export type A174 = Array<A175>;
const $A174: $.Schema<A174> = $.c.rec(() => $.c.vec($A175));
export { $A174 as A174 };

export type A175 = Array<A176>;
const $A175: $.Schema<A175> = $.c.rec(() => $.c.vec($A176));
export { $A175 as A175 };

export type A176 = Array<A177>;
const $A176: $.Schema<A176> = $.c.rec(() => $.c.vec($A177));
export { $A176 as A176 };

export type A177 = Array<A178>;
const $A177: $.Schema<A177> = $.c.rec(() => $.c.vec($A178));
export { $A177 as A177 };

export type A178 = Array<A179>;
const $A178: $.Schema<A178> = $.c.rec(() => $.c.vec($A179));
export { $A178 as A178 };

export type A179 = Array<A180>;
const $A179: $.Schema<A179> = $.c.rec(() => $.c.vec($A180));
export { $A179 as A179 };

export type A18 = Array<A19>;
const $A18: $.Schema<A18> = $.c.rec(() => $.c.vec($A19));
export { $A18 as A18 };

export type A180 = Array<A181>;
const $A180: $.Schema<A180> = $.c.rec(() => $.c.vec($A181));
export { $A180 as A180 };

export type A181 = Array<A182>;
const $A181: $.Schema<A181> = $.c.rec(() => $.c.vec($A182));
export { $A181 as A181 };

export type A182 = Array<A183>;
const $A182: $.Schema<A182> = $.c.rec(() => $.c.vec($A183));
export { $A182 as A182 };

export type A183 = Array<A184>;
const $A183: $.Schema<A183> = $.c.rec(() => $.c.vec($A184));
export { $A183 as A183 };

export type A184 = Array<A185>;
const $A184: $.Schema<A184> = $.c.rec(() => $.c.vec($A185));
export { $A184 as A184 };

export type A185 = Array<A186>;
const $A185: $.Schema<A185> = $.c.rec(() => $.c.vec($A186));
export { $A185 as A185 };

export type A186 = Array<A187>;
const $A186: $.Schema<A186> = $.c.rec(() => $.c.vec($A187));
export { $A186 as A186 };

export type A187 = Array<A188>;
const $A187: $.Schema<A187> = $.c.rec(() => $.c.vec($A188));
export { $A187 as A187 };

export type A188 = Array<A189>;
const $A188: $.Schema<A188> = $.c.rec(() => $.c.vec($A189));
export { $A188 as A188 };

export type A189 = Array<A190>;
const $A189: $.Schema<A189> = $.c.rec(() => $.c.vec($A190));
export { $A189 as A189 };

export type A19 = Array<A20>;
const $A19: $.Schema<A19> = $.c.rec(() => $.c.vec($A20));
export { $A19 as A19 };

export type A190 = Array<A191>;
const $A190: $.Schema<A190> = $.c.rec(() => $.c.vec($A191));
export { $A190 as A190 };

export type A191 = Array<A192>;
const $A191: $.Schema<A191> = $.c.rec(() => $.c.vec($A192));
export { $A191 as A191 };

export type A192 = Array<A193>;
const $A192: $.Schema<A192> = $.c.rec(() => $.c.vec($A193));
export { $A192 as A192 };

export type A193 = Array<A194>;
const $A193: $.Schema<A193> = $.c.rec(() => $.c.vec($A194));
export { $A193 as A193 };

export type A194 = Array<A195>;
const $A194: $.Schema<A194> = $.c.rec(() => $.c.vec($A195));
export { $A194 as A194 };

export type A195 = Array<A196>;
const $A195: $.Schema<A195> = $.c.rec(() => $.c.vec($A196));
export { $A195 as A195 };

export type A196 = Array<A197>;
const $A196: $.Schema<A196> = $.c.rec(() => $.c.vec($A197));
export { $A196 as A196 };

export type A197 = Array<A198>;
const $A197: $.Schema<A197> = $.c.rec(() => $.c.vec($A198));
export { $A197 as A197 };

export type A198 = Array<A199>;
const $A198: $.Schema<A198> = $.c.rec(() => $.c.vec($A199));
export { $A198 as A198 };

export type A199 = Array<A200>;
const $A199: $.Schema<A199> = $.c.rec(() => $.c.vec($A200));
export { $A199 as A199 };

export type A2 = Array<A3>;
const $A2: $.Schema<A2> = $.c.rec(() => $.c.vec($A3));
export { $A2 as A2 };

export type A20 = Array<A21>;
const $A20: $.Schema<A20> = $.c.rec(() => $.c.vec($A21));
export { $A20 as A20 };

export type A200 = Array<A201>;
const $A200: $.Schema<A200> = $.c.rec(() => $.c.vec($A201));
export { $A200 as A200 };

export type A201 = Array<A202>;
const $A201: $.Schema<A201> = $.c.rec(() => $.c.vec($A202));
export { $A201 as A201 };

export type A202 = Array<A203>;
const $A202: $.Schema<A202> = $.c.rec(() => $.c.vec($A203));
export { $A202 as A202 };

export type A203 = Array<A204>;
const $A203: $.Schema<A203> = $.c.rec(() => $.c.vec($A204));
export { $A203 as A203 };

export type A204 = Array<A205>;
const $A204: $.Schema<A204> = $.c.rec(() => $.c.vec($A205));
export { $A204 as A204 };

export type A205 = Array<A206>;
const $A205: $.Schema<A205> = $.c.rec(() => $.c.vec($A206));
export { $A205 as A205 };

export type A206 = Array<A207>;
const $A206: $.Schema<A206> = $.c.rec(() => $.c.vec($A207));
export { $A206 as A206 };

export type A207 = Array<A208>;
const $A207: $.Schema<A207> = $.c.rec(() => $.c.vec($A208));
export { $A207 as A207 };

export type A208 = Array<A209>;
const $A208: $.Schema<A208> = $.c.rec(() => $.c.vec($A209));
export { $A208 as A208 };

export type A209 = Array<A210>;
const $A209: $.Schema<A209> = $.c.rec(() => $.c.vec($A210));
export { $A209 as A209 };

export type A21 = Array<A22>;
const $A21: $.Schema<A21> = $.c.rec(() => $.c.vec($A22));
export { $A21 as A21 };

export type A210 = Array<A211>;
const $A210: $.Schema<A210> = $.c.rec(() => $.c.vec($A211));
export { $A210 as A210 };

export type A211 = Array<A212>;
const $A211: $.Schema<A211> = $.c.rec(() => $.c.vec($A212));
export { $A211 as A211 };

export type A212 = Array<A213>;
const $A212: $.Schema<A212> = $.c.rec(() => $.c.vec($A213));
export { $A212 as A212 };

export type A213 = Array<A214>;
const $A213: $.Schema<A213> = $.c.rec(() => $.c.vec($A214));
export { $A213 as A213 };

export type A214 = Array<A215>;
const $A214: $.Schema<A214> = $.c.rec(() => $.c.vec($A215));
export { $A214 as A214 };

export type A215 = Array<A216>;
const $A215: $.Schema<A215> = $.c.rec(() => $.c.vec($A216));
export { $A215 as A215 };

export type A216 = Array<A217>;
const $A216: $.Schema<A216> = $.c.rec(() => $.c.vec($A217));
export { $A216 as A216 };

export type A217 = Array<A218>;
const $A217: $.Schema<A217> = $.c.rec(() => $.c.vec($A218));
export { $A217 as A217 };

export type A218 = Array<A219>;
const $A218: $.Schema<A218> = $.c.rec(() => $.c.vec($A219));
export { $A218 as A218 };

export type A219 = Array<A220>;
const $A219: $.Schema<A219> = $.c.rec(() => $.c.vec($A220));
export { $A219 as A219 };

export type A22 = Array<A23>;
const $A22: $.Schema<A22> = $.c.rec(() => $.c.vec($A23));
export { $A22 as A22 };

export type A220 = Array<A221>;
const $A220: $.Schema<A220> = $.c.rec(() => $.c.vec($A221));
export { $A220 as A220 };

export type A221 = Array<A222>;
const $A221: $.Schema<A221> = $.c.rec(() => $.c.vec($A222));
export { $A221 as A221 };

export type A222 = Array<A223>;
const $A222: $.Schema<A222> = $.c.rec(() => $.c.vec($A223));
export { $A222 as A222 };

export type A223 = Array<A224>;
const $A223: $.Schema<A223> = $.c.rec(() => $.c.vec($A224));
export { $A223 as A223 };

export type A224 = Array<A225>;
const $A224: $.Schema<A224> = $.c.rec(() => $.c.vec($A225));
export { $A224 as A224 };

export type A225 = Array<A226>;
const $A225: $.Schema<A225> = $.c.rec(() => $.c.vec($A226));
export { $A225 as A225 };

export type A226 = Array<A227>;
const $A226: $.Schema<A226> = $.c.rec(() => $.c.vec($A227));
export { $A226 as A226 };

export type A227 = Array<A228>;
const $A227: $.Schema<A227> = $.c.rec(() => $.c.vec($A228));
export { $A227 as A227 };

export type A228 = Array<A229>;
const $A228: $.Schema<A228> = $.c.rec(() => $.c.vec($A229));
export { $A228 as A228 };

export type A229 = Array<A230>;
const $A229: $.Schema<A229> = $.c.rec(() => $.c.vec($A230));
export { $A229 as A229 };

export type A23 = Array<A24>;
const $A23: $.Schema<A23> = $.c.rec(() => $.c.vec($A24));
export { $A23 as A23 };

export type A230 = Array<A231>;
const $A230: $.Schema<A230> = $.c.rec(() => $.c.vec($A231));
export { $A230 as A230 };

export type A231 = Array<A232>;
const $A231: $.Schema<A231> = $.c.rec(() => $.c.vec($A232));
export { $A231 as A231 };

export type A232 = Array<A233>;
const $A232: $.Schema<A232> = $.c.rec(() => $.c.vec($A233));
export { $A232 as A232 };

export type A233 = Array<A234>;
const $A233: $.Schema<A233> = $.c.rec(() => $.c.vec($A234));
export { $A233 as A233 };

export type A234 = Array<A235>;
const $A234: $.Schema<A234> = $.c.rec(() => $.c.vec($A235));
export { $A234 as A234 };

export type A235 = Array<A236>;
const $A235: $.Schema<A235> = $.c.rec(() => $.c.vec($A236));
export { $A235 as A235 };

export type A236 = Array<A237>;
const $A236: $.Schema<A236> = $.c.rec(() => $.c.vec($A237));
export { $A236 as A236 };

export type A237 = Array<A238>;
const $A237: $.Schema<A237> = $.c.rec(() => $.c.vec($A238));
export { $A237 as A237 };

export type A238 = Array<A239>;
const $A238: $.Schema<A238> = $.c.rec(() => $.c.vec($A239));
export { $A238 as A238 };

export type A239 = Array<A240>;
const $A239: $.Schema<A239> = $.c.rec(() => $.c.vec($A240));
export { $A239 as A239 };

export type A24 = Array<A25>;
const $A24: $.Schema<A24> = $.c.rec(() => $.c.vec($A25));
export { $A24 as A24 };

export type A240 = Array<A241>;
const $A240: $.Schema<A240> = $.c.rec(() => $.c.vec($A241));
export { $A240 as A240 };

export type A241 = Array<A242>;
const $A241: $.Schema<A241> = $.c.rec(() => $.c.vec($A242));
export { $A241 as A241 };

export type A242 = Array<A243>;
const $A242: $.Schema<A242> = $.c.rec(() => $.c.vec($A243));
export { $A242 as A242 };

export type A243 = Array<A244>;
const $A243: $.Schema<A243> = $.c.rec(() => $.c.vec($A244));
export { $A243 as A243 };

export type A244 = Array<A245>;
const $A244: $.Schema<A244> = $.c.rec(() => $.c.vec($A245));
export { $A244 as A244 };

export type A245 = Array<A246>;
const $A245: $.Schema<A245> = $.c.rec(() => $.c.vec($A246));
export { $A245 as A245 };

export type A246 = Array<A247>;
const $A246: $.Schema<A246> = $.c.rec(() => $.c.vec($A247));
export { $A246 as A246 };

export type A247 = Array<A248>;
const $A247: $.Schema<A247> = $.c.rec(() => $.c.vec($A248));
export { $A247 as A247 };

export type A248 = Array<A249>;
const $A248: $.Schema<A248> = $.c.rec(() => $.c.vec($A249));
export { $A248 as A248 };

export type A249 = Array<A250>;
const $A249: $.Schema<A249> = $.c.rec(() => $.c.vec($A250));
export { $A249 as A249 };

export type A25 = Array<A26>;
const $A25: $.Schema<A25> = $.c.rec(() => $.c.vec($A26));
export { $A25 as A25 };

export type A250 = Array<Array<Array<Array<Array<Array<Record<string, never>>>>>>>;
const $A250: $.Schema<A250> = $.c.rec(() => $.c.vec($.c.vec($.c.vec($.c.vec($.c.vec($.c.vec($.c.unit())))))));
export { $A250 as A250 };

export type A26 = Array<A27>;
const $A26: $.Schema<A26> = $.c.rec(() => $.c.vec($A27));
export { $A26 as A26 };

export type A27 = Array<A28>;
const $A27: $.Schema<A27> = $.c.rec(() => $.c.vec($A28));
export { $A27 as A27 };

export type A28 = Array<A29>;
const $A28: $.Schema<A28> = $.c.rec(() => $.c.vec($A29));
export { $A28 as A28 };

export type A29 = Array<A30>;
const $A29: $.Schema<A29> = $.c.rec(() => $.c.vec($A30));
export { $A29 as A29 };

export type A3 = Array<A4>;
const $A3: $.Schema<A3> = $.c.rec(() => $.c.vec($A4));
export { $A3 as A3 };

export type A30 = Array<A31>;
const $A30: $.Schema<A30> = $.c.rec(() => $.c.vec($A31));
export { $A30 as A30 };

export type A31 = Array<A32>;
const $A31: $.Schema<A31> = $.c.rec(() => $.c.vec($A32));
export { $A31 as A31 };

export type A32 = Array<A33>;
const $A32: $.Schema<A32> = $.c.rec(() => $.c.vec($A33));
export { $A32 as A32 };

export type A33 = Array<A34>;
const $A33: $.Schema<A33> = $.c.rec(() => $.c.vec($A34));
export { $A33 as A33 };

export type A34 = Array<A35>;
const $A34: $.Schema<A34> = $.c.rec(() => $.c.vec($A35));
export { $A34 as A34 };

export type A35 = Array<A36>;
const $A35: $.Schema<A35> = $.c.rec(() => $.c.vec($A36));
export { $A35 as A35 };

export type A36 = Array<A37>;
const $A36: $.Schema<A36> = $.c.rec(() => $.c.vec($A37));
export { $A36 as A36 };

export type A37 = Array<A38>;
const $A37: $.Schema<A37> = $.c.rec(() => $.c.vec($A38));
export { $A37 as A37 };

export type A38 = Array<A39>;
const $A38: $.Schema<A38> = $.c.rec(() => $.c.vec($A39));
export { $A38 as A38 };

export type A39 = Array<A40>;
const $A39: $.Schema<A39> = $.c.rec(() => $.c.vec($A40));
export { $A39 as A39 };

export type A4 = Array<A5>;
const $A4: $.Schema<A4> = $.c.rec(() => $.c.vec($A5));
export { $A4 as A4 };

export type A40 = Array<A41>;
const $A40: $.Schema<A40> = $.c.rec(() => $.c.vec($A41));
export { $A40 as A40 };

export type A41 = Array<A42>;
const $A41: $.Schema<A41> = $.c.rec(() => $.c.vec($A42));
export { $A41 as A41 };

export type A42 = Array<A43>;
const $A42: $.Schema<A42> = $.c.rec(() => $.c.vec($A43));
export { $A42 as A42 };

export type A43 = Array<A44>;
const $A43: $.Schema<A43> = $.c.rec(() => $.c.vec($A44));
export { $A43 as A43 };

export type A44 = Array<A45>;
const $A44: $.Schema<A44> = $.c.rec(() => $.c.vec($A45));
export { $A44 as A44 };

export type A45 = Array<A46>;
const $A45: $.Schema<A45> = $.c.rec(() => $.c.vec($A46));
export { $A45 as A45 };

export type A46 = Array<A47>;
const $A46: $.Schema<A46> = $.c.rec(() => $.c.vec($A47));
export { $A46 as A46 };

export type A47 = Array<A48>;
const $A47: $.Schema<A47> = $.c.rec(() => $.c.vec($A48));
export { $A47 as A47 };

export type A48 = Array<A49>;
const $A48: $.Schema<A48> = $.c.rec(() => $.c.vec($A49));
export { $A48 as A48 };

export type A49 = Array<A50>;
const $A49: $.Schema<A49> = $.c.rec(() => $.c.vec($A50));
export { $A49 as A49 };

export type A5 = Array<A6>;
const $A5: $.Schema<A5> = $.c.rec(() => $.c.vec($A6));
export { $A5 as A5 };

export type A50 = Array<A51>;
const $A50: $.Schema<A50> = $.c.rec(() => $.c.vec($A51));
export { $A50 as A50 };

export type A51 = Array<A52>;
const $A51: $.Schema<A51> = $.c.rec(() => $.c.vec($A52));
export { $A51 as A51 };

export type A52 = Array<A53>;
const $A52: $.Schema<A52> = $.c.rec(() => $.c.vec($A53));
export { $A52 as A52 };

export type A53 = Array<A54>;
const $A53: $.Schema<A53> = $.c.rec(() => $.c.vec($A54));
export { $A53 as A53 };

export type A54 = Array<A55>;
const $A54: $.Schema<A54> = $.c.rec(() => $.c.vec($A55));
export { $A54 as A54 };

export type A55 = Array<A56>;
const $A55: $.Schema<A55> = $.c.rec(() => $.c.vec($A56));
export { $A55 as A55 };

export type A56 = Array<A57>;
const $A56: $.Schema<A56> = $.c.rec(() => $.c.vec($A57));
export { $A56 as A56 };

export type A57 = Array<A58>;
const $A57: $.Schema<A57> = $.c.rec(() => $.c.vec($A58));
export { $A57 as A57 };

export type A58 = Array<A59>;
const $A58: $.Schema<A58> = $.c.rec(() => $.c.vec($A59));
export { $A58 as A58 };

export type A59 = Array<A60>;
const $A59: $.Schema<A59> = $.c.rec(() => $.c.vec($A60));
export { $A59 as A59 };

export type A6 = Array<A7>;
const $A6: $.Schema<A6> = $.c.rec(() => $.c.vec($A7));
export { $A6 as A6 };

export type A60 = Array<A61>;
const $A60: $.Schema<A60> = $.c.rec(() => $.c.vec($A61));
export { $A60 as A60 };

export type A61 = Array<A62>;
const $A61: $.Schema<A61> = $.c.rec(() => $.c.vec($A62));
export { $A61 as A61 };

export type A62 = Array<A63>;
const $A62: $.Schema<A62> = $.c.rec(() => $.c.vec($A63));
export { $A62 as A62 };

export type A63 = Array<A64>;
const $A63: $.Schema<A63> = $.c.rec(() => $.c.vec($A64));
export { $A63 as A63 };

export type A64 = Array<A65>;
const $A64: $.Schema<A64> = $.c.rec(() => $.c.vec($A65));
export { $A64 as A64 };

export type A65 = Array<A66>;
const $A65: $.Schema<A65> = $.c.rec(() => $.c.vec($A66));
export { $A65 as A65 };

export type A66 = Array<A67>;
const $A66: $.Schema<A66> = $.c.rec(() => $.c.vec($A67));
export { $A66 as A66 };

export type A67 = Array<A68>;
const $A67: $.Schema<A67> = $.c.rec(() => $.c.vec($A68));
export { $A67 as A67 };

export type A68 = Array<A69>;
const $A68: $.Schema<A68> = $.c.rec(() => $.c.vec($A69));
export { $A68 as A68 };

export type A69 = Array<A70>;
const $A69: $.Schema<A69> = $.c.rec(() => $.c.vec($A70));
export { $A69 as A69 };

export type A7 = Array<A8>;
const $A7: $.Schema<A7> = $.c.rec(() => $.c.vec($A8));
export { $A7 as A7 };

export type A70 = Array<A71>;
const $A70: $.Schema<A70> = $.c.rec(() => $.c.vec($A71));
export { $A70 as A70 };

export type A71 = Array<A72>;
const $A71: $.Schema<A71> = $.c.rec(() => $.c.vec($A72));
export { $A71 as A71 };

export type A72 = Array<A73>;
const $A72: $.Schema<A72> = $.c.rec(() => $.c.vec($A73));
export { $A72 as A72 };

export type A73 = Array<A74>;
const $A73: $.Schema<A73> = $.c.rec(() => $.c.vec($A74));
export { $A73 as A73 };

export type A74 = Array<A75>;
const $A74: $.Schema<A74> = $.c.rec(() => $.c.vec($A75));
export { $A74 as A74 };

export type A75 = Array<A76>;
const $A75: $.Schema<A75> = $.c.rec(() => $.c.vec($A76));
export { $A75 as A75 };

export type A76 = Array<A77>;
const $A76: $.Schema<A76> = $.c.rec(() => $.c.vec($A77));
export { $A76 as A76 };

export type A77 = Array<A78>;
const $A77: $.Schema<A77> = $.c.rec(() => $.c.vec($A78));
export { $A77 as A77 };

export type A78 = Array<A79>;
const $A78: $.Schema<A78> = $.c.rec(() => $.c.vec($A79));
export { $A78 as A78 };

export type A79 = Array<A80>;
const $A79: $.Schema<A79> = $.c.rec(() => $.c.vec($A80));
export { $A79 as A79 };

export type A8 = Array<A9>;
const $A8: $.Schema<A8> = $.c.rec(() => $.c.vec($A9));
export { $A8 as A8 };

export type A80 = Array<A81>;
const $A80: $.Schema<A80> = $.c.rec(() => $.c.vec($A81));
export { $A80 as A80 };

export type A81 = Array<A82>;
const $A81: $.Schema<A81> = $.c.rec(() => $.c.vec($A82));
export { $A81 as A81 };

export type A82 = Array<A83>;
const $A82: $.Schema<A82> = $.c.rec(() => $.c.vec($A83));
export { $A82 as A82 };

export type A83 = Array<A84>;
const $A83: $.Schema<A83> = $.c.rec(() => $.c.vec($A84));
export { $A83 as A83 };

export type A84 = Array<A85>;
const $A84: $.Schema<A84> = $.c.rec(() => $.c.vec($A85));
export { $A84 as A84 };

export type A85 = Array<A86>;
const $A85: $.Schema<A85> = $.c.rec(() => $.c.vec($A86));
export { $A85 as A85 };

export type A86 = Array<A87>;
const $A86: $.Schema<A86> = $.c.rec(() => $.c.vec($A87));
export { $A86 as A86 };

export type A87 = Array<A88>;
const $A87: $.Schema<A87> = $.c.rec(() => $.c.vec($A88));
export { $A87 as A87 };

export type A88 = Array<A89>;
const $A88: $.Schema<A88> = $.c.rec(() => $.c.vec($A89));
export { $A88 as A88 };

export type A89 = Array<A90>;
const $A89: $.Schema<A89> = $.c.rec(() => $.c.vec($A90));
export { $A89 as A89 };

export type A9 = Array<A10>;
const $A9: $.Schema<A9> = $.c.rec(() => $.c.vec($A10));
export { $A9 as A9 };

export type A90 = Array<A91>;
const $A90: $.Schema<A90> = $.c.rec(() => $.c.vec($A91));
export { $A90 as A90 };

export type A91 = Array<A92>;
const $A91: $.Schema<A91> = $.c.rec(() => $.c.vec($A92));
export { $A91 as A91 };

export type A92 = Array<A93>;
const $A92: $.Schema<A92> = $.c.rec(() => $.c.vec($A93));
export { $A92 as A92 };

export type A93 = Array<A94>;
const $A93: $.Schema<A93> = $.c.rec(() => $.c.vec($A94));
export { $A93 as A93 };

export type A94 = Array<A95>;
const $A94: $.Schema<A94> = $.c.rec(() => $.c.vec($A95));
export { $A94 as A94 };

export type A95 = Array<A96>;
const $A95: $.Schema<A95> = $.c.rec(() => $.c.vec($A96));
export { $A95 as A95 };

export type A96 = Array<A97>;
const $A96: $.Schema<A96> = $.c.rec(() => $.c.vec($A97));
export { $A96 as A96 };

export type A97 = Array<A98>;
const $A97: $.Schema<A97> = $.c.rec(() => $.c.vec($A98));
export { $A97 as A97 };

export type A98 = Array<A99>;
const $A98: $.Schema<A98> = $.c.rec(() => $.c.vec($A99));
export { $A98 as A98 };

export type A99 = Array<A100>;
const $A99: $.Schema<A99> = $.c.rec(() => $.c.vec($A100));
export { $A99 as A99 };
