// Generated by candid-core-ts from a candid-core Contract. Do not edit.
import * as $ from "@candid-core/schema";

export type M0 = { next: M1 };
const $M0: $.Schema<M0> = $.c.rec(() => $.c.record({ next: $M1 }));
export { $M0 as M0 };

export type M1 = M2 | null;
const $M1: $.Schema<M1> = $.c.rec(() => $.c.opt($M2));
export { $M1 as M1 };

export type M10 = { principal: $.Principal; method: string };
const $M10: $.Schema<M10> = $.c.rec(() => $.c.func([$M11], [], "update"));
export { $M10 as M10 };

export type M100 = { principal: $.Principal; method: string };
const $M100: $.Schema<M100> = $.c.rec(() => $.c.func([$M101], [], "update"));
export { $M100 as M100 };

export type M101 = $.Principal;
const $M101: $.Schema<M101> = $.c.rec(() => $.c.service({ call: $.c.func([$M102], [], "update") }));
export { $M101 as M101 };

export type M102 = { next: M103 };
const $M102: $.Schema<M102> = $.c.rec(() => $.c.record({ next: $M103 }));
export { $M102 as M102 };

export type M103 = M104 | null;
const $M103: $.Schema<M103> = $.c.rec(() => $.c.opt($M104));
export { $M103 as M103 };

export type M104 = { tag: "done" } | { tag: "more"; value: M105 };
const $M104: $.Schema<M104> = $.c.rec(() => $.c.variant({ done: $.c.null, more: $M105 }));
export { $M104 as M104 };

export type M105 = [bigint, M106];
const $M105: $.Schema<M105> = $.c.rec(() => $.c.tuple([$.c.nat, $M106]));
export { $M105 as M105 };

export type M106 = { principal: $.Principal; method: string };
const $M106: $.Schema<M106> = $.c.rec(() => $.c.func([$M107], [], "update"));
export { $M106 as M106 };

export type M107 = $.Principal;
const $M107: $.Schema<M107> = $.c.rec(() => $.c.service({ call: $.c.func([$M108], [], "update") }));
export { $M107 as M107 };

export type M108 = { next: M109 };
const $M108: $.Schema<M108> = $.c.rec(() => $.c.record({ next: $M109 }));
export { $M108 as M108 };

export type M109 = M110 | null;
const $M109: $.Schema<M109> = $.c.rec(() => $.c.opt($M110));
export { $M109 as M109 };

export type M11 = $.Principal;
const $M11: $.Schema<M11> = $.c.rec(() => $.c.service({ call: $.c.func([$M12], [], "update") }));
export { $M11 as M11 };

export type M110 = { tag: "done" } | { tag: "more"; value: M111 };
const $M110: $.Schema<M110> = $.c.rec(() => $.c.variant({ done: $.c.null, more: $M111 }));
export { $M110 as M110 };

export type M111 = [bigint, M112];
const $M111: $.Schema<M111> = $.c.rec(() => $.c.tuple([$.c.nat, $M112]));
export { $M111 as M111 };

export type M112 = { principal: $.Principal; method: string };
const $M112: $.Schema<M112> = $.c.rec(() => $.c.func([$M113], [], "update"));
export { $M112 as M112 };

export type M113 = $.Principal;
const $M113: $.Schema<M113> = $.c.rec(() => $.c.service({ call: $.c.func([$M114], [], "update") }));
export { $M113 as M113 };

export type M114 = { next: M115 };
const $M114: $.Schema<M114> = $.c.rec(() => $.c.record({ next: $M115 }));
export { $M114 as M114 };

export type M115 = M116 | null;
const $M115: $.Schema<M115> = $.c.rec(() => $.c.opt($M116));
export { $M115 as M115 };

export type M116 = { tag: "done" } | { tag: "more"; value: M117 };
const $M116: $.Schema<M116> = $.c.rec(() => $.c.variant({ done: $.c.null, more: $M117 }));
export { $M116 as M116 };

export type M117 = [bigint, M118];
const $M117: $.Schema<M117> = $.c.rec(() => $.c.tuple([$.c.nat, $M118]));
export { $M117 as M117 };

export type M118 = { principal: $.Principal; method: string };
const $M118: $.Schema<M118> = $.c.rec(() => $.c.func([$M119], [], "update"));
export { $M118 as M118 };

export type M119 = $.Principal;
const $M119: $.Schema<M119> = $.c.rec(() => $.c.service({ call: $.c.func([$M120], [], "update") }));
export { $M119 as M119 };

export type M12 = { next: M13 };
const $M12: $.Schema<M12> = $.c.rec(() => $.c.record({ next: $M13 }));
export { $M12 as M12 };

export type M120 = { next: M121 };
const $M120: $.Schema<M120> = $.c.rec(() => $.c.record({ next: $M121 }));
export { $M120 as M120 };

export type M121 = M122 | null;
const $M121: $.Schema<M121> = $.c.rec(() => $.c.opt($M122));
export { $M121 as M121 };

export type M122 = { tag: "done" } | { tag: "more"; value: M123 };
const $M122: $.Schema<M122> = $.c.rec(() => $.c.variant({ done: $.c.null, more: $M123 }));
export { $M122 as M122 };

export type M123 = [bigint, M124];
const $M123: $.Schema<M123> = $.c.rec(() => $.c.tuple([$.c.nat, $M124]));
export { $M123 as M123 };

export type M124 = { principal: $.Principal; method: string };
const $M124: $.Schema<M124> = $.c.rec(() => $.c.func([$M125], [], "update"));
export { $M124 as M124 };

export type M125 = $.Principal;
const $M125: $.Schema<M125> = $.c.rec(() => $.c.service({ call: $.c.func([$M126], [], "update") }));
export { $M125 as M125 };

export type M126 = { next: M127 };
const $M126: $.Schema<M126> = $.c.rec(() => $.c.record({ next: $M127 }));
export { $M126 as M126 };

export type M127 = M128 | null;
const $M127: $.Schema<M127> = $.c.rec(() => $.c.opt($M128));
export { $M127 as M127 };

export type M128 = { tag: "done" } | { tag: "more"; value: M129 };
const $M128: $.Schema<M128> = $.c.rec(() => $.c.variant({ done: $.c.null, more: $M129 }));
export { $M128 as M128 };

export type M129 = [bigint, M130];
const $M129: $.Schema<M129> = $.c.rec(() => $.c.tuple([$.c.nat, $M130]));
export { $M129 as M129 };

export type M13 = M14 | null;
const $M13: $.Schema<M13> = $.c.rec(() => $.c.opt($M14));
export { $M13 as M13 };

export type M130 = { principal: $.Principal; method: string };
const $M130: $.Schema<M130> = $.c.rec(() => $.c.func([$M131], [], "update"));
export { $M130 as M130 };

export type M131 = $.Principal;
const $M131: $.Schema<M131> = $.c.rec(() => $.c.service({ call: $.c.func([$M132], [], "update") }));
export { $M131 as M131 };

export type M132 = { next: M133 };
const $M132: $.Schema<M132> = $.c.rec(() => $.c.record({ next: $M133 }));
export { $M132 as M132 };

export type M133 = M134 | null;
const $M133: $.Schema<M133> = $.c.rec(() => $.c.opt($M134));
export { $M133 as M133 };

export type M134 = { tag: "done" } | { tag: "more"; value: M135 };
const $M134: $.Schema<M134> = $.c.rec(() => $.c.variant({ done: $.c.null, more: $M135 }));
export { $M134 as M134 };

export type M135 = [bigint, M136];
const $M135: $.Schema<M135> = $.c.rec(() => $.c.tuple([$.c.nat, $M136]));
export { $M135 as M135 };

export type M136 = { principal: $.Principal; method: string };
const $M136: $.Schema<M136> = $.c.rec(() => $.c.func([$M137], [], "update"));
export { $M136 as M136 };

export type M137 = $.Principal;
const $M137: $.Schema<M137> = $.c.rec(() => $.c.service({ call: $.c.func([$M138], [], "update") }));
export { $M137 as M137 };

export type M138 = { next: M139 };
const $M138: $.Schema<M138> = $.c.rec(() => $.c.record({ next: $M139 }));
export { $M138 as M138 };

export type M139 = M140 | null;
const $M139: $.Schema<M139> = $.c.rec(() => $.c.opt($M140));
export { $M139 as M139 };

export type M14 = { tag: "done" } | { tag: "more"; value: M15 };
const $M14: $.Schema<M14> = $.c.rec(() => $.c.variant({ done: $.c.null, more: $M15 }));
export { $M14 as M14 };

export type M140 = { tag: "done" } | { tag: "more"; value: M141 };
const $M140: $.Schema<M140> = $.c.rec(() => $.c.variant({ done: $.c.null, more: $M141 }));
export { $M140 as M140 };

export type M141 = [bigint, M142];
const $M141: $.Schema<M141> = $.c.rec(() => $.c.tuple([$.c.nat, $M142]));
export { $M141 as M141 };

export type M142 = { principal: $.Principal; method: string };
const $M142: $.Schema<M142> = $.c.rec(() => $.c.func([$M143], [], "update"));
export { $M142 as M142 };

export type M143 = $.Principal;
const $M143: $.Schema<M143> = $.c.rec(() => $.c.service({ call: $.c.func([$M144], [], "update") }));
export { $M143 as M143 };

export type M144 = { next: M145 };
const $M144: $.Schema<M144> = $.c.rec(() => $.c.record({ next: $M145 }));
export { $M144 as M144 };

export type M145 = M146 | null;
const $M145: $.Schema<M145> = $.c.rec(() => $.c.opt($M146));
export { $M145 as M145 };

export type M146 = { tag: "done" } | { tag: "more"; value: M147 };
const $M146: $.Schema<M146> = $.c.rec(() => $.c.variant({ done: $.c.null, more: $M147 }));
export { $M146 as M146 };

export type M147 = [bigint, M148];
const $M147: $.Schema<M147> = $.c.rec(() => $.c.tuple([$.c.nat, $M148]));
export { $M147 as M147 };

export type M148 = { principal: $.Principal; method: string };
const $M148: $.Schema<M148> = $.c.rec(() => $.c.func([$M149], [], "update"));
export { $M148 as M148 };

export type M149 = $.Principal;
const $M149: $.Schema<M149> = $.c.rec(() => $.c.service({ call: $.c.func([$M150], [], "update") }));
export { $M149 as M149 };

export type M15 = [bigint, M16];
const $M15: $.Schema<M15> = $.c.rec(() => $.c.tuple([$.c.nat, $M16]));
export { $M15 as M15 };

export type M150 = { next: M151 };
const $M150: $.Schema<M150> = $.c.rec(() => $.c.record({ next: $M151 }));
export { $M150 as M150 };

export type M151 = M152 | null;
const $M151: $.Schema<M151> = $.c.rec(() => $.c.opt($M152));
export { $M151 as M151 };

export type M152 = { tag: "done" } | { tag: "more"; value: M153 };
const $M152: $.Schema<M152> = $.c.rec(() => $.c.variant({ done: $.c.null, more: $M153 }));
export { $M152 as M152 };

export type M153 = [bigint, M154];
const $M153: $.Schema<M153> = $.c.rec(() => $.c.tuple([$.c.nat, $M154]));
export { $M153 as M153 };

export type M154 = { principal: $.Principal; method: string };
const $M154: $.Schema<M154> = $.c.rec(() => $.c.func([$M155], [], "update"));
export { $M154 as M154 };

export type M155 = $.Principal;
const $M155: $.Schema<M155> = $.c.rec(() => $.c.service({ call: $.c.func([$M156], [], "update") }));
export { $M155 as M155 };

export type M156 = { next: M157 };
const $M156: $.Schema<M156> = $.c.rec(() => $.c.record({ next: $M157 }));
export { $M156 as M156 };

export type M157 = M158 | null;
const $M157: $.Schema<M157> = $.c.rec(() => $.c.opt($M158));
export { $M157 as M157 };

export type M158 = { tag: "done" } | { tag: "more"; value: M159 };
const $M158: $.Schema<M158> = $.c.rec(() => $.c.variant({ done: $.c.null, more: $M159 }));
export { $M158 as M158 };

export type M159 = [bigint, M160];
const $M159: $.Schema<M159> = $.c.rec(() => $.c.tuple([$.c.nat, $M160]));
export { $M159 as M159 };

export type M16 = { principal: $.Principal; method: string };
const $M16: $.Schema<M16> = $.c.rec(() => $.c.func([$M17], [], "update"));
export { $M16 as M16 };

export type M160 = { principal: $.Principal; method: string };
const $M160: $.Schema<M160> = $.c.rec(() => $.c.func([$M161], [], "update"));
export { $M160 as M160 };

export type M161 = $.Principal;
const $M161: $.Schema<M161> = $.c.rec(() => $.c.service({ call: $.c.func([$M162], [], "update") }));
export { $M161 as M161 };

export type M162 = { next: M163 };
const $M162: $.Schema<M162> = $.c.rec(() => $.c.record({ next: $M163 }));
export { $M162 as M162 };

export type M163 = M164 | null;
const $M163: $.Schema<M163> = $.c.rec(() => $.c.opt($M164));
export { $M163 as M163 };

export type M164 = { tag: "done" } | { tag: "more"; value: M165 };
const $M164: $.Schema<M164> = $.c.rec(() => $.c.variant({ done: $.c.null, more: $M165 }));
export { $M164 as M164 };

export type M165 = [bigint, M166];
const $M165: $.Schema<M165> = $.c.rec(() => $.c.tuple([$.c.nat, $M166]));
export { $M165 as M165 };

export type M166 = { principal: $.Principal; method: string };
const $M166: $.Schema<M166> = $.c.rec(() => $.c.func([$M167], [], "update"));
export { $M166 as M166 };

export type M167 = $.Principal;
const $M167: $.Schema<M167> = $.c.rec(() => $.c.service({ call: $.c.func([$M168], [], "update") }));
export { $M167 as M167 };

export type M168 = { next: M169 };
const $M168: $.Schema<M168> = $.c.rec(() => $.c.record({ next: $M169 }));
export { $M168 as M168 };

export type M169 = M170 | null;
const $M169: $.Schema<M169> = $.c.rec(() => $.c.opt($M170));
export { $M169 as M169 };

export type M17 = $.Principal;
const $M17: $.Schema<M17> = $.c.rec(() => $.c.service({ call: $.c.func([$M18], [], "update") }));
export { $M17 as M17 };

export type M170 = { tag: "done" } | { tag: "more"; value: M171 };
const $M170: $.Schema<M170> = $.c.rec(() => $.c.variant({ done: $.c.null, more: $M171 }));
export { $M170 as M170 };

export type M171 = [bigint, M172];
const $M171: $.Schema<M171> = $.c.rec(() => $.c.tuple([$.c.nat, $M172]));
export { $M171 as M171 };

export type M172 = { principal: $.Principal; method: string };
const $M172: $.Schema<M172> = $.c.rec(() => $.c.func([$M173], [], "update"));
export { $M172 as M172 };

export type M173 = $.Principal;
const $M173: $.Schema<M173> = $.c.rec(() => $.c.service({ call: $.c.func([$M174], [], "update") }));
export { $M173 as M173 };

export type M174 = { next: M175 };
const $M174: $.Schema<M174> = $.c.rec(() => $.c.record({ next: $M175 }));
export { $M174 as M174 };

export type M175 = M176 | null;
const $M175: $.Schema<M175> = $.c.rec(() => $.c.opt($M176));
export { $M175 as M175 };

export type M176 = { tag: "done" } | { tag: "more"; value: M177 };
const $M176: $.Schema<M176> = $.c.rec(() => $.c.variant({ done: $.c.null, more: $M177 }));
export { $M176 as M176 };

export type M177 = [bigint, M178];
const $M177: $.Schema<M177> = $.c.rec(() => $.c.tuple([$.c.nat, $M178]));
export { $M177 as M177 };

export type M178 = { principal: $.Principal; method: string };
const $M178: $.Schema<M178> = $.c.rec(() => $.c.func([$M179], [], "update"));
export { $M178 as M178 };

export type M179 = $.Principal;
const $M179: $.Schema<M179> = $.c.rec(() => $.c.service({ call: $.c.func([$M180], [], "update") }));
export { $M179 as M179 };

export type M18 = { next: M19 };
const $M18: $.Schema<M18> = $.c.rec(() => $.c.record({ next: $M19 }));
export { $M18 as M18 };

export type M180 = { next: M181 };
const $M180: $.Schema<M180> = $.c.rec(() => $.c.record({ next: $M181 }));
export { $M180 as M180 };

export type M181 = M182 | null;
const $M181: $.Schema<M181> = $.c.rec(() => $.c.opt($M182));
export { $M181 as M181 };

export type M182 = { tag: "done" } | { tag: "more"; value: M183 };
const $M182: $.Schema<M182> = $.c.rec(() => $.c.variant({ done: $.c.null, more: $M183 }));
export { $M182 as M182 };

export type M183 = [bigint, M184];
const $M183: $.Schema<M183> = $.c.rec(() => $.c.tuple([$.c.nat, $M184]));
export { $M183 as M183 };

export type M184 = { principal: $.Principal; method: string };
const $M184: $.Schema<M184> = $.c.rec(() => $.c.func([$M185], [], "update"));
export { $M184 as M184 };

export type M185 = $.Principal;
const $M185: $.Schema<M185> = $.c.rec(() => $.c.service({ call: $.c.func([$M186], [], "update") }));
export { $M185 as M185 };

export type M186 = { next: M187 };
const $M186: $.Schema<M186> = $.c.rec(() => $.c.record({ next: $M187 }));
export { $M186 as M186 };

export type M187 = M188 | null;
const $M187: $.Schema<M187> = $.c.rec(() => $.c.opt($M188));
export { $M187 as M187 };

export type M188 = { tag: "done" } | { tag: "more"; value: M189 };
const $M188: $.Schema<M188> = $.c.rec(() => $.c.variant({ done: $.c.null, more: $M189 }));
export { $M188 as M188 };

export type M189 = [bigint, M190];
const $M189: $.Schema<M189> = $.c.rec(() => $.c.tuple([$.c.nat, $M190]));
export { $M189 as M189 };

export type M19 = M20 | null;
const $M19: $.Schema<M19> = $.c.rec(() => $.c.opt($M20));
export { $M19 as M19 };

export type M190 = { principal: $.Principal; method: string };
const $M190: $.Schema<M190> = $.c.rec(() => $.c.func([$M191], [], "update"));
export { $M190 as M190 };

export type M191 = $.Principal;
const $M191: $.Schema<M191> = $.c.rec(() => $.c.service({ call: $.c.func([$M192], [], "update") }));
export { $M191 as M191 };

export type M192 = { next: M193 };
const $M192: $.Schema<M192> = $.c.rec(() => $.c.record({ next: $M193 }));
export { $M192 as M192 };

export type M193 = M194 | null;
const $M193: $.Schema<M193> = $.c.rec(() => $.c.opt($M194));
export { $M193 as M193 };

export type M194 = { tag: "done" } | { tag: "more"; value: M195 };
const $M194: $.Schema<M194> = $.c.rec(() => $.c.variant({ done: $.c.null, more: $M195 }));
export { $M194 as M194 };

export type M195 = [bigint, M196];
const $M195: $.Schema<M195> = $.c.rec(() => $.c.tuple([$.c.nat, $M196]));
export { $M195 as M195 };

export type M196 = { principal: $.Principal; method: string };
const $M196: $.Schema<M196> = $.c.rec(() => $.c.func([$M197], [], "update"));
export { $M196 as M196 };

export type M197 = $.Principal;
const $M197: $.Schema<M197> = $.c.rec(() => $.c.service({ call: $.c.func([$M198], [], "update") }));
export { $M197 as M197 };

export type M198 = { next: M199 };
const $M198: $.Schema<M198> = $.c.rec(() => $.c.record({ next: $M199 }));
export { $M198 as M198 };

export type M199 = M200 | null;
const $M199: $.Schema<M199> = $.c.rec(() => $.c.opt($M200));
export { $M199 as M199 };

export type M2 = { tag: "done" } | { tag: "more"; value: M3 };
const $M2: $.Schema<M2> = $.c.rec(() => $.c.variant({ done: $.c.null, more: $M3 }));
export { $M2 as M2 };

export type M20 = { tag: "done" } | { tag: "more"; value: M21 };
const $M20: $.Schema<M20> = $.c.rec(() => $.c.variant({ done: $.c.null, more: $M21 }));
export { $M20 as M20 };

export type M200 = { tag: "done" } | { tag: "more"; value: M201 };
const $M200: $.Schema<M200> = $.c.rec(() => $.c.variant({ done: $.c.null, more: $M201 }));
export { $M200 as M200 };

export type M201 = [bigint, M202];
const $M201: $.Schema<M201> = $.c.rec(() => $.c.tuple([$.c.nat, $M202]));
export { $M201 as M201 };

export type M202 = { principal: $.Principal; method: string };
const $M202: $.Schema<M202> = $.c.rec(() => $.c.func([$M203], [], "update"));
export { $M202 as M202 };

export type M203 = $.Principal;
const $M203: $.Schema<M203> = $.c.rec(() => $.c.service({ call: $.c.func([$M204], [], "update") }));
export { $M203 as M203 };

export type M204 = { next: M205 };
const $M204: $.Schema<M204> = $.c.rec(() => $.c.record({ next: $M205 }));
export { $M204 as M204 };

export type M205 = M206 | null;
const $M205: $.Schema<M205> = $.c.rec(() => $.c.opt($M206));
export { $M205 as M205 };

export type M206 = { tag: "done" } | { tag: "more"; value: M207 };
const $M206: $.Schema<M206> = $.c.rec(() => $.c.variant({ done: $.c.null, more: $M207 }));
export { $M206 as M206 };

export type M207 = [bigint, M208];
const $M207: $.Schema<M207> = $.c.rec(() => $.c.tuple([$.c.nat, $M208]));
export { $M207 as M207 };

export type M208 = { principal: $.Principal; method: string };
const $M208: $.Schema<M208> = $.c.rec(() => $.c.func([$M209], [], "update"));
export { $M208 as M208 };

export type M209 = $.Principal;
const $M209: $.Schema<M209> = $.c.rec(() => $.c.service({ call: $.c.func([$M210], [], "update") }));
export { $M209 as M209 };

export type M21 = [bigint, M22];
const $M21: $.Schema<M21> = $.c.rec(() => $.c.tuple([$.c.nat, $M22]));
export { $M21 as M21 };

export type M210 = { next: M211 };
const $M210: $.Schema<M210> = $.c.rec(() => $.c.record({ next: $M211 }));
export { $M210 as M210 };

export type M211 = M212 | null;
const $M211: $.Schema<M211> = $.c.rec(() => $.c.opt($M212));
export { $M211 as M211 };

export type M212 = { tag: "done" } | { tag: "more"; value: M213 };
const $M212: $.Schema<M212> = $.c.rec(() => $.c.variant({ done: $.c.null, more: $M213 }));
export { $M212 as M212 };

export type M213 = [bigint, M214];
const $M213: $.Schema<M213> = $.c.rec(() => $.c.tuple([$.c.nat, $M214]));
export { $M213 as M213 };

export type M214 = { principal: $.Principal; method: string };
const $M214: $.Schema<M214> = $.c.rec(() => $.c.func([$M215], [], "update"));
export { $M214 as M214 };

export type M215 = Array<Array<Array<Array<Array<Array<Record<string, never>>>>>>>;
const $M215: $.Schema<M215> = $.c.rec(() => $.c.vec($.c.vec($.c.vec($.c.vec($.c.vec($.c.vec($.c.unit())))))));
export { $M215 as M215 };

export type M22 = { principal: $.Principal; method: string };
const $M22: $.Schema<M22> = $.c.rec(() => $.c.func([$M23], [], "update"));
export { $M22 as M22 };

export type M23 = $.Principal;
const $M23: $.Schema<M23> = $.c.rec(() => $.c.service({ call: $.c.func([$M24], [], "update") }));
export { $M23 as M23 };

export type M24 = { next: M25 };
const $M24: $.Schema<M24> = $.c.rec(() => $.c.record({ next: $M25 }));
export { $M24 as M24 };

export type M25 = M26 | null;
const $M25: $.Schema<M25> = $.c.rec(() => $.c.opt($M26));
export { $M25 as M25 };

export type M26 = { tag: "done" } | { tag: "more"; value: M27 };
const $M26: $.Schema<M26> = $.c.rec(() => $.c.variant({ done: $.c.null, more: $M27 }));
export { $M26 as M26 };

export type M27 = [bigint, M28];
const $M27: $.Schema<M27> = $.c.rec(() => $.c.tuple([$.c.nat, $M28]));
export { $M27 as M27 };

export type M28 = { principal: $.Principal; method: string };
const $M28: $.Schema<M28> = $.c.rec(() => $.c.func([$M29], [], "update"));
export { $M28 as M28 };

export type M29 = $.Principal;
const $M29: $.Schema<M29> = $.c.rec(() => $.c.service({ call: $.c.func([$M30], [], "update") }));
export { $M29 as M29 };

export type M3 = [bigint, M4];
const $M3: $.Schema<M3> = $.c.rec(() => $.c.tuple([$.c.nat, $M4]));
export { $M3 as M3 };

export type M30 = { next: M31 };
const $M30: $.Schema<M30> = $.c.rec(() => $.c.record({ next: $M31 }));
export { $M30 as M30 };

export type M31 = M32 | null;
const $M31: $.Schema<M31> = $.c.rec(() => $.c.opt($M32));
export { $M31 as M31 };

export type M32 = { tag: "done" } | { tag: "more"; value: M33 };
const $M32: $.Schema<M32> = $.c.rec(() => $.c.variant({ done: $.c.null, more: $M33 }));
export { $M32 as M32 };

export type M33 = [bigint, M34];
const $M33: $.Schema<M33> = $.c.rec(() => $.c.tuple([$.c.nat, $M34]));
export { $M33 as M33 };

export type M34 = { principal: $.Principal; method: string };
const $M34: $.Schema<M34> = $.c.rec(() => $.c.func([$M35], [], "update"));
export { $M34 as M34 };

export type M35 = $.Principal;
const $M35: $.Schema<M35> = $.c.rec(() => $.c.service({ call: $.c.func([$M36], [], "update") }));
export { $M35 as M35 };

export type M36 = { next: M37 };
const $M36: $.Schema<M36> = $.c.rec(() => $.c.record({ next: $M37 }));
export { $M36 as M36 };

export type M37 = M38 | null;
const $M37: $.Schema<M37> = $.c.rec(() => $.c.opt($M38));
export { $M37 as M37 };

export type M38 = { tag: "done" } | { tag: "more"; value: M39 };
const $M38: $.Schema<M38> = $.c.rec(() => $.c.variant({ done: $.c.null, more: $M39 }));
export { $M38 as M38 };

export type M39 = [bigint, M40];
const $M39: $.Schema<M39> = $.c.rec(() => $.c.tuple([$.c.nat, $M40]));
export { $M39 as M39 };

export type M4 = { principal: $.Principal; method: string };
const $M4: $.Schema<M4> = $.c.rec(() => $.c.func([$M5], [], "update"));
export { $M4 as M4 };

export type M40 = { principal: $.Principal; method: string };
const $M40: $.Schema<M40> = $.c.rec(() => $.c.func([$M41], [], "update"));
export { $M40 as M40 };

export type M41 = $.Principal;
const $M41: $.Schema<M41> = $.c.rec(() => $.c.service({ call: $.c.func([$M42], [], "update") }));
export { $M41 as M41 };

export type M42 = { next: M43 };
const $M42: $.Schema<M42> = $.c.rec(() => $.c.record({ next: $M43 }));
export { $M42 as M42 };

export type M43 = M44 | null;
const $M43: $.Schema<M43> = $.c.rec(() => $.c.opt($M44));
export { $M43 as M43 };

export type M44 = { tag: "done" } | { tag: "more"; value: M45 };
const $M44: $.Schema<M44> = $.c.rec(() => $.c.variant({ done: $.c.null, more: $M45 }));
export { $M44 as M44 };

export type M45 = [bigint, M46];
const $M45: $.Schema<M45> = $.c.rec(() => $.c.tuple([$.c.nat, $M46]));
export { $M45 as M45 };

export type M46 = { principal: $.Principal; method: string };
const $M46: $.Schema<M46> = $.c.rec(() => $.c.func([$M47], [], "update"));
export { $M46 as M46 };

export type M47 = $.Principal;
const $M47: $.Schema<M47> = $.c.rec(() => $.c.service({ call: $.c.func([$M48], [], "update") }));
export { $M47 as M47 };

export type M48 = { next: M49 };
const $M48: $.Schema<M48> = $.c.rec(() => $.c.record({ next: $M49 }));
export { $M48 as M48 };

export type M49 = M50 | null;
const $M49: $.Schema<M49> = $.c.rec(() => $.c.opt($M50));
export { $M49 as M49 };

export type M5 = $.Principal;
const $M5: $.Schema<M5> = $.c.rec(() => $.c.service({ call: $.c.func([$M6], [], "update") }));
export { $M5 as M5 };

export type M50 = { tag: "done" } | { tag: "more"; value: M51 };
const $M50: $.Schema<M50> = $.c.rec(() => $.c.variant({ done: $.c.null, more: $M51 }));
export { $M50 as M50 };

export type M51 = [bigint, M52];
const $M51: $.Schema<M51> = $.c.rec(() => $.c.tuple([$.c.nat, $M52]));
export { $M51 as M51 };

export type M52 = { principal: $.Principal; method: string };
const $M52: $.Schema<M52> = $.c.rec(() => $.c.func([$M53], [], "update"));
export { $M52 as M52 };

export type M53 = $.Principal;
const $M53: $.Schema<M53> = $.c.rec(() => $.c.service({ call: $.c.func([$M54], [], "update") }));
export { $M53 as M53 };

export type M54 = { next: M55 };
const $M54: $.Schema<M54> = $.c.rec(() => $.c.record({ next: $M55 }));
export { $M54 as M54 };

export type M55 = M56 | null;
const $M55: $.Schema<M55> = $.c.rec(() => $.c.opt($M56));
export { $M55 as M55 };

export type M56 = { tag: "done" } | { tag: "more"; value: M57 };
const $M56: $.Schema<M56> = $.c.rec(() => $.c.variant({ done: $.c.null, more: $M57 }));
export { $M56 as M56 };

export type M57 = [bigint, M58];
const $M57: $.Schema<M57> = $.c.rec(() => $.c.tuple([$.c.nat, $M58]));
export { $M57 as M57 };

export type M58 = { principal: $.Principal; method: string };
const $M58: $.Schema<M58> = $.c.rec(() => $.c.func([$M59], [], "update"));
export { $M58 as M58 };

export type M59 = $.Principal;
const $M59: $.Schema<M59> = $.c.rec(() => $.c.service({ call: $.c.func([$M60], [], "update") }));
export { $M59 as M59 };

export type M6 = { next: M7 };
const $M6: $.Schema<M6> = $.c.rec(() => $.c.record({ next: $M7 }));
export { $M6 as M6 };

export type M60 = { next: M61 };
const $M60: $.Schema<M60> = $.c.rec(() => $.c.record({ next: $M61 }));
export { $M60 as M60 };

export type M61 = M62 | null;
const $M61: $.Schema<M61> = $.c.rec(() => $.c.opt($M62));
export { $M61 as M61 };

export type M62 = { tag: "done" } | { tag: "more"; value: M63 };
const $M62: $.Schema<M62> = $.c.rec(() => $.c.variant({ done: $.c.null, more: $M63 }));
export { $M62 as M62 };

export type M63 = [bigint, M64];
const $M63: $.Schema<M63> = $.c.rec(() => $.c.tuple([$.c.nat, $M64]));
export { $M63 as M63 };

export type M64 = { principal: $.Principal; method: string };
const $M64: $.Schema<M64> = $.c.rec(() => $.c.func([$M65], [], "update"));
export { $M64 as M64 };

export type M65 = $.Principal;
const $M65: $.Schema<M65> = $.c.rec(() => $.c.service({ call: $.c.func([$M66], [], "update") }));
export { $M65 as M65 };

export type M66 = { next: M67 };
const $M66: $.Schema<M66> = $.c.rec(() => $.c.record({ next: $M67 }));
export { $M66 as M66 };

export type M67 = M68 | null;
const $M67: $.Schema<M67> = $.c.rec(() => $.c.opt($M68));
export { $M67 as M67 };

export type M68 = { tag: "done" } | { tag: "more"; value: M69 };
const $M68: $.Schema<M68> = $.c.rec(() => $.c.variant({ done: $.c.null, more: $M69 }));
export { $M68 as M68 };

export type M69 = [bigint, M70];
const $M69: $.Schema<M69> = $.c.rec(() => $.c.tuple([$.c.nat, $M70]));
export { $M69 as M69 };

export type M7 = M8 | null;
const $M7: $.Schema<M7> = $.c.rec(() => $.c.opt($M8));
export { $M7 as M7 };

export type M70 = { principal: $.Principal; method: string };
const $M70: $.Schema<M70> = $.c.rec(() => $.c.func([$M71], [], "update"));
export { $M70 as M70 };

export type M71 = $.Principal;
const $M71: $.Schema<M71> = $.c.rec(() => $.c.service({ call: $.c.func([$M72], [], "update") }));
export { $M71 as M71 };

export type M72 = { next: M73 };
const $M72: $.Schema<M72> = $.c.rec(() => $.c.record({ next: $M73 }));
export { $M72 as M72 };

export type M73 = M74 | null;
const $M73: $.Schema<M73> = $.c.rec(() => $.c.opt($M74));
export { $M73 as M73 };

export type M74 = { tag: "done" } | { tag: "more"; value: M75 };
const $M74: $.Schema<M74> = $.c.rec(() => $.c.variant({ done: $.c.null, more: $M75 }));
export { $M74 as M74 };

export type M75 = [bigint, M76];
const $M75: $.Schema<M75> = $.c.rec(() => $.c.tuple([$.c.nat, $M76]));
export { $M75 as M75 };

export type M76 = { principal: $.Principal; method: string };
const $M76: $.Schema<M76> = $.c.rec(() => $.c.func([$M77], [], "update"));
export { $M76 as M76 };

export type M77 = $.Principal;
const $M77: $.Schema<M77> = $.c.rec(() => $.c.service({ call: $.c.func([$M78], [], "update") }));
export { $M77 as M77 };

export type M78 = { next: M79 };
const $M78: $.Schema<M78> = $.c.rec(() => $.c.record({ next: $M79 }));
export { $M78 as M78 };

export type M79 = M80 | null;
const $M79: $.Schema<M79> = $.c.rec(() => $.c.opt($M80));
export { $M79 as M79 };

export type M8 = { tag: "done" } | { tag: "more"; value: M9 };
const $M8: $.Schema<M8> = $.c.rec(() => $.c.variant({ done: $.c.null, more: $M9 }));
export { $M8 as M8 };

export type M80 = { tag: "done" } | { tag: "more"; value: M81 };
const $M80: $.Schema<M80> = $.c.rec(() => $.c.variant({ done: $.c.null, more: $M81 }));
export { $M80 as M80 };

export type M81 = [bigint, M82];
const $M81: $.Schema<M81> = $.c.rec(() => $.c.tuple([$.c.nat, $M82]));
export { $M81 as M81 };

export type M82 = { principal: $.Principal; method: string };
const $M82: $.Schema<M82> = $.c.rec(() => $.c.func([$M83], [], "update"));
export { $M82 as M82 };

export type M83 = $.Principal;
const $M83: $.Schema<M83> = $.c.rec(() => $.c.service({ call: $.c.func([$M84], [], "update") }));
export { $M83 as M83 };

export type M84 = { next: M85 };
const $M84: $.Schema<M84> = $.c.rec(() => $.c.record({ next: $M85 }));
export { $M84 as M84 };

export type M85 = M86 | null;
const $M85: $.Schema<M85> = $.c.rec(() => $.c.opt($M86));
export { $M85 as M85 };

export type M86 = { tag: "done" } | { tag: "more"; value: M87 };
const $M86: $.Schema<M86> = $.c.rec(() => $.c.variant({ done: $.c.null, more: $M87 }));
export { $M86 as M86 };

export type M87 = [bigint, M88];
const $M87: $.Schema<M87> = $.c.rec(() => $.c.tuple([$.c.nat, $M88]));
export { $M87 as M87 };

export type M88 = { principal: $.Principal; method: string };
const $M88: $.Schema<M88> = $.c.rec(() => $.c.func([$M89], [], "update"));
export { $M88 as M88 };

export type M89 = $.Principal;
const $M89: $.Schema<M89> = $.c.rec(() => $.c.service({ call: $.c.func([$M90], [], "update") }));
export { $M89 as M89 };

export type M9 = [bigint, M10];
const $M9: $.Schema<M9> = $.c.rec(() => $.c.tuple([$.c.nat, $M10]));
export { $M9 as M9 };

export type M90 = { next: M91 };
const $M90: $.Schema<M90> = $.c.rec(() => $.c.record({ next: $M91 }));
export { $M90 as M90 };

export type M91 = M92 | null;
const $M91: $.Schema<M91> = $.c.rec(() => $.c.opt($M92));
export { $M91 as M91 };

export type M92 = { tag: "done" } | { tag: "more"; value: M93 };
const $M92: $.Schema<M92> = $.c.rec(() => $.c.variant({ done: $.c.null, more: $M93 }));
export { $M92 as M92 };

export type M93 = [bigint, M94];
const $M93: $.Schema<M93> = $.c.rec(() => $.c.tuple([$.c.nat, $M94]));
export { $M93 as M93 };

export type M94 = { principal: $.Principal; method: string };
const $M94: $.Schema<M94> = $.c.rec(() => $.c.func([$M95], [], "update"));
export { $M94 as M94 };

export type M95 = $.Principal;
const $M95: $.Schema<M95> = $.c.rec(() => $.c.service({ call: $.c.func([$M96], [], "update") }));
export { $M95 as M95 };

export type M96 = { next: M97 };
const $M96: $.Schema<M96> = $.c.rec(() => $.c.record({ next: $M97 }));
export { $M96 as M96 };

export type M97 = M98 | null;
const $M97: $.Schema<M97> = $.c.rec(() => $.c.opt($M98));
export { $M97 as M97 };

export type M98 = { tag: "done" } | { tag: "more"; value: M99 };
const $M98: $.Schema<M98> = $.c.rec(() => $.c.variant({ done: $.c.null, more: $M99 }));
export { $M98 as M98 };

export type M99 = [bigint, M100];
const $M99: $.Schema<M99> = $.c.rec(() => $.c.tuple([$.c.nat, $M100]));
export { $M99 as M99 };
