//! Contracts no Candid source produces, which Contract validation accepts
//! (issue #218): chains far deeper than the compiler's 256-level bound, and
//! cycles that pass through no declaration.
//!
//! Generation must either succeed or return `Err` for every Contract
//! `Contract::from_json_with_limits` or `ContractDraft::build_with_limits`
//! accepts — never abort and never fail to terminate — on a thread of
//! `SMALL_STACK_BYTES`, in the dev and the release profile. Each test runs
//! in a child process, because the failure it guards against kills the
//! process (see `support`). The Contracts are built on the test thread;
//! only generation runs on the small one.

mod support;

use candid_core::{
    Contract, ContractDraft, Declaration, Field, Limits, PrimitiveType, TypeNode, TypeRef,
};
use candid_core_ts::{generate_module, GeneratedModule, TsGenError, TsNames, TsOptions};
use support::{in_child_process, on_small_stack};

/// The Contract of `type D = vec T; type T = opt T;` with the declaration of
/// `T` removed, as issue #218 gives it (465 bytes there with the file's
/// trailing newline, 464 here), accepted by `Contract::from_json` at default
/// limits, and before issue #218 an infinite recursion at any stack size.
const UNDECLARED_SELF_CYCLE: &str = r#"{"format":"candid-core","format_version":1,"semantics_profile":"candid-1","canonicalization_profile":"candid-core-canon-1","identities":{"contract":"candid-core:contract:v1:sha256:421991979930a94cee5e8e910aaf7abd0e87458e7d4ae4aaf1e4140ba68e82e2"},"producer":{"name":"candid-core","version":"0.1.0-beta.3","candid_version":"0.10.30","candid_parser_version":"0.4.0"},"types":[{"kind":"vec","inner":1},{"kind":"opt","inner":1}],"declarations":[{"name":"D","type":0}]}"#;

/// Generate on a small-stack thread with no field names and default options.
fn generate_small(contract: Contract) -> Result<GeneratedModule, TsGenError> {
    on_small_stack(move || generate_module(&contract, &TsNames::new(), &TsOptions::default()))
}

/// `nat <- opt <- opt <- …`, `depth` opts, the outermost declared `D`.
fn opt_chain(depth: usize) -> ContractDraft {
    let mut types = vec![TypeNode::Primitive {
        primitive: PrimitiveType::Nat,
    }];
    for inner in 0..depth {
        types.push(TypeNode::Opt {
            inner: TypeRef::try_from(inner).expect("the chain fits a TypeRef"),
        });
    }
    ContractDraft::new(
        types,
        vec![Declaration {
            name: "D".to_string(),
            ty: TypeRef::try_from(depth).expect("the chain fits a TypeRef"),
        }],
        None,
    )
}

/// The exact module for `opt_chain(depth)`, `depth >= 1`. The innermost
/// `opt nat` is `bigint | null`; every opt over an opt is boxed.
fn opt_chain_module(depth: usize) -> String {
    let alias = format!(
        "{}bigint | null{}",
        "{ some: ".repeat(depth - 1),
        " } | null".repeat(depth - 1)
    );
    let builder = format!("{}$.c.nat{}", "$.c.opt(".repeat(depth), ")".repeat(depth));
    format!(
        "// Generated by candid-core-ts from a candid-core Contract. Do not edit.\n\
         import * as $ from \"@candid-core/schema\";\n\
         \n\
         type $D = {alias};\n\
         const $D: $.Schema<$D> = $.c.rec(() => {builder});\n\
         export {{ $D as D }};\n"
    )
}

/// The chain text formula, checked where a reviewer can read it.
#[test]
fn the_chain_formula_matches_a_shallow_chain() {
    let contract = opt_chain(3).build().expect("a shallow chain builds");
    let module = generate_module(&contract, &TsNames::new(), &TsOptions::default())
        .expect("a shallow chain generates");
    assert_eq!(
        module.module,
        "// Generated by candid-core-ts from a candid-core Contract. Do not edit.\n\
         import * as $ from \"@candid-core/schema\";\n\
         \n\
         type $D = { some: { some: bigint | null } | null } | null;\n\
         const $D: $.Schema<$D> = $.c.rec(() => $.c.opt($.c.opt($.c.opt($.c.nat))));\n\
         export { $D as D };\n"
    );
    assert_eq!(module.module, opt_chain_module(3));
}

/// 1,500 levels: past the compiler's bound and accepted at default limits
/// (the ceiling for this chain is 1,810). Before issue #218 it needed about
/// 1.1 MiB of stack in release and 11 MiB in dev.
#[test]
fn a_1500_level_chain_generates_on_a_small_stack() {
    in_child_process("a_1500_level_chain_generates_on_a_small_stack", || {
        let contract = opt_chain(1_500)
            .build()
            .expect("1,500 levels build at default limits");
        let module = generate_small(contract).expect("the chain generates");
        assert!(module.omitted.is_empty());
        assert_eq!(module.module, opt_chain_module(1_500));
    });
}

/// 2,000 levels: beyond what default limits accept for this chain (the
/// first refused depth is 1,811, `canonicalization_work` observed 10,010,366
/// against 10,000,000), so a trusted host raised `max_canonicalization_work`
/// to build it (about 12.2M work units). Canonicalization is quadratic in
/// this chain's depth and dominates the test's time, so it builds once, at
/// the raised limit, and does not re-read.
#[test]
fn a_chain_beyond_the_default_ceiling_generates_on_a_small_stack() {
    in_child_process(
        "a_chain_beyond_the_default_ceiling_generates_on_a_small_stack",
        || {
            const DEPTH: usize = 2_000;
            let limits = Limits::default().with_max_canonicalization_work(15_000_000);
            let contract = opt_chain(DEPTH)
                .build_with_limits(&limits)
                .expect("the chain builds at the raised limit");
            let module = generate_small(contract).expect("the chain generates");
            assert!(module.omitted.is_empty());
            assert_eq!(module.module, opt_chain_module(DEPTH));
        },
    );
}

/// A cycle through `members` (arena indices `0..`, each member's edge
/// pointing at the next and the last at the first), reached from a declared
/// `D = variant { 2 : <member 0> }`, with the members at the indices in
/// `declare` declared too, as `N{index}`. The Contract is built and then
/// re-read, as one from a registry or an agent arrives.
fn cycle(members: Vec<TypeNode>, declare: &[TypeRef]) -> Contract {
    let entry = TypeRef::try_from(members.len()).expect("the cycle fits a TypeRef");
    let mut types = members;
    types.push(TypeNode::Variant {
        fields: vec![Field { id: 2, ty: 0 }],
    });
    let mut declarations = vec![Declaration {
        name: "D".to_string(),
        ty: entry,
    }];
    for &index in declare {
        declarations.push(Declaration {
            name: format!("N{index}"),
            ty: index,
        });
    }
    let contract = ContractDraft::new(types, declarations, None)
        .build()
        .expect("Contract validation accepts every cycle");
    Contract::from_json(&serde_json::to_string(&contract).expect("the Contract serializes"))
        .expect("the document is a valid canonical Contract")
}

/// `record { 1 : opt <the record> }`, as two nodes.
fn two_nodes() -> Vec<TypeNode> {
    vec![
        TypeNode::Record {
            fields: vec![Field { id: 1, ty: 1 }],
        },
        TypeNode::Opt { inner: 0 },
    ]
}

/// `record -> opt -> vec -> record`.
fn three_nodes() -> Vec<TypeNode> {
    vec![
        TypeNode::Record {
            fields: vec![Field { id: 1, ty: 1 }],
        },
        TypeNode::Opt { inner: 2 },
        TypeNode::Vec { inner: 0 },
    ]
}

#[test]
fn cycles_through_no_declaration_are_refused() {
    in_child_process("cycles_through_no_declaration_are_refused", || {
        let contract =
            Contract::from_json(UNDECLARED_SELF_CYCLE).expect("accepted at default limits");
        assert_eq!(UNDECLARED_SELF_CYCLE.len(), 464);
        let refusal = generate_small(contract).expect_err("an undeclared cycle refuses");
        assert_eq!(refusal, TsGenError::UndeclaredCycle { reference: 1 });
        assert_eq!(
            refusal.to_string(),
            "type node 1 lies on a cycle that passes through no declaration; a \
             TypeScript type alias cannot spell an anonymous cycle (issue #218)"
        );

        for (name, members) in [("two-node", two_nodes()), ("three-node", three_nodes())] {
            let contract = cycle(members, &[]);
            // The canonical arena orders the nodes. The search starts from
            // the first undeclared node in that order — every cycle member,
            // here, since only `D` is declared — and reports the node whose
            // incoming edge closes the cycle, which is that start.
            let first = contract
                .types()
                .iter()
                .position(|node| !matches!(node, TypeNode::Variant { .. }))
                .map(|index| TypeRef::try_from(index).expect("arena indices fit a TypeRef"))
                .expect("the cycle has members");
            let refusal = generate_small(contract).expect_err("an undeclared cycle refuses");
            assert_eq!(
                refusal,
                TsGenError::UndeclaredCycle { reference: first },
                "{name}"
            );
            assert!(
                refusal
                    .to_string()
                    .starts_with(&format!("type node {first} lies on a cycle")),
                "{name}: the message names the node: {refusal}"
            );
        }
    });
}

#[test]
fn the_same_cycle_with_one_member_declared_generates() {
    in_child_process("the_same_cycle_with_one_member_declared_generates", || {
        for (name, members, count) in [
            ("two-node", two_nodes as fn() -> Vec<TypeNode>, 2),
            ("three-node", three_nodes, 3),
        ] {
            for member in 0..count {
                let module = generate_small(cycle(members(), &[member])).unwrap_or_else(|error| {
                    panic!("{name}: declaring member {member} must generate: {error}")
                });
                assert!(module.omitted.is_empty(), "{name}: {:?}", module.omitted);
            }
        }
        // One text in full: the cycle written through the declared record.
        let module = generate_small(cycle(three_nodes(), &[0])).expect("generates");
        assert_eq!(
                module.module,
                "// Generated by candid-core-ts from a candid-core Contract. Do not edit.\n\
                 import * as $ from \"@candid-core/schema\";\n\
                 \n\
                 type $D = { tag: \"_2_\"; value: $N0 };\n\
                 const $D: $.Schema<$D> = $.c.rec(() => $.c.variant({ _2_: $N0 }));\n\
                 export { $D as D };\n\
                 \n\
                 type $N0 = { _1_: Array<$N0> | null };\n\
                 const $N0: $.Schema<$N0> = $.c.rec(() => $.c.record({ _1_: $.c.opt($.c.vec($N0)) }));\n\
                 export { $N0 as N0 };\n"
            );
    });
}
