//! Contracts no Candid source produces, which Contract validation accepts
//! (issue #218): chains far deeper than the compiler's 256-level bound, and
//! cycles that pass through no declaration.
//!
//! Generation must either succeed or return `Err` for every Contract
//! `Contract::from_json_with_limits` or `ContractDraft::build_with_limits`
//! accepts — never abort and never fail to terminate — on a thread of
//! `SMALL_STACK_BYTES`, in the dev and the release profile. Each test runs
//! in a child process, because the failure it guards against kills the
//! process (see `support`). The Contracts are built on the test thread;
//! only generation runs on the small one.

mod support;

use candid_core::{
    Actor, Contract, ContractDraft, Declaration, Field, Limits, MethodMode, PrimitiveType,
    ServiceMethod, TypeNode, TypeRef,
};
use candid_core_ts::{generate_module, GeneratedModule, TsGenError, TsNames, TsOptions};
use support::{in_child_process, on_small_stack};

/// The Contract of `type D = vec T; type T = opt T;` with the declaration of
/// `T` removed, as issue #218 gives it (465 bytes there with the file's
/// trailing newline, 464 here), accepted by `Contract::from_json` at default
/// limits, and before issue #218 an infinite recursion at any stack size.
const UNDECLARED_SELF_CYCLE: &str = r#"{"format":"candid-core","format_version":1,"semantics_profile":"candid-1","canonicalization_profile":"candid-core-canon-1","identities":{"contract":"candid-core:contract:v1:sha256:421991979930a94cee5e8e910aaf7abd0e87458e7d4ae4aaf1e4140ba68e82e2"},"producer":{"name":"candid-core","version":"0.1.0-beta.3","candid_version":"0.10.30","candid_parser_version":"0.4.0"},"types":[{"kind":"vec","inner":1},{"kind":"opt","inner":1}],"declarations":[{"name":"D","type":0}]}"#;

/// Generate on a small-stack thread with no field names and default options.
fn generate_small(contract: Contract) -> Result<GeneratedModule, TsGenError> {
    on_small_stack(move || generate_module(&contract, &TsNames::new(), &TsOptions::default()))
}

/// `nat <- opt <- opt <- …`, `depth` opts, the outermost declared `D`.
fn opt_chain(depth: usize) -> ContractDraft {
    let mut types = vec![TypeNode::Primitive {
        primitive: PrimitiveType::Nat,
    }];
    for inner in 0..depth {
        types.push(TypeNode::Opt {
            inner: TypeRef::try_from(inner).expect("the chain fits a TypeRef"),
        });
    }
    ContractDraft::new(
        types,
        vec![Declaration {
            name: "D".to_string(),
            ty: TypeRef::try_from(depth).expect("the chain fits a TypeRef"),
        }],
        None,
    )
}

/// The exact module for `opt_chain(depth)`, `depth >= 1`. The innermost
/// `opt nat` is `bigint | null`; every opt over an opt is boxed.
fn opt_chain_module(depth: usize) -> String {
    let alias = format!(
        "{}bigint | null{}",
        "{ some: ".repeat(depth - 1),
        " } | null".repeat(depth - 1)
    );
    let builder = format!("{}$.c.nat{}", "$.c.opt(".repeat(depth), ")".repeat(depth));
    format!(
        "// Generated by candid-core-ts from a candid-core Contract. Do not edit.\n\
         import * as $ from \"@candid-core/schema\";\n\
         \n\
         type $D = {alias};\n\
         const $D: $.Schema<$D> = $.c.rec(() => {builder});\n\
         export {{ $D as D }};\n"
    )
}

/// The chain text formula, checked where a reviewer can read it.
#[test]
fn the_chain_formula_matches_a_shallow_chain() {
    let contract = opt_chain(3).build().expect("a shallow chain builds");
    let module = generate_module(&contract, &TsNames::new(), &TsOptions::default())
        .expect("a shallow chain generates");
    assert_eq!(
        module.module,
        "// Generated by candid-core-ts from a candid-core Contract. Do not edit.\n\
         import * as $ from \"@candid-core/schema\";\n\
         \n\
         type $D = { some: { some: bigint | null } | null } | null;\n\
         const $D: $.Schema<$D> = $.c.rec(() => $.c.opt($.c.opt($.c.opt($.c.nat))));\n\
         export { $D as D };\n"
    );
    assert_eq!(module.module, opt_chain_module(3));
}

/// 1,500 levels: past the compiler's bound and accepted at default limits
/// (the ceiling for this chain is 1,810). Before issue #218 it needed about
/// 1.1 MiB of stack in release and 11 MiB in dev.
#[test]
fn a_1500_level_chain_generates_on_a_small_stack() {
    in_child_process("a_1500_level_chain_generates_on_a_small_stack", || {
        let contract = opt_chain(1_500)
            .build()
            .expect("1,500 levels build at default limits");
        let module = generate_small(contract).expect("the chain generates");
        assert!(module.omitted.is_empty());
        assert_eq!(module.module, opt_chain_module(1_500));
    });
}

/// 2,000 levels: beyond what default limits accept for this chain (the
/// first refused depth is 1,811, `canonicalization_work` observed 10,010,366
/// against 10,000,000), so a trusted host raised `max_canonicalization_work`
/// to build it (about 12.2M work units). Canonicalization is quadratic in
/// this chain's depth and dominates the test's time, so it builds at the
/// raised limit and does not re-read, and the test checks that default
/// limits refuse the chain — that it is beyond the ceiling — in the release
/// profile only, where that second canonicalization is cheap.
#[test]
fn a_chain_beyond_the_default_ceiling_generates_on_a_small_stack() {
    in_child_process(
        "a_chain_beyond_the_default_ceiling_generates_on_a_small_stack",
        || {
            const DEPTH: usize = 2_000;
            if !cfg!(debug_assertions) {
                let refusal = opt_chain(DEPTH)
                    .build()
                    .expect_err("default limits refuse the chain");
                let limit = refusal
                    .violations
                    .iter()
                    .find_map(|violation| violation.resource_limit.as_ref())
                    .expect("a resource limit refuses the chain");
                assert_eq!(limit.resource, "canonicalization_work");
            }
            let limits = Limits::default().with_max_canonicalization_work(15_000_000);
            let contract = opt_chain(DEPTH)
                .build_with_limits(&limits)
                .expect("the chain builds at the raised limit");
            let module = generate_small(contract).expect("the chain generates");
            assert!(module.omitted.is_empty());
            assert_eq!(module.module, opt_chain_module(DEPTH));
        },
    );
}

/// The composite kinds other than `opt`, each nested through the position
/// the renderer walks, so every frame kind of `Generator::walk` is shown to
/// use no call stack per level: reintroducing a recursive call in any one of
/// them overflows the small stack (about 0.75 KiB per level in release
/// before issue #218, so 85 levels exceed 64 KiB; each chain nests at least
/// 250 recursive levels for every frame kind).
#[derive(Clone, Copy, Debug)]
enum Kind {
    /// `record { 1 : <inner> }`.
    Record,
    /// `variant { 1 : <inner> }`.
    Variant,
    /// `record { 0 : <inner> }`, which renders as a tuple.
    Tuple,
    /// `service { m : func (<inner>) -> () }`: two nodes a level, and the
    /// func frame renders the argument.
    Service,
}

impl Kind {
    /// The number of levels a test nests, all accepted at default limits.
    fn depth(self) -> usize {
        match self {
            Kind::Service => 250,
            _ => 500,
        }
    }
}

/// `depth` levels of `kind` around `nat`, the outermost declared `D`, never
/// a declared node in between.
fn composite_chain(kind: Kind, depth: usize) -> ContractDraft {
    let mut types = vec![TypeNode::Primitive {
        primitive: PrimitiveType::Nat,
    }];
    let reference = |index: usize| TypeRef::try_from(index).expect("the chain fits a TypeRef");
    for _ in 0..depth {
        let inner = reference(types.len() - 1);
        match kind {
            Kind::Record => types.push(TypeNode::Record {
                fields: vec![Field { id: 1, ty: inner }],
            }),
            Kind::Variant => types.push(TypeNode::Variant {
                fields: vec![Field { id: 1, ty: inner }],
            }),
            Kind::Tuple => types.push(TypeNode::Record {
                fields: vec![Field { id: 0, ty: inner }],
            }),
            Kind::Service => {
                types.push(func(vec![inner]));
                types.push(TypeNode::Service {
                    methods: vec![method("m", reference(types.len() - 1))],
                });
            }
        }
    }
    let outermost = reference(types.len() - 1);
    ContractDraft::new(
        types,
        vec![Declaration {
            name: "D".to_string(),
            ty: outermost,
        }],
        None,
    )
}

/// The exact module for `composite_chain(kind, depth)`, `depth >= 1`.
fn composite_chain_module(kind: Kind, depth: usize) -> String {
    let wrap = |open: &str, leaf: &str, close: &str| {
        format!("{}{leaf}{}", open.repeat(depth), close.repeat(depth))
    };
    let (alias, builder) = match kind {
        Kind::Record => (
            wrap("{ _1_: ", "bigint", " }"),
            wrap("$.c.record({ _1_: ", "$.c.nat", " })"),
        ),
        Kind::Variant => (
            wrap("{ tag: \"_1_\"; value: ", "bigint", " }"),
            wrap("$.c.variant({ _1_: ", "$.c.nat", " })"),
        ),
        Kind::Tuple => (
            wrap("[", "bigint", "]"),
            wrap("$.c.tuple([", "$.c.nat", "])"),
        ),
        Kind::Service => (
            "$.Principal".to_string(),
            wrap(
                "$.c.service({ m: $.c.func([",
                "$.c.nat",
                "], [], \"update\") })",
            ),
        ),
    };
    format!(
        "// Generated by candid-core-ts from a candid-core Contract. Do not edit.\n\
         import * as $ from \"@candid-core/schema\";\n\
         \n\
         type $D = {alias};\n\
         const $D: $.Schema<$D> = $.c.rec(() => {builder});\n\
         export {{ $D as D }};\n"
    )
}

const KINDS: [Kind; 4] = [Kind::Record, Kind::Variant, Kind::Tuple, Kind::Service];

/// The composite chain formulas, checked against two-level texts a reviewer
/// can read.
#[test]
fn the_composite_chain_formulas_match_shallow_chains() {
    let expected = [
        (
            "{ _1_: { _1_: bigint } }",
            "$.c.record({ _1_: $.c.record({ _1_: $.c.nat }) })",
        ),
        (
            "{ tag: \"_1_\"; value: { tag: \"_1_\"; value: bigint } }",
            "$.c.variant({ _1_: $.c.variant({ _1_: $.c.nat }) })",
        ),
        ("[[bigint]]", "$.c.tuple([$.c.tuple([$.c.nat])])"),
        (
            "$.Principal",
            "$.c.service({ m: $.c.func([$.c.service({ m: $.c.func([$.c.nat], [], \"update\") })], [], \"update\") })",
        ),
    ];
    for (kind, (alias, builder)) in KINDS.into_iter().zip(expected) {
        let contract = composite_chain(kind, 2)
            .build()
            .expect("a shallow chain builds");
        let module = generate_module(&contract, &TsNames::new(), &TsOptions::default())
            .expect("a shallow chain generates");
        assert_eq!(
            module.module,
            format!(
                "// Generated by candid-core-ts from a candid-core Contract. Do not edit.\n\
                 import * as $ from \"@candid-core/schema\";\n\
                 \n\
                 type $D = {alias};\n\
                 const $D: $.Schema<$D> = $.c.rec(() => {builder});\n\
                 export {{ $D as D }};\n"
            ),
            "{kind:?}"
        );
        assert_eq!(module.module, composite_chain_module(kind, 2), "{kind:?}");
    }
}

/// A deep undeclared chain of each remaining composite kind — record field,
/// variant arm, tuple element, func argument and service method — at default
/// limits. Together with the opt chains above, a recursive call reintroduced
/// in any frame of the walk turns a test red.
#[test]
fn every_composite_kind_nests_on_a_small_stack() {
    in_child_process("every_composite_kind_nests_on_a_small_stack", || {
        for kind in KINDS {
            let depth = kind.depth();
            let contract = composite_chain(kind, depth)
                .build()
                .unwrap_or_else(|refusal| panic!("{kind:?}: default limits accept: {refusal:?}"));
            let module = generate_small(contract)
                .unwrap_or_else(|error| panic!("{kind:?}: the chain generates: {error}"));
            assert!(module.omitted.is_empty(), "{kind:?}: {:?}", module.omitted);
            assert!(
                module.module == composite_chain_module(kind, depth),
                "{kind:?}: the module differs from the formula"
            );
        }
    });
}

/// Candid's field and method name hash.
fn name_hash(name: &str) -> u32 {
    name.bytes().fold(0u32, |hash, byte| {
        hash.wrapping_mul(223).wrapping_add(byte.into())
    })
}

/// Build a draft and re-read it, as a Contract from a registry or an agent
/// arrives.
fn reread(types: Vec<TypeNode>, declarations: Vec<Declaration>, actor: Option<Actor>) -> Contract {
    let contract = ContractDraft::new(types, declarations, actor)
        .build()
        .expect("Contract validation accepts every cycle");
    Contract::from_json(&serde_json::to_string(&contract).expect("the Contract serializes"))
        .expect("the document is a valid canonical Contract")
}

/// How a shape's cycle is reached.
#[derive(Clone, Copy)]
enum Entry {
    /// From a declared `D = variant { 2 : <member 0> }`.
    Declaration,
    /// Only from the actor: `service { call : <member 0> }`, member 0 a
    /// `func`.
    Actor,
}

/// A cycle among `members[..cycle]` (draft indices `0..`), possibly with
/// further non-cycle nodes after them, reached from `entry`.
struct Shape {
    name: &'static str,
    members: fn() -> Vec<TypeNode>,
    cycle: TypeRef,
    entry: Entry,
}

/// The shape's Contract, with the members at the draft indices in `declare`
/// declared as `N{index}`.
fn shape_contract(shape: &Shape, declare: &[TypeRef]) -> Contract {
    let mut types = (shape.members)();
    let entry = TypeRef::try_from(types.len()).expect("the shape fits a TypeRef");
    let mut declarations = Vec::new();
    let mut actor = None;
    match shape.entry {
        Entry::Declaration => {
            types.push(TypeNode::Variant {
                fields: vec![Field { id: 2, ty: 0 }],
            });
            declarations.push(Declaration {
                name: "D".to_string(),
                ty: entry,
            });
        }
        Entry::Actor => {
            types.push(TypeNode::Service {
                methods: vec![method("call", 0)],
            });
            actor = Some(Actor::Service { service: entry });
        }
    }
    for &index in declare {
        declarations.push(Declaration {
            name: format!("N{index}"),
            ty: index,
        });
    }
    reread(types, declarations, actor)
}

/// Where member 0 landed in the canonical arena: the node the entry
/// references, which is where the search enters the cycle, and so the node
/// whose incoming edge closes it.
fn entered(contract: &Contract) -> TypeRef {
    if let Some(declaration) = contract.declarations().iter().find(|d| d.name == "D") {
        match &contract.types()[declaration.ty as usize] {
            TypeNode::Variant { fields } => fields[0].ty,
            other => panic!("D is the entry variant: {other:?}"),
        }
    } else {
        match contract.actor() {
            Some(Actor::Service { service }) => match &contract.types()[*service as usize] {
                TypeNode::Service { methods } => methods[0].function,
                other => panic!("the actor is the entry service: {other:?}"),
            },
            other => panic!("the shape has an entry: {other:?}"),
        }
    }
}

fn method(name: &str, function: TypeRef) -> ServiceMethod {
    ServiceMethod {
        name: name.to_string(),
        id: name_hash(name),
        function,
    }
}

fn func(args: Vec<TypeRef>) -> TypeNode {
    TypeNode::Func {
        args,
        results: Vec::new(),
        mode: MethodMode::Update,
    }
}

/// Every edge kind the renderer follows, each on an undeclared cycle.
const SHAPES: &[Shape] = &[
    // `record { 1 : opt <the record> }`.
    Shape {
        name: "record and opt",
        members: || {
            vec![
                TypeNode::Record {
                    fields: vec![Field { id: 1, ty: 1 }],
                },
                TypeNode::Opt { inner: 0 },
            ]
        },
        cycle: 2,
        entry: Entry::Declaration,
    },
    // `record -> opt -> vec -> record`.
    Shape {
        name: "record, opt and vec",
        members: || {
            vec![
                TypeNode::Record {
                    fields: vec![Field { id: 1, ty: 1 }],
                },
                TypeNode::Opt { inner: 2 },
                TypeNode::Vec { inner: 0 },
            ]
        },
        cycle: 3,
        entry: Entry::Declaration,
    },
    // `variant { 1 : opt <the variant> }`.
    Shape {
        name: "variant arm",
        members: || {
            vec![
                TypeNode::Variant {
                    fields: vec![Field { id: 1, ty: 1 }],
                },
                TypeNode::Opt { inner: 0 },
            ]
        },
        cycle: 2,
        entry: Entry::Declaration,
    },
    // `record { 1 : func (<the record>) -> () }`: the builder renders the
    // func's arguments.
    Shape {
        name: "func argument",
        members: || {
            vec![
                TypeNode::Record {
                    fields: vec![Field { id: 1, ty: 1 }],
                },
                func(vec![0]),
            ]
        },
        cycle: 2,
        entry: Entry::Declaration,
    },
    // `service { m : func (opt <the service>) -> () }`.
    Shape {
        name: "service method",
        members: || {
            vec![
                TypeNode::Service {
                    methods: vec![method("m", 1)],
                },
                func(vec![2]),
                TypeNode::Opt { inner: 0 },
            ]
        },
        cycle: 3,
        entry: Entry::Declaration,
    },
    // `record { 0 : opt <the tuple>; 1 : nat }`.
    Shape {
        name: "tuple element",
        members: || {
            vec![
                TypeNode::Record {
                    fields: vec![Field { id: 0, ty: 1 }, Field { id: 1, ty: 2 }],
                },
                TypeNode::Opt { inner: 0 },
                TypeNode::Primitive {
                    primitive: PrimitiveType::Nat,
                },
            ]
        },
        cycle: 2,
        entry: Entry::Declaration,
    },
    // `func (service { m : <the func> }) -> ()`, reached only from the
    // actor's `call` method: the signatures and the actor's builder walk it.
    Shape {
        name: "func and service under the actor",
        members: || {
            vec![
                func(vec![1]),
                TypeNode::Service {
                    methods: vec![method("m", 0)],
                },
            ]
        },
        cycle: 2,
        entry: Entry::Actor,
    },
];

#[test]
fn cycles_through_no_declaration_are_refused() {
    in_child_process("cycles_through_no_declaration_are_refused", || {
        let contract =
            Contract::from_json(UNDECLARED_SELF_CYCLE).expect("accepted at default limits");
        assert_eq!(UNDECLARED_SELF_CYCLE.len(), 464);
        let refusal = generate_small(contract).expect_err("an undeclared cycle refuses");
        assert_eq!(refusal, TsGenError::UndeclaredCycle { reference: 1 });
        assert_eq!(
            refusal.to_string(),
            "type node 1 lies on a cycle that passes through no declaration; a \
             TypeScript type alias cannot spell an anonymous cycle (issue #218)"
        );

        for shape in SHAPES {
            let contract = shape_contract(shape, &[]);
            let first = entered(&contract);
            let refusal = generate_small(contract).expect_err("an undeclared cycle refuses");
            assert_eq!(
                refusal,
                TsGenError::UndeclaredCycle { reference: first },
                "{}",
                shape.name
            );
            assert!(
                refusal
                    .to_string()
                    .starts_with(&format!("type node {first} lies on a cycle")),
                "{}: the message names the node: {refusal}",
                shape.name
            );
        }
    });
}

#[test]
fn the_same_cycle_with_one_member_declared_generates() {
    in_child_process("the_same_cycle_with_one_member_declared_generates", || {
        for shape in SHAPES {
            for member in 0..shape.cycle {
                let module =
                    generate_small(shape_contract(shape, &[member])).unwrap_or_else(|error| {
                        panic!(
                            "{}: declaring member {member} must generate: {error}",
                            shape.name
                        )
                    });
                assert!(
                    module.omitted.is_empty(),
                    "{}: {:?}",
                    shape.name,
                    module.omitted
                );
            }
        }
        // One text in full: the cycle written through the declared record.
        let module = generate_small(shape_contract(&SHAPES[1], &[0])).expect("generates");
        assert_eq!(
            module.module,
            "// Generated by candid-core-ts from a candid-core Contract. Do not edit.\n\
             import * as $ from \"@candid-core/schema\";\n\
             \n\
             type $D = { tag: \"_2_\"; value: $N0 };\n\
             const $D: $.Schema<$D> = $.c.rec(() => $.c.variant({ _2_: $N0 }));\n\
             export { $D as D };\n\
             \n\
             type $N0 = { _1_: Array<$N0> | null };\n\
             const $N0: $.Schema<$N0> = $.c.rec(() => $.c.record({ _1_: $.c.opt($.c.vec($N0)) }));\n\
             export { $N0 as N0 };\n"
        );
    });
}

/// The rule covers only what the module renders, so a cycle through no
/// declaration that the renderer never walks does not refuse, and these
/// Contracts generate exactly what they generated before issue #218: one in
/// a class actor's init args, which the module does not render (issue #104),
/// one reachable only from a declaration the module omits (issue #189), and
/// one reachable only from an actor method the module omits next to one it
/// keeps.
#[test]
fn cycles_the_module_never_renders_do_not_refuse() {
    in_child_process("cycles_the_module_never_renders_do_not_refuse", || {
        // `service : (opt <self>) -> {}`, the opt a cycle through no
        // declaration.
        let contract = reread(
            vec![
                TypeNode::Class {
                    init: vec![1],
                    service: 2,
                },
                TypeNode::Opt { inner: 1 },
                TypeNode::Service {
                    methods: Vec::new(),
                },
            ],
            Vec::new(),
            Some(Actor::Class { class: 0 }),
        );
        let module = generate_small(contract).expect("init args are never rendered");
        assert!(module.omitted.is_empty());
        assert_eq!(CLASS_INIT_CYCLE_MODULE.len(), 364);
        assert_eq!(module.module, CLASS_INIT_CYCLE_MODULE);

        // `type D = record { 5 : <opt self> }`, field 5 labelled `_3_`, a
        // reserved name, so `D` is omitted and nothing renders the cycle.
        let contract = reread(
            vec![
                TypeNode::Record {
                    fields: vec![Field { id: 5, ty: 1 }],
                },
                TypeNode::Opt { inner: 1 },
            ],
            vec![Declaration {
                name: "D".to_string(),
                ty: 0,
            }],
            None,
        );
        let record = contract.declarations()[0].ty;
        let mut names = TsNames::new();
        names.insert(record, 5, "_3_");
        let module =
            on_small_stack(move || generate_module(&contract, &names, &TsOptions::default()))
                .expect("an omitted declaration is never rendered");
        assert_eq!(
            module
                .omitted
                .iter()
                .map(ToString::to_string)
                .collect::<Vec<_>>(),
            ["type D (reserved_field_name)"]
        );
        assert_eq!(module.module, OMITTED_CYCLE_MODULE);

        // `service : { a : () -> (); m : (R, C) -> () }` with `R = record {
        // 5 : nat }`, field 5 labelled `_3_`, so `m` is omitted, and `C = opt
        // C` undeclared. `a` survives, so the service is tainted and the
        // module renders its surviving methods one by one: neither that walk
        // nor the signatures reach `C`.
        let contract = reread(
            vec![
                TypeNode::Primitive {
                    primitive: PrimitiveType::Nat,
                },
                TypeNode::Record {
                    fields: vec![Field { id: 5, ty: 0 }],
                },
                TypeNode::Opt { inner: 2 },
                func(vec![1, 2]),
                func(Vec::new()),
                TypeNode::Service {
                    methods: vec![method("a", 4), method("m", 3)],
                },
            ],
            Vec::new(),
            Some(Actor::Service { service: 5 }),
        );
        let record = match contract.actor() {
            Some(Actor::Service { service }) => match &contract.types()[*service as usize] {
                TypeNode::Service { methods } => {
                    let m = methods
                        .iter()
                        .find(|method| method.name == "m")
                        .expect("the service has `m`");
                    match &contract.types()[m.function as usize] {
                        TypeNode::Func { args, .. } => args[0],
                        other => panic!("`m` is a func: {other:?}"),
                    }
                }
                other => panic!("the actor is a service: {other:?}"),
            },
            other => panic!("the Contract has a service actor: {other:?}"),
        };
        let mut names = TsNames::new();
        names.insert(record, 5, "_3_");
        let module =
            on_small_stack(move || generate_module(&contract, &names, &TsOptions::default()))
                .expect("an omitted method is never rendered");
        assert_eq!(
            module
                .omitted
                .iter()
                .map(ToString::to_string)
                .collect::<Vec<_>>(),
            ["method m (reserved_field_name)"]
        );
        assert_eq!(module.module, OMITTED_METHOD_CYCLE_MODULE);
    });
}

/// What `cycles_the_module_never_renders_do_not_refuse`'s class actor
/// generated before issue #218 (364 bytes).
const CLASS_INIT_CYCLE_MODULE: &str = "\
// Generated by candid-core-ts from a candid-core Contract. Do not edit.
import * as $ from \"@candid-core/schema\";

const $actor: $.Schema<$.Principal> = $.c.rec(() => $.c.service({  }));
type $Actor = {

};
export { $actor as actor, type $Actor as Actor };
// Note: the actor is a service class; init args are install-time metadata not exposed here (issue #104).
";
/// What `cycles_the_module_never_renders_do_not_refuse`'s omitted
/// declaration generated before issue #218.
const OMITTED_CYCLE_MODULE: &str = "\
// Generated by candid-core-ts from a candid-core Contract. Do not edit.
// Omitted: type D (reserved_field_name)
";
/// What `cycles_the_module_never_renders_do_not_refuse`'s service with an
/// omitted method generated before issue #218.
const OMITTED_METHOD_CYCLE_MODULE: &str = "\
// Generated by candid-core-ts from a candid-core Contract. Do not edit.
// Omitted: method m (reserved_field_name)
import * as $ from \"@candid-core/schema\";

const $actor: $.Schema<$.Principal> = $.c.rec(() => $.c.service({ a: $.c.func([], [], \"update\") }));
type $Actor = {
  a: () => Promise<void>;
};
export { $actor as actor, type $Actor as Actor };
";
