//! Issue #103's conformance gate, Rust half: the upstream `candid` crate is
//! the reference wire-format implementation, and this test holds both
//! directions of the differential.
//!
//! *Emit*: every vector case (a fixture declaration plus a textual Candid
//! value) is encoded with `candid` into `tests/goldens/wire/<fixture>.wire.json`
//! — hex bytes the TypeScript decoder must accept and interpret to the same
//! domain value (`ts/tests/codec.test.ts` holds the expected values).
//!
//! *Verify back*: the TypeScript encoder's own bytes are checked in as
//! `tests/goldens/wire/<fixture>.wire-ts.json` (regenerated by
//! `UPDATE_GOLDENS=1 npm test`); each is decoded here with `candid` and must
//! equal the case's value — the reference implementation validates our
//! encoder, not just the reverse.
//!
//! The type environment comes from `candid_parser` over the fixture `.did`
//! source directly — deliberately not through candid-core's compiler, so the
//! reference path shares no code with the model under test. Regenerate with
//! `UPDATE_GOLDENS=1 cargo test -p candid-core-ts --features compiler`.
#![cfg(feature = "compiler")]

use std::path::PathBuf;

use candid::types::value::IDLArgs;
use candid::TypeEnv;
use candid_parser::{check_prog, parse_idl_args, IDLProg};

struct Case {
    name: &'static str,
    declaration: &'static str,
    textual: &'static str,
}

const VECTORS: &[(&str, &[Case])] = &[
    (
        "primitives",
        &[
            Case {
                name: "null",
                declaration: "P00",
                textual: "(null)",
            },
            Case {
                name: "bool_true",
                declaration: "P01",
                textual: "(true)",
            },
            Case {
                name: "nat_big",
                declaration: "P02",
                textual: "(340282366920938463463374607431768211455)",
            },
            Case {
                name: "int_negative_big",
                declaration: "P03",
                textual: "(-170141183460469231731687303715884105728)",
            },
            Case {
                name: "nat8_max",
                declaration: "P04",
                textual: "(255)",
            },
            Case {
                name: "nat16",
                declaration: "P05",
                textual: "(65535)",
            },
            Case {
                name: "nat32",
                declaration: "P06",
                textual: "(4294967295)",
            },
            Case {
                name: "nat64_max",
                declaration: "P07",
                textual: "(18446744073709551615)",
            },
            Case {
                name: "int8_min",
                declaration: "P08",
                textual: "(-128)",
            },
            Case {
                name: "int16_min",
                declaration: "P09",
                textual: "(-32768)",
            },
            Case {
                name: "int32_min",
                declaration: "P10",
                textual: "(-2147483648)",
            },
            Case {
                name: "int64_min",
                declaration: "P11",
                textual: "(-9223372036854775808)",
            },
            Case {
                name: "float32",
                declaration: "P12",
                textual: "(1.5)",
            },
            Case {
                name: "float64_neg_zero",
                declaration: "P13",
                textual: "(-0.0)",
            },
            Case {
                name: "text_unicode",
                declaration: "P14",
                textual: "(\"héllo ☃\")",
            },
            Case {
                name: "reserved",
                declaration: "P15",
                textual: "(null)",
            },
            Case {
                name: "principal_management",
                declaration: "P17",
                textual: "(principal \"aaaaa-aa\")",
            },
            Case {
                name: "principal_anonymous",
                declaration: "P17",
                textual: "(principal \"2vxsx-fae\")",
            },
        ],
    ),
    (
        "collections",
        &[
            Case {
                name: "unit",
                declaration: "Unit",
                textual: "(record {})",
            },
            Case {
                name: "pair",
                declaration: "Pair",
                textual: "(record { 1; \"x\" })",
            },
            Case {
                name: "item",
                declaration: "Item",
                textual: "(record { id = 7; label = \"seven\"; payload = blob \"\\01\\02\" })",
            },
            Case {
                name: "maybe_item_none",
                declaration: "MaybeItem",
                textual: "(null)",
            },
            Case {
                name: "maybe_item_some",
                declaration: "MaybeItem",
                textual: "(opt record { id = 7; label = \"seven\"; payload = blob \"\\07\" })",
            },
            Case {
                name: "note_some",
                declaration: "Note",
                textual: "(opt \"n\")",
            },
            Case {
                name: "items",
                declaration: "Items",
                textual: "(vec { record { id = 1; label = \"a\"; payload = blob \"\" } })",
            },
            Case {
                name: "grid",
                declaration: "Grid",
                textual: "(vec { blob \"\\01\"; blob \"\" })",
            },
        ],
    ),
    (
        "variants",
        &[
            Case {
                name: "status_ok",
                declaration: "Status",
                textual: "(variant { ok })",
            },
            Case {
                name: "status_busy",
                declaration: "Status",
                textual: "(variant { busy = 3 })",
            },
            Case {
                name: "status_failed",
                declaration: "Status",
                textual: "(variant { failed = \"why\" })",
            },
            Case {
                name: "numbered_0",
                declaration: "Numbered",
                textual: "(variant { 0 })",
            },
            Case {
                name: "numbered_5",
                declaration: "Numbered",
                textual: "(variant { 5 = 4 })",
            },
            Case {
                name: "tree",
                declaration: "Tree",
                textual: "(variant { node = record { left = variant { leaf = 1 }; \
                          right = variant { leaf = 2 } } })",
            },
        ],
    ),
    (
        "recursion",
        &[
            Case {
                name: "list_empty",
                declaration: "List",
                textual: "(null)",
            },
            Case {
                name: "list_two",
                declaration: "List",
                textual: "(opt record { head = 1; tail = opt record { head = 2; tail = null } })",
            },
            Case {
                name: "even_two_hops",
                declaration: "Even",
                textual: "(record { next = opt record { next = null } })",
            },
        ],
    ),
    (
        "deferred",
        &[
            Case {
                name: "kept",
                declaration: "Kept",
                textual: "(record { value = 1 })",
            },
            Case {
                name: "callback_value",
                declaration: "Callback",
                textual: "(func \"aaaaa-aa\".\"go\")",
            },
            Case {
                name: "registry_value",
                declaration: "Registry",
                textual: "(service \"aaaaa-aa\")",
            },
        ],
    ),
    (
        "quoting",
        &[Case {
            name: "weird",
            declaration: "Weird",
            textual: "(record { \"has space\" = 1; \"naïve\" = \"x\"; \"quote\\\"mark\" = true })",
        }],
    ),
];

fn goldens_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("goldens")
        .join("wire")
}

fn fixture_env(fixture: &str) -> TypeEnv {
    let source = std::fs::read_to_string(
        PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("tests")
            .join("fixtures")
            .join(format!("{fixture}.did")),
    )
    .expect("fixture must be readable");
    let prog: IDLProg = source.parse().expect("fixture must parse as Candid");
    let mut env = TypeEnv::new();
    check_prog(&mut env, &prog).expect("fixture must type-check");
    env
}

fn encode_case(env: &TypeEnv, case: &Case) -> (IDLArgs, Vec<u8>) {
    let ty = env
        .find_type(case.declaration)
        .unwrap_or_else(|_| panic!("declaration {} must exist", case.declaration))
        .clone();
    let args: IDLArgs = parse_idl_args(case.textual).expect("textual value must parse");
    let types = [ty];
    let annotated = args
        .annotate_types(true, env, &types)
        .expect("value must type against the declaration");
    let bytes = annotated
        .to_bytes_with_types(env, &types)
        .expect("reference encoding must succeed");
    (annotated, bytes)
}

fn hex(bytes: &[u8]) -> String {
    bytes.iter().map(|byte| format!("{byte:02x}")).collect()
}

/// Emit (or verify) the reference vectors the TS decoder consumes.
#[test]
fn wire_vectors_match_reference_encoding() {
    for (fixture, cases) in VECTORS {
        let env = fixture_env(fixture);
        let mut entries = Vec::new();
        for case in *cases {
            let (_, bytes) = encode_case(&env, case);
            entries.push(serde_json::json!({
                "name": case.name,
                "declaration": case.declaration,
                "textual": case.textual,
                "hex": hex(&bytes),
            }));
        }
        let mut text = serde_json::to_string_pretty(&serde_json::Value::Array(entries))
            .expect("vectors must serialize");
        text.push('\n');
        let path = goldens_dir().join(format!("{fixture}.wire.json"));
        if std::env::var_os("UPDATE_GOLDENS").is_some() {
            std::fs::create_dir_all(goldens_dir()).expect("goldens dir must be creatable");
            std::fs::write(&path, &text).expect("golden must be writable");
            continue;
        }
        let golden = std::fs::read_to_string(&path)
            .unwrap_or_else(|_| panic!("missing golden {path:?}; run with UPDATE_GOLDENS=1"));
        assert_eq!(
            text, golden,
            "reference vectors for `{fixture}` diverged; regenerate deliberately \
             with UPDATE_GOLDENS=1 and review the diff"
        );
    }
}

/// The reverse differential: the TypeScript encoder's checked-in bytes must
/// decode to each case's value under the reference implementation. The
/// TS-side goldens are written by `UPDATE_GOLDENS=1 npm test`, so a missing
/// file fails loudly rather than skipping the gate.
#[test]
fn ts_encodings_decode_under_the_reference_implementation() {
    for (fixture, cases) in VECTORS {
        let env = fixture_env(fixture);
        let path = goldens_dir().join(format!("{fixture}.wire-ts.json"));
        let text = std::fs::read_to_string(&path).unwrap_or_else(|_| {
            panic!("missing TS-encoder golden {path:?}; run UPDATE_GOLDENS=1 npm test")
        });
        let entries: serde_json::Value =
            serde_json::from_str(&text).expect("TS golden must be JSON");
        let entries = entries.as_array().expect("TS golden must be an array");
        assert_eq!(
            entries.len(),
            cases.len(),
            "TS golden for `{fixture}` must carry every vector case"
        );
        for (entry, case) in entries.iter().zip(*cases) {
            assert_eq!(
                entry["name"].as_str(),
                Some(case.name),
                "TS golden order must match the case list"
            );
            let ts_hex = entry["hex"].as_str().expect("hex must be a string");
            let bytes: Vec<u8> = (0..ts_hex.len())
                .step_by(2)
                .map(|i| u8::from_str_radix(&ts_hex[i..i + 2], 16).expect("valid hex"))
                .collect();
            let ty = env
                .find_type(case.declaration)
                .expect("declaration")
                .clone();
            let types = [ty];
            let decoded =
                IDLArgs::from_bytes_with_types(&bytes, &env, &types).unwrap_or_else(|error| {
                    panic!(
                        "reference decode of TS bytes failed for {fixture}/{}: {error}",
                        case.name
                    )
                });
            let (expected, _) = encode_case(&env, case);
            assert_eq!(
                decoded.args, expected.args,
                "TS encoding of {fixture}/{} decodes to a different value",
                case.name
            );
        }
    }
}
