// Generated by candid-core-ts from a candid-core Contract. Do not edit.
// Regenerated by `npm run generate`; the schema-core import specifier is
// rewritten to the prototype's re-export until the npm package exists.
import { c, type Schema } from "../../src/schema.ts";
import type { Principal } from "@icp-sdk/core/principal";

export type NewNote = { title: string; body: string; tags: Array<string>; attachment: Uint8Array | null };
export const NewNote: Schema<NewNote> = c.rec(() => c.record({ title: c.text, body: c.text, tags: c.vec(c.text), attachment: c.opt(c.blob()) }));

export type Note = { id: NoteId; status: NoteStatus; title: string; owner: Principal; body: string; tags: Array<string>; created_at_ns: NoteId; attachment: Uint8Array | null };
export const Note: Schema<Note> = c.rec(() => c.record({ id: NoteId, status: NoteStatus, title: c.text, owner: c.principal, body: c.text, tags: c.vec(c.text), created_at_ns: NoteId, attachment: c.opt(c.blob()) }));

export type NoteId = bigint;
export const NoteId: Schema<NoteId> = c.rec(() => c.nat64);

export type NoteStatus = { tag: "published"; value: { at_ns: NoteId } } | { tag: "draft" } | { tag: "archived" };
export const NoteStatus: Schema<NoteStatus> = c.rec(() => c.variant({ published: c.record({ at_ns: NoteId }), draft: c.null, archived: c.null }));

export type PublishResult = { tag: "ok"; value: Note } | { tag: "not_found" } | { tag: "already_published" };
export const PublishResult: Schema<PublishResult> = c.rec(() => c.variant({ ok: Note, not_found: c.null, already_published: c.null }));
