// Regenerate example/notes/schemas.ts from example/notes/notes.did through
// the real generator: candid-core compiles the .did into a canonical
// Contract, candid-core-ts emits the schema module, and this script rewrites
// the `@candid-core/schema` placeholder specifier to the prototype's
// re-export (the npm package behind that specifier does not exist yet —
// issue #106). The integration suite re-runs this pipeline and asserts the
// checked-in file is byte-identical, so a drifted schemas.ts fails closed.
import { spawnSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const repoRoot = fileURLToPath(new URL("../../..", import.meta.url));
const didPath = fileURLToPath(
  new URL("../example/notes/notes.did", import.meta.url),
);
const outPath = fileURLToPath(
  new URL("../example/notes/schemas.ts", import.meta.url),
);

export function generateSchemas(): string {
  const result = spawnSync(
    "cargo",
    [
      "run",
      "--quiet",
      "--locked",
      "-p",
      "candid-core-ts",
      "--features",
      "compiler",
      "--example",
      "generate",
      "--",
      didPath,
    ],
    { cwd: repoRoot, encoding: "utf-8" },
  );
  if (result.error !== undefined) {
    throw new Error(`cargo could not be spawned: ${String(result.error)}`);
  }
  if (result.status !== 0) {
    throw new Error(`generation failed:\n${result.stderr}`);
  }
  const generated = result.stdout;
  const marker = 'from "@candid-core/schema";';
  const occurrences = generated.split(marker).length - 1;
  if (occurrences !== 1) {
    throw new Error(
      `expected exactly one schema-core import, found ${occurrences}`,
    );
  }
  const lines = generated
    .replace(marker, 'from "../../src/schema.ts";')
    .split("\n");
  lines.splice(
    1,
    0,
    "// Regenerated by `npm run generate`; the schema-core import specifier is",
    "// rewritten to the prototype's re-export until the npm package exists.",
  );
  return lines.join("\n");
}

if (process.argv[1] !== undefined && import.meta.url.endsWith("generate.ts")) {
  const isDirect = fileURLToPath(import.meta.url) === process.argv[1];
  if (isDirect) {
    writeFileSync(outPath, generateSchemas());
    process.stdout.write(`wrote ${outPath}\n`);
  }
}
