// Generated by candid-core-ts from a candid-core Contract. Do not edit.
import * as $ from "@candid-core/schema";

type $AliasArms = { tag: "tagged" } | { tag: "plain" };
const $AliasArms: $.Schema<$AliasArms> = $.c.rec(() => $.c.variant({ tagged: $NullAlias, plain: $NullAlias }));
export { $AliasArms as AliasArms };

type $EmptyOptArm = { tag: "a"; value: never | null } | { tag: "b"; value: bigint };
const $EmptyOptArm: $.Schema<$EmptyOptArm> = $.c.rec(() => $.c.variant({ a: $.c.opt($.c.empty), b: $.c.nat }));
export { $EmptyOptArm as EmptyOptArm };

type $EmptyVariant = { tag: "a"; value: never } | { tag: "b"; value: bigint };
const $EmptyVariant: $.Schema<$EmptyVariant> = $.c.rec(() => $.c.variant({ a: $.c.empty, b: $.c.nat }));
export { $EmptyVariant as EmptyVariant };

type $NullAlias = null;
const $NullAlias: $.Schema<$NullAlias> = $.c.rec(() => $.c.null);
export { $NullAlias as NullAlias };
