// Generated by candid-core-ts from a candid-core Contract. Do not edit.
import { c, type Schema } from "@candid-core/schema";

export type AliasArms = { tag: "tagged" } | { tag: "plain" };
export const AliasArms: Schema<AliasArms> = c.rec(() => c.variant({ tagged: NullAlias, plain: NullAlias }));

export type EmptyOptArm = { tag: "a"; value: never | null } | { tag: "b"; value: bigint };
export const EmptyOptArm: Schema<EmptyOptArm> = c.rec(() => c.variant({ a: c.opt(c.empty), b: c.nat }));

export type EmptyVariant = { tag: "a"; value: never } | { tag: "b"; value: bigint };
export const EmptyVariant: Schema<EmptyVariant> = c.rec(() => c.variant({ a: c.empty, b: c.nat }));

export type NullAlias = null;
export const NullAlias: Schema<NullAlias> = c.rec(() => c.null);
