// Generated by candid-core-ts from a candid-core Contract. Do not edit.

export type DoubleOpt = [] | [[] | [bigint]];

export type Grid = Array<Array<number>>;

export type Item = { id: number; label: string; payload: Array<number> };

export type Items = Array<Item>;

export type MaybeItem = [] | [Item];

export type Pair = [bigint, string];

export type Unit = Record<string, never>;
