// Generated by candid-core-ts from a candid-core Contract. Do not edit.
import { c, type Schema } from "@candid-core/schema";

export type Grid = Array<Uint8Array>;
export const Grid: Schema<Grid> = c.rec(() => c.vec(c.blob()));

export type Item = { id: number; label: string; payload: Uint8Array };
export const Item: Schema<Item> = c.rec(() => c.record({ id: c.nat32, label: c.text, payload: c.blob() }));

export type Items = Array<Item>;
export const Items: Schema<Items> = c.rec(() => c.vec(Item));

export type MaybeItem = Item | null;
export const MaybeItem: Schema<MaybeItem> = c.rec(() => c.opt(Item));

export type Note = string | null;
export const Note: Schema<Note> = c.rec(() => c.opt(c.text));

export type Pair = [bigint, string];
export const Pair: Schema<Pair> = c.rec(() => c.tuple([c.nat, c.text]));

export type Unit = Record<string, never>;
export const Unit: Schema<Unit> = c.rec(() => c.unit());
