// Generated by candid-core-ts from a candid-core Contract. Do not edit.
// Deferred: `Callback` is a `func` declaration; func/service/class arrive in a later slice (issue #38).
// Deferred: `Registry` is a `service` declaration; func/service/class arrive in a later slice (issue #38).
// Deferred: the actor interface; func/service/class arrive in a later slice (issue #38).

export type Kept = { value: bigint };
