// Generated by candid-core-ts from a candid-core Contract. Do not edit.
import { c, type Schema } from "@candid-core/schema";
import type { Principal } from "@icp-sdk/core/principal";

export type Callback = { principal: Principal; method: string };
export const Callback: Schema<Callback> = c.rec(() => c.func([c.nat], [c.text], "query"));

export type Kept = { value: bigint };
export const Kept: Schema<Kept> = c.rec(() => c.record({ value: c.nat }));

export type Registry = Principal;
export const Registry: Schema<Registry> = c.rec(() => c.service({ register: c.func([c.text], [c.nat], "update") }));

export const actor: Schema<Principal> = c.rec(() => c.service({ ping: c.func([], [], "update") }));
export type Actor = {
  ping: () => Promise<void>;
};
