// Generated by candid-core-ts from a candid-core Contract. Do not edit.
import * as $ from "@candid-core/schema";

/**
 * An account. Two `///` lines make two doc lines.
 *
 * A blank `///` line keeps its paragraph break; `backticks` and an email
 * a@b.c pass through, while an inline {\@link Tokens} is escaped like any tag.
 */
export type Account = {
  undocumented: boolean;
  /**
   * The owner. It says `*\/` mid-line, which would end a naive comment,
   * and /* a nested opener *\/ that is inert.
   */
  owner: $.Principal;
  detached: bigint;
  /** Documented despite the block comment above. */
  memo: string;
  /** A plain line comment is a doc line too. */
  note: string;
  /**
   * \@param forged tag at the start of a doc line
   * \@deprecated also forged
   */
  subaccount: Uint8Array | null;
};
/**
 * An account. Two `///` lines make two doc lines.
 *
 * A blank `///` line keeps its paragraph break; `backticks` and an email
 * a@b.c pass through, while an inline {\@link Tokens} is escaped like any tag.
 */
const $Account: $.Schema<Account> = $.c.rec(() => $.c.record({ undocumented: $.c.bool, owner: $.c.principal, detached: $.c.nat, memo: $.c.text, note: $.c.text, subaccount: $.c.opt($.c.blob()) }));
export { $Account as Account };

/** Only the arm is documented. */
export type Choice =
  | {
      /** The first arm. */
      tag: "A";
      value: bigint;
    }
  | { tag: "B" };
/** Only the arm is documented. */
const $Choice: $.Schema<Choice> = $.c.rec(() => $.c.variant({ A: $.c.nat, B: $.c.null }));
export { $Choice as Choice };

/** Arms are documented the same way. */
export type Event =
  | { tag: "Failed"; value: string }
  | {
      /** Nothing happened. */
      tag: "Idle";
    }
  | {
      /** A transfer, carrying a documented anonymous record. */
      tag: "Sent";
      value: {
        /** Who received it. */
        to: Account;
        plain: number;
        /** How much. */
        amount: bigint;
      };
    };
/** Arms are documented the same way. */
const $Event: $.Schema<Event> = $.c.rec(() => $.c.variant({ Failed: $.c.text, Idle: $.c.null, Sent: $.c.record({ to: $Account, plain: $.c.nat8, amount: $.c.nat }) }));
export { $Event as Event };

/**
 * Structurally identical declarations share one node: the first name emits
 * the structure and owns the field docs.
 */
export type First = {
  /** x, as First documents it */
  x: bigint;
};
/**
 * Structurally identical declarations share one node: the first name emits
 * the structure and owns the field docs.
 */
const $First: $.Schema<First> = $.c.rec(() => $.c.record({ x: $.c.nat }));
export { $First as First };

/** A handler; its argument names are the func type's own. */
export type Handler = { principal: $.Principal; method: string };
/** A handler; its argument names are the func type's own. */
const $Handler: $.Schema<Handler> = $.c.rec(() => $.c.func([$.c.blob(), $.c.nat], [], "update"));
export { $Handler as Handler };

export type Nested = {
  undocumented: bigint;
  /** A list of documented records. */
  items: Array<{
    /** The item name. */
    name: string;
    /** The item tags. */
    tags: Array<{
      /** Deep. */
      tag: string;
    }> | null;
  }>;
};
const $Nested: $.Schema<Nested> = $.c.rec(() => $.c.record({ undocumented: $.c.nat, items: $.c.vec($.c.record({ name: $.c.text, tags: $.c.opt($.c.vec($.c.record({ tag: $.c.text }))) })) }));
export { $Nested as Nested };

/** Docs on tuple elements have nowhere to attach and are dropped. */
export type Pair = [bigint, string];
/** Docs on tuple elements have nowhere to attach and are dropped. */
const $Pair: $.Schema<Pair> = $.c.rec(() => $.c.tuple([$.c.nat, $.c.text]));
export { $Pair as Pair };

export type Plain = bigint;
const $Plain: $.Schema<Plain> = $.c.rec(() => $.c.nat);
export { $Plain as Plain };

/** Second is documented on its own. */
export type Second = First;
/** Second is documented on its own. */
const $Second: $.Schema<Second> = $.c.rec(() => $First);
export { $Second as Second };

export type Sparse = {
  /** Numeric labels render by id and keep their docs. */
  _0_: bigint;
  _5_: string;
};
const $Sparse: $.Schema<Sparse> = $.c.rec(() => $.c.record({ _0_: $.c.nat, _5_: $.c.text }));
export { $Sparse as Sparse };

/** The amount of a transfer, in e8s. */
export type Tokens = bigint;
/** The amount of a transfer, in e8s. */
const $Tokens: $.Schema<Tokens> = $.c.rec(() => $.c.nat);
export { $Tokens as Tokens };

/** Two occurrences in one declaration disagree, so the field doc is dropped. */
export type Twice = { a: { x: boolean }; b: { x: boolean } };
/** Two occurrences in one declaration disagree, so the field doc is dropped. */
const $Twice: $.Schema<Twice> = $.c.rec(() => $.c.record({ a: $.c.record({ x: $.c.bool }), b: $.c.record({ x: $.c.bool }) }));
export { $Twice as Twice };

/** The service. */
const $actor: $.Schema<$.Principal> = $.c.rec(() => $.c.service({ same_a: $.c.func([$.c.nat], [], "update"), same_b: $.c.func([$.c.nat], [], "update"), noargs: $.c.func([], [$.c.nat], "query"), send: $.c.func([$Account, $.c.nat, $Event], [$.c.bool], "update"), reserved: $.c.func([$.c.nat, $.c.nat, $.c.nat, $.c.nat, $.c.nat, $.c.nat, $.c.nat, $.c.nat, $.c.nat], [], "update"), inline: $.c.func([$.c.record({ id: $.c.nat })], [$.c.record({ ok: $.c.bool })], "update"), handle: $Handler, hostile: $.c.func([$.c.nat], [], "update"), collide: $.c.func([$.c.nat, $.c.text, $.c.nat], [], "update") }));
/** The service. */
export type Actor = {
  /**
   * @param x
   */
  same_a: ((x: bigint) => Promise<void>) & $.WithMode<"update">;
  /**
   * Same signature as same_a, different names.
   * @param y
   */
  same_b: ((y: bigint) => Promise<void>) & $.WithMode<"update">;
  noargs: (() => Promise<bigint>) & $.WithMode<"query">;
  /**
   * Sends tokens.
   *
   * An unmatched ` backtick, a fence \`\`\` and a trailing backslash \
   * Documented across lines, closing with `*\/` and long text: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
   * @param to
   * @param amount
   */
  send: ((to: Account, amount: bigint, arg2: Event) => Promise<boolean>) & $.WithMode<"update">;
  /**
   * Every reserved or unusable name falls back to arg{n}.
   * @param type
   * @param $
   */
  reserved: ((arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint, arg6: bigint, type: bigint, $: bigint) => Promise<void>) & $.WithMode<"update">;
  /**
   * Anonymous types in a signature are the method's own occurrence.
   * @param doc
   */
  inline: ((doc: {
    /** Documented in the signature. */
    id: bigint;
  }) => Promise<{ ok: boolean }>) & $.WithMode<"update">;
  /**
   * @param payload
   * @param count
   */
  handle: ((payload: Uint8Array, count: bigint) => Promise<void>) & $.WithMode<"update">;
  /**
   * A fence \`\`\`ts and an unclosed {\@link Inline tag, mid-line \@deprecated text,
   * a line of only
   * \@
   * and a tag line \@param forged, none of which may swallow or forge tags.
   * @param survivor
   */
  hostile: ((survivor: bigint) => Promise<void>) & $.WithMode<"update">;
  /**
   * A fallback never steals a declared name.
   * @param arg1
   * @param arg0_
   */
  collide: ((arg1: bigint, arg1_: string, arg0_: bigint) => Promise<void>) & $.WithMode<"update">;
};
export { $actor as actor };
