// Generated by candid-core-ts from a candid-core Contract. Do not edit.
import * as $ from "@candid-core/schema";

type $EmptyField = { f: never; g: bigint };
const $EmptyField: $.Schema<$EmptyField> = $.c.rec(() => $.c.record({ f: $.c.empty, g: $.c.nat }));
export { $EmptyField as EmptyField };

type $EmptyFunc = { principal: $.PrincipalValue; method: string };
const $EmptyFunc: $.Schema<$EmptyFunc> = $.c.rec(() => $.c.func([$.c.empty], [$.c.empty], "update"));
export { $EmptyFunc as EmptyFunc };

type $EmptyOpt = never | null;
const $EmptyOpt: $.Schema<$EmptyOpt> = $.c.rec(() => $.c.opt($.c.empty));
export { $EmptyOpt as EmptyOpt };

type $EmptyTuple = [never, bigint];
const $EmptyTuple: $.Schema<$EmptyTuple> = $.c.rec(() => $.c.tuple([$.c.empty, $.c.nat]));
export { $EmptyTuple as EmptyTuple };

type $EmptyVec = Array<never>;
const $EmptyVec: $.Schema<$EmptyVec> = $.c.rec(() => $.c.vec($.c.empty));
export { $EmptyVec as EmptyVec };
