// Generated by candid-core-ts from a candid-core Contract. Do not edit.
import { c, type Schema } from "@candid-core/schema";
import type { PrincipalValue } from "@candid-core/schema";

export type EmptyField = { f: never; g: bigint };
export const EmptyField: Schema<EmptyField> = c.rec(() => c.record({ f: c.empty, g: c.nat }));

export type EmptyFunc = { principal: PrincipalValue; method: string };
export const EmptyFunc: Schema<EmptyFunc> = c.rec(() => c.func([c.empty], [c.empty], "update"));

export type EmptyOpt = never | null;
export const EmptyOpt: Schema<EmptyOpt> = c.rec(() => c.opt(c.empty));

export type EmptyTuple = [never, bigint];
export const EmptyTuple: Schema<EmptyTuple> = c.rec(() => c.tuple([c.empty, c.nat]));

export type EmptyVec = Array<never>;
export const EmptyVec: Schema<EmptyVec> = c.rec(() => c.vec(c.empty));
