// Generated by candid-core-ts from a candid-core Contract. Do not edit.
import * as $ from "@candid-core/schema";

type $Account = { owner: $.Principal; subaccount: Uint8Array | null };
const $Account: $.Schema<$Account> = $.c.rec(() => $.c.record({ owner: $.c.principal, subaccount: $.c.opt($.c.blob()) }));
export { $Account as Account };

type $Anything = unknown;
const $Anything: $.Schema<$Anything> = $.c.rec(() => $.c.reserved);
export { $Anything as Anything };

type $BlockIndex = bigint;
const $BlockIndex: $.Schema<$BlockIndex> = $.c.rec(() => $.c.nat);
export { $BlockIndex as BlockIndex };

type $Byte = number;
const $Byte: $.Schema<$Byte> = $.c.rec(() => $.c.nat8);
export { $Byte as Byte };

type $Memo = bigint;
const $Memo: $.Schema<$Memo> = $.c.rec(() => $.c.nat64);
export { $Memo as Memo };

type $Millis = bigint;
const $Millis: $.Schema<$Millis> = $.c.rec(() => $.c.int64);
export { $Millis as Millis };

type $Never = never;
const $Never: $.Schema<$Never> = $.c.rec(() => $.c.empty);
export { $Never as Never };

type $Nothing = null;
const $Nothing: $.Schema<$Nothing> = $.c.rec(() => $.c.null);
export { $Nothing as Nothing };

type $Odd = { tag: "a" } | { tag: "b"; value: never } | { tag: "c"; value: unknown } | { tag: "d"; value: { some: null } | null } | { tag: "e"; value: never | null } | { tag: "f"; value: Array<unknown> };
const $Odd: $.Schema<$Odd> = $.c.rec(() => $.c.variant({ a: $.c.null, b: $.c.empty, c: $.c.reserved, d: $.c.opt($.c.null), e: $.c.opt($.c.empty), f: $.c.vec($.c.reserved) }));
export { $Odd as Odd };

type $Owned = { by: $.Principal; alias: $.Principal };
const $Owned: $.Schema<$Owned> = $.c.rec(() => $.c.record({ by: $.c.principal, alias: $.c.principal }));
export { $Owned as Owned };

type $Owner = $.Principal;
const $Owner: $.Schema<$Owner> = $.c.rec(() => $.c.principal);
export { $Owner as Owner };

type $R = { a: bigint; b: bigint };
const $R: $.Schema<$R> = $.c.rec(() => $.c.record({ a: $.c.nat64, b: $.c.nat64 }));
export { $R as R };

type $Raw = { one: number; raw: Uint8Array; maybe: Uint8Array | null; grid: Array<Uint8Array>; bytes: Uint8Array; plain: number };
const $Raw: $.Schema<$Raw> = $.c.rec(() => $.c.record({ one: $.c.nat8, raw: $.c.blob(), maybe: $.c.opt($.c.blob()), grid: $.c.vec($.c.blob()), bytes: $.c.blob(), plain: $.c.nat8 }));
export { $Raw as Raw };

type $Seconds = bigint;
const $Seconds: $.Schema<$Seconds> = $.c.rec(() => $.c.int64);
export { $Seconds as Seconds };

type $Timing = { raw: bigint; started: bigint; elapsed: bigint };
const $Timing: $.Schema<$Timing> = $.c.rec(() => $.c.record({ raw: $.c.int64, started: $.c.int64, elapsed: $.c.int64 }));
export { $Timing as Timing };

type $Tokens = bigint;
const $Tokens: $.Schema<$Tokens> = $.c.rec(() => $.c.nat);
export { $Tokens as Tokens };

type $TransferArg = { to: $Account; fee: bigint | null; amount: bigint };
const $TransferArg: $.Schema<$TransferArg> = $.c.rec(() => $.c.record({ to: $Account, fee: $.c.opt($.c.nat), amount: $.c.nat }));
export { $TransferArg as TransferArg };

type $TransferResult = { tag: "Ok"; value: bigint } | { tag: "Err"; value: string };
const $TransferResult: $.Schema<$TransferResult> = $.c.rec(() => $.c.variant({ Ok: $.c.nat, Err: $.c.text }));
export { $TransferResult as TransferResult };

const $actor: $.Schema<$.Principal> = $.c.rec(() => $.c.service({ put: $.c.func([$.c.blob(), $.c.blob(), $.c.nat8], [$.c.nat64, $.c.nat64], "update"), icrc1_balance_of: $.c.func([$Account], [$.c.nat], "query"), icrc1_transfer: $.c.func([$TransferArg], [$TransferResult], "update") }));
type $Actor = {
  put: (arg0: Uint8Array, arg1: Uint8Array, arg2: number) => Promise<[bigint, bigint]>;
  icrc1_balance_of: (arg0: $Account) => Promise<bigint>;
  icrc1_transfer: (arg0: $TransferArg) => Promise<$TransferResult>;
};
export { $actor as actor, type $Actor as Actor };
