// Generated by candid-core-ts from a candid-core Contract. Do not edit.
import { c, type Schema } from "@candid-core/schema";
import type { PrincipalValue } from "@candid-core/schema";

export type Account = { owner: PrincipalValue; subaccount: Uint8Array | null };
export const Account: Schema<Account> = c.rec(() => c.record({ owner: c.principal, subaccount: c.opt(c.blob()) }));

export type ArchiveCallback = { principal: PrincipalValue; method: string };
export const ArchiveCallback: Schema<ArchiveCallback> = c.rec(() => c.func([c.record({ start: c.nat, length: c.nat })], [TransactionRange], "query"));

export type ArchivedRange = { callback: ArchiveCallback; start: bigint; length: bigint };
export const ArchivedRange: Schema<ArchivedRange> = c.rec(() => c.record({ callback: ArchiveCallback, start: c.nat, length: c.nat }));

export type Tokens = { e8s: bigint };
export const Tokens: Schema<Tokens> = c.rec(() => c.record({ e8s: c.nat64 }));

export type Transaction = { to: Account | null; fee: Tokens | null; from: Account | null; memo: Uint8Array | null; timestamp: bigint; index: bigint; amount: Tokens };
export const Transaction: Schema<Transaction> = c.rec(() => c.record({ to: c.opt(Account), fee: c.opt(Tokens), from: c.opt(Account), memo: c.opt(c.blob()), timestamp: c.nat64, index: c.nat, amount: Tokens }));

export type TransactionRange = { transactions: Array<Transaction> };
export const TransactionRange: Schema<TransactionRange> = c.rec(() => c.record({ transactions: c.vec(Transaction) }));

export type TransactionsResponse = { log_length: bigint; transactions: Array<Transaction>; archived_transactions: Array<ArchivedRange> };
export const TransactionsResponse: Schema<TransactionsResponse> = c.rec(() => c.record({ log_length: c.nat, transactions: c.vec(Transaction), archived_transactions: c.vec(ArchivedRange) }));

export type TransferArg = { to: Account; fee: Tokens | null; memo: Uint8Array | null; from_subaccount: Uint8Array | null; created_at_time: bigint | null; amount: Tokens };
export const TransferArg: Schema<TransferArg> = c.rec(() => c.record({ to: Account, fee: c.opt(Tokens), memo: c.opt(c.blob()), from_subaccount: c.opt(c.blob()), created_at_time: c.opt(c.nat64), amount: Tokens }));

export type TransferError = { tag: "insufficient_funds"; value: { balance: Tokens } } | { tag: "created_in_future"; value: { ledger_time: bigint } } | { tag: "generic_error"; value: { message: string; error_code: bigint } } | { tag: "temporarily_unavailable" } | { tag: "too_old" } | { tag: "bad_fee"; value: { expected_fee: Tokens } } | { tag: "bad_burn"; value: { min_burn_amount: Tokens } } | { tag: "duplicate"; value: { duplicate_of: bigint } };
export const TransferError: Schema<TransferError> = c.rec(() => c.variant({ insufficient_funds: c.record({ balance: Tokens }), created_in_future: c.record({ ledger_time: c.nat64 }), generic_error: c.record({ message: c.text, error_code: c.nat }), temporarily_unavailable: c.null, too_old: c.null, bad_fee: c.record({ expected_fee: Tokens }), bad_burn: c.record({ min_burn_amount: Tokens }), duplicate: c.record({ duplicate_of: c.nat }) }));

export type TransferResult = { tag: "ok"; value: bigint } | { tag: "err"; value: TransferError };
export const TransferResult: Schema<TransferResult> = c.rec(() => c.variant({ ok: c.nat, err: TransferError }));

export const actor: Schema<PrincipalValue> = c.rec(() => c.service({ fee: c.func([], [Tokens], "query"), decimals: c.func([], [c.nat8], "query"), name: c.func([], [c.text], "query"), balance_of: c.func([Account], [Tokens], "query"), get_transactions: c.func([c.record({ start: c.nat, length: c.nat })], [TransactionsResponse], "query"), transfer: c.func([TransferArg], [TransferResult], "update"), total_supply: c.func([], [Tokens], "query"), symbol: c.func([], [c.text], "query") }));
export type Actor = {
  fee: () => Promise<Tokens>;
  decimals: () => Promise<number>;
  name: () => Promise<string>;
  balance_of: (arg0: Account) => Promise<Tokens>;
  get_transactions: (arg0: { start: bigint; length: bigint }) => Promise<TransactionsResponse>;
  transfer: (arg0: TransferArg) => Promise<TransferResult>;
  total_supply: () => Promise<Tokens>;
  symbol: () => Promise<string>;
};
