// Generated by candid-core-ts from a candid-core Contract. Do not edit.
import * as $ from "@candid-core/schema";

const $actor: $.Schema<$.Principal> = $.c.rec(() => $.c.service({  }));
export type Actor = {

};
export { $actor as actor };
