// Generated by candid-core-ts from a candid-core Contract. Do not edit.
import * as $ from "@candid-core/schema";

type $Notifier = { principal: $.Principal; method: string };
const $Notifier: $.Schema<$Notifier> = $.c.rec(() => $.c.func([$.c.text], [], "oneway"));
export { $Notifier as Notifier };

type $Reader = { principal: $.Principal; method: string };
const $Reader: $.Schema<$Reader> = $.c.rec(() => $.c.func([], [$.c.nat], "query"));
export { $Reader as Reader };

const $actor: $.Schema<$.Principal> = $.c.rec(() => $.c.service({ balance: $Reader, notify: $.c.func([$.c.nat], [], "oneway"), "quoted name": $Reader, read: $Reader, aggregate: $.c.func([$.c.text], [$.c.vec($.c.nat)], "composite_query"), announce: $Notifier, transfer: $.c.func([$.c.nat, $.c.text], [$.c.bool], "update") }));
type $Actor = {
  balance: (() => Promise<bigint>) & $.WithMode<"query">;
  notify: ((arg0: bigint) => Promise<void>) & $.WithMode<"oneway">;
  "quoted name": (() => Promise<bigint>) & $.WithMode<"query">;
  read: (() => Promise<bigint>) & $.WithMode<"query">;
  aggregate: ((arg0: string) => Promise<Array<bigint>>) & $.WithMode<"composite_query">;
  announce: ((arg0: string) => Promise<void>) & $.WithMode<"oneway">;
  transfer: ((arg0: bigint, arg1: string) => Promise<boolean>) & $.WithMode<"update">;
};
export { $actor as actor, type $Actor as Actor };
