// Generated by candid-core-ts from a candid-core Contract. Do not edit.
// Omitted: type Actor (reserved_export_name)
// Omitted: type Ambiguous (ambiguous_variant_arm)
// Omitted: type AnonymousBad (reserved_field_name)
// Omitted: type Bad (reserved_field_name)
// Omitted: type BadAlias (references_omitted via Bad)
// Omitted: type Callback (references_omitted via Bad)
// Omitted: type Deep (references_omitted via Bad)
// Omitted: type Handlers (references_omitted via Callback)
// Omitted: type Holder (references_omitted via Bad)
// Omitted: type Loop (references_omitted via Bad)
// Omitted: type Registry (references_omitted via Bad)
// Omitted: type TwoCauses (references_omitted via Bad)
// Omitted: type UsesActor (references_omitted via actor)
// Omitted: type UsesAmbiguous (references_omitted via Ambiguous)
// Omitted: type actor (reserved_export_name)
// Omitted: method ambiguous (references_omitted via Ambiguous)
// Omitted: method anonymous_bad (reserved_field_name)
// Omitted: method bad (references_omitted via Bad)
// Omitted: method by_reference (references_omitted via Callback)
// Omitted: method callback (references_omitted via Callback)
// Omitted: method two_causes (references_omitted via Ambiguous)
// Omitted: method uses_actor (references_omitted via actor)
import * as $ from "@candid-core/schema";

type $Directory = { svc: $.Principal };
const $Directory: $.Schema<$Directory> = $.c.rec(() => $.c.record({ svc: $.c.service({ g: $.c.func([$Good], [], "update") }) }));
export { $Directory as Directory };

type $Good = { a: bigint };
const $Good: $.Schema<$Good> = $.c.rec(() => $.c.record({ a: $.c.nat }));
export { $Good as Good };

type $List = { head: bigint; tail: $List } | null;
const $List: $.Schema<$List> = $.c.rec(() => $.c.opt($.c.record({ head: $.c.nat, tail: $List })));
export { $List as List };

type $NoValue = never | null;
const $NoValue: $.Schema<$NoValue> = $.c.rec(() => $.c.opt($.c.empty));
export { $NoValue as NoValue };

const $actor: $.Schema<$.Principal> = $.c.rec(() => $.c.service({ ok: $.c.func([$Good], [$Good], "query"), directory: $.c.func([$Directory], [], "update"), list: $.c.func([], [$List], "query") }));
type $Actor = {
  ok: (arg0: $Good) => Promise<$Good>;
  directory: (arg0: $Directory) => Promise<void>;
  list: () => Promise<$List>;
};
export { $actor as actor, type $Actor as Actor };
