// Generated by candid-core-ts from a candid-core Contract. Do not edit.
import { c, type Schema } from "@candid-core/schema";
import type { PrincipalValue } from "@candid-core/schema";

export type AliasedOuter = { some: MaybeText } | null;
export const AliasedOuter: Schema<AliasedOuter> = c.rec(() => c.opt(MaybeText));

export type Chain = { some: Chain } | null;
export const Chain: Schema<Chain> = c.rec(() => c.opt(Chain));

export type Change = { tag: "set"; value: AliasedOuter } | { tag: "keep" } | { tag: "clear"; value: OptNothing };
export const Change: Schema<Change> = c.rec(() => c.variant({ set: AliasedOuter, keep: Nothing, clear: OptNothing }));

export type DoubleOpt = { some: bigint | null } | null;
export const DoubleOpt: Schema<DoubleOpt> = c.rec(() => c.opt(c.opt(c.nat)));

export type MaybeText = string | null;
export const MaybeText: Schema<MaybeText> = c.rec(() => c.opt(c.text));

export type Nothing = null;
export const Nothing: Schema<Nothing> = c.rec(() => c.null);

export type OptEmpty = never | null;
export const OptEmpty: Schema<OptEmpty> = c.rec(() => c.opt(c.empty));

export type OptNothing = { some: Nothing } | null;
export const OptNothing: Schema<OptNothing> = c.rec(() => c.opt(Nothing));

export type OptNull = OptNothing;
export const OptNull: Schema<OptNull> = c.rec(() => OptNothing);

export type OptOptEmpty = { some: OptEmpty } | null;
export const OptOptEmpty: Schema<OptOptEmpty> = c.rec(() => c.opt(OptEmpty));

export type OptReserved = { some: unknown } | null;
export const OptReserved: Schema<OptReserved> = c.rec(() => c.opt(c.reserved));

export type Ping = { pong: Pong } | null;
export const Ping: Schema<Ping> = c.rec(() => c.opt(c.record({ pong: Pong })));

export type Pong = { some: Ping } | null;
export const Pong: Schema<Pong> = c.rec(() => c.opt(Ping));

export type Settings = { flag: MaybeText; label: AliasedOuter; limit: { some: bigint | null } | null };
export const Settings: Schema<Settings> = c.rec(() => c.record({ flag: MaybeText, label: AliasedOuter, limit: c.opt(c.opt(c.nat64)) }));

export type TripleOpt = { some: DoubleOpt } | null;
export const TripleOpt: Schema<TripleOpt> = c.rec(() => c.opt(DoubleOpt));

export const actor: Schema<PrincipalValue> = c.rec(() => c.service({ describe: c.func([AliasedOuter], [AliasedOuter], "update"), update: c.func([Settings], [Change], "update"), settings: c.func([], [Settings], "query") }));
export type Actor = {
  describe: (arg0: AliasedOuter) => Promise<AliasedOuter>;
  update: (arg0: Settings) => Promise<Change>;
  settings: () => Promise<Settings>;
};
