// Generated by candid-core-ts from a candid-core Contract. Do not edit.
import * as $ from "@candid-core/schema";

export type AliasedOuter = { some: MaybeText } | null;
const $AliasedOuter: $.Schema<AliasedOuter> = $.c.rec(() => $.c.opt($MaybeText));
export { $AliasedOuter as AliasedOuter };

/** Variant arms whose payloads are collapsing opts carry `value`. */
export type Change = { tag: "set"; value: AliasedOuter } | { tag: "keep" } | { tag: "clear"; value: OptNothing };
/** Variant arms whose payloads are collapsing opts carry `value`. */
const $Change: $.Schema<Change> = $.c.rec(() => $.c.variant({ set: $AliasedOuter, keep: $.c.null, clear: $OptNothing }));
export { $Change as Change };

/**
 * Collapsing options: an `opt` whose inner type admits `null` boxes its
 * present value as `{ some: T } | null`; every other opt stays `T | null`.
 */
export type DoubleOpt = { some: bigint | null } | null;
/**
 * Collapsing options: an `opt` whose inner type admits `null` boxes its
 * present value as `{ some: T } | null`; every other opt stays `T | null`.
 */
const $DoubleOpt: $.Schema<DoubleOpt> = $.c.rec(() => $.c.opt($.c.opt($.c.nat)));
export { $DoubleOpt as DoubleOpt };

/** Boxed through declared aliases: the test is on the node, not the spelling. */
export type MaybeText = string | null;
/** Boxed through declared aliases: the test is on the node, not the spelling. */
const $MaybeText: $.Schema<MaybeText> = $.c.rec(() => $.c.opt($.c.text));
export { $MaybeText as MaybeText };

export type Nothing = null;
const $Nothing: $.Schema<Nothing> = $.c.rec(() => $.c.null);
export { $Nothing as Nothing };

/** Unboxed control: `empty` does not admit null, so this is plain `null`. */
export type OptEmpty = never | null;
/** Unboxed control: `empty` does not admit null, so this is plain `null`. */
const $OptEmpty: $.Schema<OptEmpty> = $.c.rec(() => $.c.opt($.c.empty));
export { $OptEmpty as OptEmpty };

export type OptNothing = { some: null } | null;
const $OptNothing: $.Schema<OptNothing> = $.c.rec(() => $.c.opt($.c.null));
export { $OptNothing as OptNothing };

export type OptNull = OptNothing;
const $OptNull: $.Schema<OptNull> = $.c.rec(() => $OptNothing);
export { $OptNull as OptNull };

export type OptOptEmpty = { some: OptEmpty } | null;
const $OptOptEmpty: $.Schema<OptOptEmpty> = $.c.rec(() => $.c.opt($OptEmpty));
export { $OptOptEmpty as OptOptEmpty };

export type OptReserved = { some: unknown } | null;
const $OptReserved: $.Schema<OptReserved> = $.c.rec(() => $.c.opt($.c.reserved));
export { $OptReserved as OptReserved };

/**
 * Mutual recursion through opt: `Ping` wraps a record (unboxed), `Pong`
 * wraps `Ping`, an opt (boxed).
 */
export type Ping = { pong: Pong } | null;
/**
 * Mutual recursion through opt: `Ping` wraps a record (unboxed), `Pong`
 * wraps `Ping`, an opt (boxed).
 */
const $Ping: $.Schema<Ping> = $.c.rec(() => $.c.opt($.c.record({ pong: $Pong })));
export { $Ping as Ping };

export type Pong = { some: Ping } | null;
const $Pong: $.Schema<Pong> = $.c.rec(() => $.c.opt($Ping));
export { $Pong as Pong };

/**
 * The set/clear/keep pattern real interfaces use (Internet Identity's
 * config, Orbit's `opt opt` fields, the asset canister's property updates).
 */
export type Settings = { flag: MaybeText; label: AliasedOuter; limit: { some: bigint | null } | null };
/**
 * The set/clear/keep pattern real interfaces use (Internet Identity's
 * config, Orbit's `opt opt` fields, the asset canister's property updates).
 */
const $Settings: $.Schema<Settings> = $.c.rec(() => $.c.record({ flag: $MaybeText, label: $AliasedOuter, limit: $.c.opt($.c.opt($.c.nat64)) }));
export { $Settings as Settings };

export type TripleOpt = { some: DoubleOpt } | null;
const $TripleOpt: $.Schema<TripleOpt> = $.c.rec(() => $.c.opt($DoubleOpt));
export { $TripleOpt as TripleOpt };

const $actor: $.Schema<$.Principal> = $.c.rec(() => $.c.service({ describe: $.c.func([$AliasedOuter], [$AliasedOuter], "update"), update: $.c.func([$Settings], [$Change], "update"), settings: $.c.func([], [$Settings], "query") }));
export type Actor = {
  describe: ((arg0: AliasedOuter) => Promise<AliasedOuter>) & $.WithMode<"update">;
  update: ((arg0: Settings) => Promise<Change>) & $.WithMode<"update">;
  settings: (() => Promise<Settings>) & $.WithMode<"query">;
};
export { $actor as actor };
