// Generated by candid-core-ts from a candid-core Contract. Do not edit.
import * as $ from "@candid-core/schema";

type $AliasedOuter = { some: $MaybeText } | null;
const $AliasedOuter: $.Schema<$AliasedOuter> = $.c.rec(() => $.c.opt($MaybeText));
export { $AliasedOuter as AliasedOuter };

type $Chain = { some: $Chain } | null;
const $Chain: $.Schema<$Chain> = $.c.rec(() => $.c.opt($Chain));
export { $Chain as Chain };

type $Change = { tag: "set"; value: $AliasedOuter } | { tag: "keep" } | { tag: "clear"; value: $OptNothing };
const $Change: $.Schema<$Change> = $.c.rec(() => $.c.variant({ set: $AliasedOuter, keep: $Nothing, clear: $OptNothing }));
export { $Change as Change };

type $DoubleOpt = { some: bigint | null } | null;
const $DoubleOpt: $.Schema<$DoubleOpt> = $.c.rec(() => $.c.opt($.c.opt($.c.nat)));
export { $DoubleOpt as DoubleOpt };

type $MaybeText = string | null;
const $MaybeText: $.Schema<$MaybeText> = $.c.rec(() => $.c.opt($.c.text));
export { $MaybeText as MaybeText };

type $Nothing = null;
const $Nothing: $.Schema<$Nothing> = $.c.rec(() => $.c.null);
export { $Nothing as Nothing };

type $OptEmpty = never | null;
const $OptEmpty: $.Schema<$OptEmpty> = $.c.rec(() => $.c.opt($.c.empty));
export { $OptEmpty as OptEmpty };

type $OptNothing = { some: $Nothing } | null;
const $OptNothing: $.Schema<$OptNothing> = $.c.rec(() => $.c.opt($Nothing));
export { $OptNothing as OptNothing };

type $OptNull = $OptNothing;
const $OptNull: $.Schema<$OptNull> = $.c.rec(() => $OptNothing);
export { $OptNull as OptNull };

type $OptOptEmpty = { some: $OptEmpty } | null;
const $OptOptEmpty: $.Schema<$OptOptEmpty> = $.c.rec(() => $.c.opt($OptEmpty));
export { $OptOptEmpty as OptOptEmpty };

type $OptReserved = { some: unknown } | null;
const $OptReserved: $.Schema<$OptReserved> = $.c.rec(() => $.c.opt($.c.reserved));
export { $OptReserved as OptReserved };

type $Ping = { pong: $Pong } | null;
const $Ping: $.Schema<$Ping> = $.c.rec(() => $.c.opt($.c.record({ pong: $Pong })));
export { $Ping as Ping };

type $Pong = { some: $Ping } | null;
const $Pong: $.Schema<$Pong> = $.c.rec(() => $.c.opt($Ping));
export { $Pong as Pong };

type $Settings = { flag: $MaybeText; label: $AliasedOuter; limit: { some: bigint | null } | null };
const $Settings: $.Schema<$Settings> = $.c.rec(() => $.c.record({ flag: $MaybeText, label: $AliasedOuter, limit: $.c.opt($.c.opt($.c.nat64)) }));
export { $Settings as Settings };

type $TripleOpt = { some: $DoubleOpt } | null;
const $TripleOpt: $.Schema<$TripleOpt> = $.c.rec(() => $.c.opt($DoubleOpt));
export { $TripleOpt as TripleOpt };

const $actor: $.Schema<$.Principal> = $.c.rec(() => $.c.service({ describe: $.c.func([$AliasedOuter], [$AliasedOuter], "update"), update: $.c.func([$Settings], [$Change], "update"), settings: $.c.func([], [$Settings], "query") }));
type $Actor = {
  describe: (arg0: $AliasedOuter) => Promise<$AliasedOuter>;
  update: (arg0: $Settings) => Promise<$Change>;
  settings: () => Promise<$Settings>;
};
export { $actor as actor, type $Actor as Actor };
