// Generated by candid-core-ts from a candid-core Contract. Do not edit.
import * as $ from "@candid-core/schema";

type $P00 = null;
const $P00: $.Schema<$P00> = $.c.rec(() => $.c.null);
export { $P00 as P00 };

type $P01 = boolean;
const $P01: $.Schema<$P01> = $.c.rec(() => $.c.bool);
export { $P01 as P01 };

type $P02 = bigint;
const $P02: $.Schema<$P02> = $.c.rec(() => $.c.nat);
export { $P02 as P02 };

type $P03 = bigint;
const $P03: $.Schema<$P03> = $.c.rec(() => $.c.int);
export { $P03 as P03 };

type $P04 = number;
const $P04: $.Schema<$P04> = $.c.rec(() => $.c.nat8);
export { $P04 as P04 };

type $P05 = number;
const $P05: $.Schema<$P05> = $.c.rec(() => $.c.nat16);
export { $P05 as P05 };

type $P06 = number;
const $P06: $.Schema<$P06> = $.c.rec(() => $.c.nat32);
export { $P06 as P06 };

type $P07 = bigint;
const $P07: $.Schema<$P07> = $.c.rec(() => $.c.nat64);
export { $P07 as P07 };

type $P08 = number;
const $P08: $.Schema<$P08> = $.c.rec(() => $.c.int8);
export { $P08 as P08 };

type $P09 = number;
const $P09: $.Schema<$P09> = $.c.rec(() => $.c.int16);
export { $P09 as P09 };

type $P10 = number;
const $P10: $.Schema<$P10> = $.c.rec(() => $.c.int32);
export { $P10 as P10 };

type $P11 = bigint;
const $P11: $.Schema<$P11> = $.c.rec(() => $.c.int64);
export { $P11 as P11 };

type $P12 = number;
const $P12: $.Schema<$P12> = $.c.rec(() => $.c.float32);
export { $P12 as P12 };

type $P13 = number;
const $P13: $.Schema<$P13> = $.c.rec(() => $.c.float64);
export { $P13 as P13 };

type $P14 = string;
const $P14: $.Schema<$P14> = $.c.rec(() => $.c.text);
export { $P14 as P14 };

type $P15 = unknown;
const $P15: $.Schema<$P15> = $.c.rec(() => $.c.reserved);
export { $P15 as P15 };

type $P16 = never;
const $P16: $.Schema<$P16> = $.c.rec(() => $.c.empty);
export { $P16 as P16 };

type $P17 = $.Principal;
const $P17: $.Schema<$P17> = $.c.rec(() => $.c.principal);
export { $P17 as P17 };
