// Generated by candid-core-ts from a candid-core Contract. Do not edit.
import { c, type Schema } from "@candid-core/schema";
import type { Principal } from "@icp-sdk/core/principal";

export type P00 = null;
export const P00: Schema<P00> = c.rec(() => c.null);

export type P01 = boolean;
export const P01: Schema<P01> = c.rec(() => c.bool);

export type P02 = bigint;
export const P02: Schema<P02> = c.rec(() => c.nat);

export type P03 = bigint;
export const P03: Schema<P03> = c.rec(() => c.int);

export type P04 = number;
export const P04: Schema<P04> = c.rec(() => c.nat8);

export type P05 = number;
export const P05: Schema<P05> = c.rec(() => c.nat16);

export type P06 = number;
export const P06: Schema<P06> = c.rec(() => c.nat32);

export type P07 = bigint;
export const P07: Schema<P07> = c.rec(() => c.nat64);

export type P08 = number;
export const P08: Schema<P08> = c.rec(() => c.int8);

export type P09 = number;
export const P09: Schema<P09> = c.rec(() => c.int16);

export type P10 = number;
export const P10: Schema<P10> = c.rec(() => c.int32);

export type P11 = bigint;
export const P11: Schema<P11> = c.rec(() => c.int64);

export type P12 = number;
export const P12: Schema<P12> = c.rec(() => c.float32);

export type P13 = number;
export const P13: Schema<P13> = c.rec(() => c.float64);

export type P14 = string;
export const P14: Schema<P14> = c.rec(() => c.text);

export type P15 = unknown;
export const P15: Schema<P15> = c.rec(() => c.reserved);

export type P16 = never;
export const P16: Schema<P16> = c.rec(() => c.empty);

export type P17 = Principal;
export const P17: Schema<P17> = c.rec(() => c.principal);
