// Generated by candid-core-ts from a candid-core Contract. Do not edit.
import type { Principal } from "@icp-sdk/core/principal";

export type P00 = null;

export type P01 = boolean;

export type P02 = bigint;

export type P03 = bigint;

export type P04 = number;

export type P05 = number;

export type P06 = number;

export type P07 = bigint;

export type P08 = number;

export type P09 = number;

export type P10 = number;

export type P11 = bigint;

export type P12 = number;

export type P13 = number;

export type P14 = string;

export type P15 = unknown;

export type P16 = never;

export type P17 = Principal;
