// Generated by candid-core-ts from a candid-core Contract. Do not edit.
import { c, type Schema } from "@candid-core/schema";

export type Event = { tag: "idle" } | { tag: "__proto__"; value: number };
export const Event: Schema<Event> = c.rec(() => c.variant({ idle: c.null, ["__proto__"]: c.nat8 }));

export type Holder = { __proto__: number };
export const Holder: Schema<Holder> = c.rec(() => c.record({ ["__proto__"]: c.nat8 }));
