// Generated by candid-core-ts from a candid-core Contract. Do not edit.
import * as $ from "@candid-core/schema";

export type Event = { tag: "idle" } | { tag: "__proto__"; value: number };
const $Event: $.Schema<Event> = $.c.rec(() => $.c.variant({ idle: $.c.null, ["__proto__"]: $.c.nat8 }));
export { $Event as Event };

export type Holder = { __proto__: number };
const $Holder: $.Schema<Holder> = $.c.rec(() => $.c.record({ ["__proto__"]: $.c.nat8 }));
export { $Holder as Holder };
