// Generated by candid-core-ts from a candid-core Contract. Do not edit.
import { c, type Schema } from "@candid-core/schema";

export type Weird = { "quote\"mark": boolean; "naïve": string; "has space": bigint };
export const Weird: Schema<Weird> = c.rec(() => c.record({ "quote\"mark": c.bool, "naïve": c.text, "has space": c.nat }));
