// Generated by candid-core-ts from a candid-core Contract. Do not edit.
import * as $ from "@candid-core/schema";

type $Weird = { "quote\"mark": boolean; "naïve": string; "has space": bigint };
const $Weird: $.Schema<$Weird> = $.c.rec(() => $.c.record({ "quote\"mark": $.c.bool, "naïve": $.c.text, "has space": $.c.nat }));
export { $Weird as Weird };
