// Generated by candid-core-ts from a candid-core Contract. Do not edit.

export type Even = { next: [] | [Even] };

export type List = [] | [{ head: bigint; tail: List }];

export type ListAlias = List;

export type Odd = Even;
