// Generated by candid-core-ts from a candid-core Contract. Do not edit.
import * as $ from "@candid-core/schema";

type $Even = { next: $Even | null };
const $Even: $.Schema<$Even> = $.c.rec(() => $.c.record({ next: $.c.opt($Even) }));
export { $Even as Even };

type $List = { head: bigint; tail: $List } | null;
const $List: $.Schema<$List> = $.c.rec(() => $.c.opt($.c.record({ head: $.c.nat, tail: $List })));
export { $List as List };

type $ListAlias = $List;
const $ListAlias: $.Schema<$ListAlias> = $.c.rec(() => $List);
export { $ListAlias as ListAlias };

type $Odd = $Even;
const $Odd: $.Schema<$Odd> = $.c.rec(() => $Even);
export { $Odd as Odd };
