// Generated by candid-core-ts from a candid-core Contract. Do not edit.
import { c, type Schema } from "@candid-core/schema";

export type Even = { next: Even | null };
export const Even: Schema<Even> = c.rec(() => c.record({ next: c.opt(Even) }));

export type List = { head: bigint; tail: List } | null;
export const List: Schema<List> = c.rec(() => c.opt(c.record({ head: c.nat, tail: List })));

export type ListAlias = List;
export const ListAlias: Schema<ListAlias> = c.rec(() => List);

export type Odd = Even;
export const Odd: Schema<Odd> = c.rec(() => Even);
