// Generated by candid-core-ts from a candid-core Contract. Do not edit.
import * as $ from "@candid-core/schema";

type $Array = number;
const $Array: $.Schema<$Array> = $.c.rec(() => $.c.int32);
export { $Array as Array };

type $Bytes = Uint8Array;
const $Bytes: $.Schema<$Bytes> = $.c.rec(() => $.c.blob());
export { $Bytes as Bytes };

type $PrincipalValue = { p: $.PrincipalValue };
const $PrincipalValue: $.Schema<$PrincipalValue> = $.c.rec(() => $.c.record({ p: $.c.principal }));
export { $PrincipalValue as PrincipalValue };

type $Promise = { id: bigint };
const $Promise: $.Schema<$Promise> = $.c.rec(() => $.c.record({ id: $.c.nat }));
export { $Promise as Promise };

type $Record = bigint;
const $Record: $.Schema<$Record> = $.c.rec(() => $.c.int64);
export { $Record as Record };

type $Schema = number;
const $Schema: $.Schema<$Schema> = $.c.rec(() => $.c.int16);
export { $Schema as Schema };

type $Texts = Array<string>;
const $Texts: $.Schema<$Texts> = $.c.rec(() => $.c.vec($.c.text));
export { $Texts as Texts };

type $Uint8Array = number;
const $Uint8Array: $.Schema<$Uint8Array> = $.c.rec(() => $.c.float32);
export { $Uint8Array as Uint8Array };

type $Unit = Record<string, never>;
const $Unit: $.Schema<$Unit> = $.c.rec(() => $.c.unit());
export { $Unit as Unit };

type $Uses = { a: $Array; d: $delete; p: $Promise; s: $Schema; t: $Texts; w: $PrincipalValue; x: $c };
const $Uses: $.Schema<$Uses> = $.c.rec(() => $.c.record({ a: $Array, d: $delete, p: $Promise, s: $Schema, t: $Texts, w: $PrincipalValue, x: $c }));
export { $Uses as Uses };

type $c = number;
const $c: $.Schema<$c> = $.c.rec(() => $.c.int8);
export { $c as c };

type $default = number;
const $default: $.Schema<$default> = $.c.rec(() => $.c.nat32);
export { $default as default };

type $delete = number;
const $delete: $.Schema<$delete> = $.c.rec(() => $.c.float64);
export { $delete as delete };

type $string = number;
const $string: $.Schema<$string> = $.c.rec(() => $.c.nat16);
export { $string as string };

const $actor: $.Schema<$.PrincipalValue> = $.c.rec(() => $.c.service({ all: $.c.func([$Uses], [$default, $Bytes, $Unit], "query"), get: $.c.func([$string], [$delete], "query"), ping: $.c.func([$c], [$Promise], "update") }));
type $Actor = {
  all: (arg0: $Uses) => Promise<[$default, $Bytes, $Unit]>;
  get: (arg0: $string) => Promise<$delete>;
  ping: (arg0: $c) => Promise<$Promise>;
};
export { $actor as actor, type $Actor as Actor };
