// Generated by candid-core-ts from a candid-core Contract. Do not edit.
import * as $ from "@candid-core/schema";

export type Account = { owner: $.Principal; subaccount: Uint8Array | null };
const $Account: $.Schema<Account> = $.c.rec(() => $.c.record({ owner: $.c.principal, subaccount: $.c.opt($.c.blob()) }));
export { $Account as Account };

type $Array = { items: Array<Account> };
const $Array: $.Schema<$Array> = $.c.rec(() => $.c.record({ items: $.c.vec($Account) }));
export { $Array as Array };

export type Contextual = { is: is; of: of; get: get; out: out; set: set; async: async; source: source; asserts: asserts; eval: eval; from: from; require: require; override: override; assert: assert; constructor: constructor; global: global; abstract: abstract; using: using; satisfies: satisfies; module: module; accessor: accessor; defer: defer; namespace: namespace; declare: declare; arguments: arguments };
const $Contextual: $.Schema<Contextual> = $.c.rec(() => $.c.record({ is: $is, of: $of, get: $get, out: $out, set: $set, async: $async, source: $source, asserts: $asserts, eval: $eval, from: $from, require: $require, override: $override, assert: $assert, constructor: $constructor, global: $global, abstract: $abstract, using: $using, satisfies: $satisfies, module: $module, accessor: $accessor, defer: $defer, namespace: $namespace, declare: $declare, arguments: $arguments }));
export { $Contextual as Contextual };

export type Forest = Array<Tree>;
const $Forest: $.Schema<Forest> = $.c.rec(() => $.c.vec($Tree));
export { $Forest as Forest };

export type Grove = Forest;
const $Grove: $.Schema<Grove> = $.c.rec(() => $Forest);
export { $Grove as Grove };

type $Promise = { pending: Forest };
const $Promise: $.Schema<$Promise> = $.c.rec(() => $.c.record({ pending: $Forest }));
export { $Promise as Promise };

type $Record = { unit: Record<string, never>; bytes: Uint8Array };
const $Record: $.Schema<$Record> = $.c.rec(() => $.c.record({ unit: $.c.unit(), bytes: $.c.blob() }));
export { $Record as Record };

export type Refused = { as: $as; do: $do; if: $if; in: $in; any: $any; for: $for; let: $let; new: $new; try: $try; var: $var; static: $static; return: $return; throw: $throw; string: $string; function: $function; object: $object; finally: $finally; await: $await; continue: $continue; interface: $interface; catch: $catch; package: $package; case: $case; else: $else; enum: $enum; intrinsic: $intrinsic; class: $class; const: $const; this: $this; void: $void; with: $with; typeof: $typeof; unique: $unique; public: $public; delete: $delete; instanceof: $instanceof; extends: $extends; boolean: $boolean; super: $super; readonly: $readonly; private: $private; debugger: $debugger; protected: $protected; never: $never; default: $default; undefined: $undefined; number: $number; implements: $implements; break: $break; infer: $infer; export: $export; switch: $switch; while: $while; keyof: $keyof; unknown: $unknown; bigint: $bigint; symbol: $symbol; yield: $yield };
const $Refused: $.Schema<Refused> = $.c.rec(() => $.c.record({ as: $as, do: $do, if: $if, in: $in, any: $any, for: $for, let: $let, new: $new, try: $try, var: $var, static: $static, return: $return, throw: $throw, string: $string, function: $function, object: $object, finally: $finally, await: $await, continue: $continue, interface: $interface, catch: $catch, package: $package, case: $case, else: $else, enum: $enum, intrinsic: $intrinsic, class: $class, const: $const, this: $this, void: $void, with: $with, typeof: $typeof, unique: $unique, public: $public, delete: $delete, instanceof: $instanceof, extends: $extends, boolean: $boolean, super: $super, readonly: $readonly, private: $private, debugger: $debugger, protected: $protected, never: $never, default: $default, undefined: $undefined, number: $number, implements: $implements, break: $break, infer: $infer, export: $export, switch: $switch, while: $while, keyof: $keyof, unknown: $unknown, bigint: $bigint, symbol: $symbol, yield: $yield }));
export { $Refused as Refused };

export type TransferArg = { to: Account; amount: bigint };
const $TransferArg: $.Schema<TransferArg> = $.c.rec(() => $.c.record({ to: $Account, amount: $.c.nat }));
export { $TransferArg as TransferArg };

export type TransferResult = { tag: "ok"; value: bigint } | { tag: "err"; value: string };
const $TransferResult: $.Schema<TransferResult> = $.c.rec(() => $.c.variant({ ok: $.c.nat, err: $.c.text }));
export { $TransferResult as TransferResult };

export type Tree = { tag: "leaf"; value: bigint } | { tag: "node"; value: { left: Tree; right: Tree } };
const $Tree: $.Schema<Tree> = $.c.rec(() => $.c.variant({ leaf: $.c.nat, node: $.c.record({ left: $Tree, right: $Tree }) }));
export { $Tree as Tree };

type $Uint8Array = number;
const $Uint8Array: $.Schema<$Uint8Array> = $.c.rec(() => $.c.int16);
export { $Uint8Array as Uint8Array };

export type abstract = { abstract: number };
const $abstract: $.Schema<abstract> = $.c.rec(() => $.c.record({ abstract: $.c.nat8 }));
export { $abstract as abstract };

export type accessor = { accessor: number };
const $accessor: $.Schema<accessor> = $.c.rec(() => $.c.record({ accessor: $.c.nat8 }));
export { $accessor as accessor };

type $any = { any: number };
const $any: $.Schema<$any> = $.c.rec(() => $.c.record({ any: $.c.nat16 }));
export { $any as any };

export type arguments = { arguments: number };
const $arguments: $.Schema<arguments> = $.c.rec(() => $.c.record({ arguments: $.c.nat8 }));
export { $arguments as arguments };

type $as = { as: number };
const $as: $.Schema<$as> = $.c.rec(() => $.c.record({ as: $.c.nat16 }));
export { $as as as };

export type assert = { assert: number };
const $assert: $.Schema<assert> = $.c.rec(() => $.c.record({ assert: $.c.nat8 }));
export { $assert as assert };

export type asserts = { asserts: number };
const $asserts: $.Schema<asserts> = $.c.rec(() => $.c.record({ asserts: $.c.nat8 }));
export { $asserts as asserts };

export type async = { async: number };
const $async: $.Schema<async> = $.c.rec(() => $.c.record({ async: $.c.nat8 }));
export { $async as async };

type $await = { await: number };
const $await: $.Schema<$await> = $.c.rec(() => $.c.record({ await: $.c.nat16 }));
export { $await as await };

type $bigint = { bigint: number };
const $bigint: $.Schema<$bigint> = $.c.rec(() => $.c.record({ bigint: $.c.nat16 }));
export { $bigint as bigint };

type $boolean = { boolean: number };
const $boolean: $.Schema<$boolean> = $.c.rec(() => $.c.record({ boolean: $.c.nat16 }));
export { $boolean as boolean };

type $break = { break: number };
const $break: $.Schema<$break> = $.c.rec(() => $.c.record({ break: $.c.nat16 }));
export { $break as break };

type $case = { case: number };
const $case: $.Schema<$case> = $.c.rec(() => $.c.record({ case: $.c.nat16 }));
export { $case as case };

type $catch = { catch: number };
const $catch: $.Schema<$catch> = $.c.rec(() => $.c.record({ catch: $.c.nat16 }));
export { $catch as catch };

type $class = { class: number };
const $class: $.Schema<$class> = $.c.rec(() => $.c.record({ class: $.c.nat16 }));
export { $class as class };

type $const = { const: number };
const $const: $.Schema<$const> = $.c.rec(() => $.c.record({ const: $.c.nat16 }));
export { $const as const };

export type constructor = { constructor: number };
const $constructor: $.Schema<constructor> = $.c.rec(() => $.c.record({ constructor: $.c.nat8 }));
export { $constructor as constructor };

type $continue = { continue: number };
const $continue: $.Schema<$continue> = $.c.rec(() => $.c.record({ continue: $.c.nat16 }));
export { $continue as continue };

type $debugger = { debugger: number };
const $debugger: $.Schema<$debugger> = $.c.rec(() => $.c.record({ debugger: $.c.nat16 }));
export { $debugger as debugger };

export type declare = { declare: number };
const $declare: $.Schema<declare> = $.c.rec(() => $.c.record({ declare: $.c.nat8 }));
export { $declare as declare };

type $default = { default: number };
const $default: $.Schema<$default> = $.c.rec(() => $.c.record({ default: $.c.nat16 }));
export { $default as default };

export type defer = { defer: number };
const $defer: $.Schema<defer> = $.c.rec(() => $.c.record({ defer: $.c.nat8 }));
export { $defer as defer };

type $delete = { delete: number };
const $delete: $.Schema<$delete> = $.c.rec(() => $.c.record({ delete: $.c.nat16 }));
export { $delete as delete };

type $do = { do: number };
const $do: $.Schema<$do> = $.c.rec(() => $.c.record({ do: $.c.nat16 }));
export { $do as do };

type $else = { else: number };
const $else: $.Schema<$else> = $.c.rec(() => $.c.record({ else: $.c.nat16 }));
export { $else as else };

type $enum = { enum: number };
const $enum: $.Schema<$enum> = $.c.rec(() => $.c.record({ enum: $.c.nat16 }));
export { $enum as enum };

export type eval = { eval: number };
const $eval: $.Schema<eval> = $.c.rec(() => $.c.record({ eval: $.c.nat8 }));
export { $eval as eval };

type $export = { export: number };
const $export: $.Schema<$export> = $.c.rec(() => $.c.record({ export: $.c.nat16 }));
export { $export as export };

type $extends = { extends: number };
const $extends: $.Schema<$extends> = $.c.rec(() => $.c.record({ extends: $.c.nat16 }));
export { $extends as extends };

type $finally = { finally: number };
const $finally: $.Schema<$finally> = $.c.rec(() => $.c.record({ finally: $.c.nat16 }));
export { $finally as finally };

type $for = { for: number };
const $for: $.Schema<$for> = $.c.rec(() => $.c.record({ for: $.c.nat16 }));
export { $for as for };

export type from = { from: number };
const $from: $.Schema<from> = $.c.rec(() => $.c.record({ from: $.c.nat8 }));
export { $from as from };

type $function = { function: number };
const $function: $.Schema<$function> = $.c.rec(() => $.c.record({ function: $.c.nat16 }));
export { $function as function };

export type get = { get: number };
const $get: $.Schema<get> = $.c.rec(() => $.c.record({ get: $.c.nat8 }));
export { $get as get };

export type global = { global: number };
const $global: $.Schema<global> = $.c.rec(() => $.c.record({ global: $.c.nat8 }));
export { $global as global };

type $if = { if: number };
const $if: $.Schema<$if> = $.c.rec(() => $.c.record({ if: $.c.nat16 }));
export { $if as if };

type $implements = { implements: number };
const $implements: $.Schema<$implements> = $.c.rec(() => $.c.record({ implements: $.c.nat16 }));
export { $implements as implements };

type $in = { in: number };
const $in: $.Schema<$in> = $.c.rec(() => $.c.record({ in: $.c.nat16 }));
export { $in as in };

type $infer = { infer: number };
const $infer: $.Schema<$infer> = $.c.rec(() => $.c.record({ infer: $.c.nat16 }));
export { $infer as infer };

type $instanceof = { instanceof: number };
const $instanceof: $.Schema<$instanceof> = $.c.rec(() => $.c.record({ instanceof: $.c.nat16 }));
export { $instanceof as instanceof };

type $interface = { interface: number };
const $interface: $.Schema<$interface> = $.c.rec(() => $.c.record({ interface: $.c.nat16 }));
export { $interface as interface };

type $intrinsic = { intrinsic: number };
const $intrinsic: $.Schema<$intrinsic> = $.c.rec(() => $.c.record({ intrinsic: $.c.nat16 }));
export { $intrinsic as intrinsic };

export type is = { is: number };
const $is: $.Schema<is> = $.c.rec(() => $.c.record({ is: $.c.nat8 }));
export { $is as is };

type $keyof = { keyof: number };
const $keyof: $.Schema<$keyof> = $.c.rec(() => $.c.record({ keyof: $.c.nat16 }));
export { $keyof as keyof };

type $let = { let: number };
const $let: $.Schema<$let> = $.c.rec(() => $.c.record({ let: $.c.nat16 }));
export { $let as let };

export type module = { module: number };
const $module: $.Schema<module> = $.c.rec(() => $.c.record({ module: $.c.nat8 }));
export { $module as module };

export type namespace = { namespace: number };
const $namespace: $.Schema<namespace> = $.c.rec(() => $.c.record({ namespace: $.c.nat8 }));
export { $namespace as namespace };

type $never = { never: number };
const $never: $.Schema<$never> = $.c.rec(() => $.c.record({ never: $.c.nat16 }));
export { $never as never };

type $new = { new: number };
const $new: $.Schema<$new> = $.c.rec(() => $.c.record({ new: $.c.nat16 }));
export { $new as new };

type $number = { number: number };
const $number: $.Schema<$number> = $.c.rec(() => $.c.record({ number: $.c.nat16 }));
export { $number as number };

type $object = { object: number };
const $object: $.Schema<$object> = $.c.rec(() => $.c.record({ object: $.c.nat16 }));
export { $object as object };

export type of = { of: number };
const $of: $.Schema<of> = $.c.rec(() => $.c.record({ of: $.c.nat8 }));
export { $of as of };

export type out = { out: number };
const $out: $.Schema<out> = $.c.rec(() => $.c.record({ out: $.c.nat8 }));
export { $out as out };

export type override = { override: number };
const $override: $.Schema<override> = $.c.rec(() => $.c.record({ override: $.c.nat8 }));
export { $override as override };

type $package = { package: number };
const $package: $.Schema<$package> = $.c.rec(() => $.c.record({ package: $.c.nat16 }));
export { $package as package };

type $private = { private: number };
const $private: $.Schema<$private> = $.c.rec(() => $.c.record({ private: $.c.nat16 }));
export { $private as private };

type $protected = { protected: number };
const $protected: $.Schema<$protected> = $.c.rec(() => $.c.record({ protected: $.c.nat16 }));
export { $protected as protected };

type $public = { public: number };
const $public: $.Schema<$public> = $.c.rec(() => $.c.record({ public: $.c.nat16 }));
export { $public as public };

type $readonly = { readonly: number };
const $readonly: $.Schema<$readonly> = $.c.rec(() => $.c.record({ readonly: $.c.nat16 }));
export { $readonly as readonly };

export type require = { require: number };
const $require: $.Schema<require> = $.c.rec(() => $.c.record({ require: $.c.nat8 }));
export { $require as require };

type $return = { return: number };
const $return: $.Schema<$return> = $.c.rec(() => $.c.record({ return: $.c.nat16 }));
export { $return as return };

export type satisfies = { satisfies: number };
const $satisfies: $.Schema<satisfies> = $.c.rec(() => $.c.record({ satisfies: $.c.nat8 }));
export { $satisfies as satisfies };

export type set = { set: number };
const $set: $.Schema<set> = $.c.rec(() => $.c.record({ set: $.c.nat8 }));
export { $set as set };

export type source = { source: number };
const $source: $.Schema<source> = $.c.rec(() => $.c.record({ source: $.c.nat8 }));
export { $source as source };

type $static = { static: number };
const $static: $.Schema<$static> = $.c.rec(() => $.c.record({ static: $.c.nat16 }));
export { $static as static };

type $string = { string: number };
const $string: $.Schema<$string> = $.c.rec(() => $.c.record({ string: $.c.nat16 }));
export { $string as string };

type $super = { super: number };
const $super: $.Schema<$super> = $.c.rec(() => $.c.record({ super: $.c.nat16 }));
export { $super as super };

type $switch = { switch: number };
const $switch: $.Schema<$switch> = $.c.rec(() => $.c.record({ switch: $.c.nat16 }));
export { $switch as switch };

type $symbol = { symbol: number };
const $symbol: $.Schema<$symbol> = $.c.rec(() => $.c.record({ symbol: $.c.nat16 }));
export { $symbol as symbol };

type $this = { this: number };
const $this: $.Schema<$this> = $.c.rec(() => $.c.record({ this: $.c.nat16 }));
export { $this as this };

type $throw = { throw: number };
const $throw: $.Schema<$throw> = $.c.rec(() => $.c.record({ throw: $.c.nat16 }));
export { $throw as throw };

type $try = { try: number };
const $try: $.Schema<$try> = $.c.rec(() => $.c.record({ try: $.c.nat16 }));
export { $try as try };

type $typeof = { typeof: number };
const $typeof: $.Schema<$typeof> = $.c.rec(() => $.c.record({ typeof: $.c.nat16 }));
export { $typeof as typeof };

type $undefined = { undefined: number };
const $undefined: $.Schema<$undefined> = $.c.rec(() => $.c.record({ undefined: $.c.nat16 }));
export { $undefined as undefined };

type $unique = { unique: number };
const $unique: $.Schema<$unique> = $.c.rec(() => $.c.record({ unique: $.c.nat16 }));
export { $unique as unique };

type $unknown = { unknown: number };
const $unknown: $.Schema<$unknown> = $.c.rec(() => $.c.record({ unknown: $.c.nat16 }));
export { $unknown as unknown };

export type using = { using: number };
const $using: $.Schema<using> = $.c.rec(() => $.c.record({ using: $.c.nat8 }));
export { $using as using };

type $var = { var: number };
const $var: $.Schema<$var> = $.c.rec(() => $.c.record({ var: $.c.nat16 }));
export { $var as var };

type $void = { void: number };
const $void: $.Schema<$void> = $.c.rec(() => $.c.record({ void: $.c.nat16 }));
export { $void as void };

type $while = { while: number };
const $while: $.Schema<$while> = $.c.rec(() => $.c.record({ while: $.c.nat16 }));
export { $while as while };

type $with = { with: number };
const $with: $.Schema<$with> = $.c.rec(() => $.c.record({ with: $.c.nat16 }));
export { $with as with };

type $yield = { yield: number };
const $yield: $.Schema<$yield> = $.c.rec(() => $.c.record({ yield: $.c.nat16 }));
export { $yield as yield };

export type zz_abstract = abstract;
const $zz_abstract: $.Schema<zz_abstract> = $.c.rec(() => $abstract);
export { $zz_abstract as zz_abstract };

export type zz_accessor = accessor;
const $zz_accessor: $.Schema<zz_accessor> = $.c.rec(() => $accessor);
export { $zz_accessor as zz_accessor };

export type zz_arguments = arguments;
const $zz_arguments: $.Schema<zz_arguments> = $.c.rec(() => $arguments);
export { $zz_arguments as zz_arguments };

export type zz_assert = assert;
const $zz_assert: $.Schema<zz_assert> = $.c.rec(() => $assert);
export { $zz_assert as zz_assert };

export type zz_asserts = asserts;
const $zz_asserts: $.Schema<zz_asserts> = $.c.rec(() => $asserts);
export { $zz_asserts as zz_asserts };

export type zz_async = async;
const $zz_async: $.Schema<zz_async> = $.c.rec(() => $async);
export { $zz_async as zz_async };

export type zz_constructor = constructor;
const $zz_constructor: $.Schema<zz_constructor> = $.c.rec(() => $constructor);
export { $zz_constructor as zz_constructor };

export type zz_declare = declare;
const $zz_declare: $.Schema<zz_declare> = $.c.rec(() => $declare);
export { $zz_declare as zz_declare };

export type zz_defer = defer;
const $zz_defer: $.Schema<zz_defer> = $.c.rec(() => $defer);
export { $zz_defer as zz_defer };

export type zz_eval = eval;
const $zz_eval: $.Schema<zz_eval> = $.c.rec(() => $eval);
export { $zz_eval as zz_eval };

export type zz_from = from;
const $zz_from: $.Schema<zz_from> = $.c.rec(() => $from);
export { $zz_from as zz_from };

export type zz_get = get;
const $zz_get: $.Schema<zz_get> = $.c.rec(() => $get);
export { $zz_get as zz_get };

export type zz_global = global;
const $zz_global: $.Schema<zz_global> = $.c.rec(() => $global);
export { $zz_global as zz_global };

export type zz_intrinsic = $intrinsic;
const $zz_intrinsic: $.Schema<zz_intrinsic> = $.c.rec(() => $intrinsic);
export { $zz_intrinsic as zz_intrinsic };

export type zz_is = is;
const $zz_is: $.Schema<zz_is> = $.c.rec(() => $is);
export { $zz_is as zz_is };

export type zz_module = module;
const $zz_module: $.Schema<zz_module> = $.c.rec(() => $module);
export { $zz_module as zz_module };

export type zz_namespace = namespace;
const $zz_namespace: $.Schema<zz_namespace> = $.c.rec(() => $namespace);
export { $zz_namespace as zz_namespace };

export type zz_of = of;
const $zz_of: $.Schema<zz_of> = $.c.rec(() => $of);
export { $zz_of as zz_of };

export type zz_opt_abstract = abstract | null;
const $zz_opt_abstract: $.Schema<zz_opt_abstract> = $.c.rec(() => $.c.opt($abstract));
export { $zz_opt_abstract as zz_opt_abstract };

export type zz_opt_accessor = accessor | null;
const $zz_opt_accessor: $.Schema<zz_opt_accessor> = $.c.rec(() => $.c.opt($accessor));
export { $zz_opt_accessor as zz_opt_accessor };

export type zz_opt_arguments = arguments | null;
const $zz_opt_arguments: $.Schema<zz_opt_arguments> = $.c.rec(() => $.c.opt($arguments));
export { $zz_opt_arguments as zz_opt_arguments };

export type zz_opt_assert = assert | null;
const $zz_opt_assert: $.Schema<zz_opt_assert> = $.c.rec(() => $.c.opt($assert));
export { $zz_opt_assert as zz_opt_assert };

export type zz_opt_asserts = asserts | null;
const $zz_opt_asserts: $.Schema<zz_opt_asserts> = $.c.rec(() => $.c.opt($asserts));
export { $zz_opt_asserts as zz_opt_asserts };

export type zz_opt_async = async | null;
const $zz_opt_async: $.Schema<zz_opt_async> = $.c.rec(() => $.c.opt($async));
export { $zz_opt_async as zz_opt_async };

export type zz_opt_constructor = constructor | null;
const $zz_opt_constructor: $.Schema<zz_opt_constructor> = $.c.rec(() => $.c.opt($constructor));
export { $zz_opt_constructor as zz_opt_constructor };

export type zz_opt_declare = declare | null;
const $zz_opt_declare: $.Schema<zz_opt_declare> = $.c.rec(() => $.c.opt($declare));
export { $zz_opt_declare as zz_opt_declare };

export type zz_opt_defer = defer | null;
const $zz_opt_defer: $.Schema<zz_opt_defer> = $.c.rec(() => $.c.opt($defer));
export { $zz_opt_defer as zz_opt_defer };

export type zz_opt_eval = eval | null;
const $zz_opt_eval: $.Schema<zz_opt_eval> = $.c.rec(() => $.c.opt($eval));
export { $zz_opt_eval as zz_opt_eval };

export type zz_opt_from = from | null;
const $zz_opt_from: $.Schema<zz_opt_from> = $.c.rec(() => $.c.opt($from));
export { $zz_opt_from as zz_opt_from };

export type zz_opt_get = get | null;
const $zz_opt_get: $.Schema<zz_opt_get> = $.c.rec(() => $.c.opt($get));
export { $zz_opt_get as zz_opt_get };

export type zz_opt_global = global | null;
const $zz_opt_global: $.Schema<zz_opt_global> = $.c.rec(() => $.c.opt($global));
export { $zz_opt_global as zz_opt_global };

export type zz_opt_intrinsic = $intrinsic | null;
const $zz_opt_intrinsic: $.Schema<zz_opt_intrinsic> = $.c.rec(() => $.c.opt($intrinsic));
export { $zz_opt_intrinsic as zz_opt_intrinsic };

export type zz_opt_is = is | null;
const $zz_opt_is: $.Schema<zz_opt_is> = $.c.rec(() => $.c.opt($is));
export { $zz_opt_is as zz_opt_is };

export type zz_opt_module = module | null;
const $zz_opt_module: $.Schema<zz_opt_module> = $.c.rec(() => $.c.opt($module));
export { $zz_opt_module as zz_opt_module };

export type zz_opt_namespace = namespace | null;
const $zz_opt_namespace: $.Schema<zz_opt_namespace> = $.c.rec(() => $.c.opt($namespace));
export { $zz_opt_namespace as zz_opt_namespace };

export type zz_opt_of = of | null;
const $zz_opt_of: $.Schema<zz_opt_of> = $.c.rec(() => $.c.opt($of));
export { $zz_opt_of as zz_opt_of };

export type zz_opt_out = out | null;
const $zz_opt_out: $.Schema<zz_opt_out> = $.c.rec(() => $.c.opt($out));
export { $zz_opt_out as zz_opt_out };

export type zz_opt_override = override | null;
const $zz_opt_override: $.Schema<zz_opt_override> = $.c.rec(() => $.c.opt($override));
export { $zz_opt_override as zz_opt_override };

export type zz_opt_require = require | null;
const $zz_opt_require: $.Schema<zz_opt_require> = $.c.rec(() => $.c.opt($require));
export { $zz_opt_require as zz_opt_require };

export type zz_opt_satisfies = satisfies | null;
const $zz_opt_satisfies: $.Schema<zz_opt_satisfies> = $.c.rec(() => $.c.opt($satisfies));
export { $zz_opt_satisfies as zz_opt_satisfies };

export type zz_opt_set = set | null;
const $zz_opt_set: $.Schema<zz_opt_set> = $.c.rec(() => $.c.opt($set));
export { $zz_opt_set as zz_opt_set };

export type zz_opt_source = source | null;
const $zz_opt_source: $.Schema<zz_opt_source> = $.c.rec(() => $.c.opt($source));
export { $zz_opt_source as zz_opt_source };

export type zz_opt_using = using | null;
const $zz_opt_using: $.Schema<zz_opt_using> = $.c.rec(() => $.c.opt($using));
export { $zz_opt_using as zz_opt_using };

export type zz_out = out;
const $zz_out: $.Schema<zz_out> = $.c.rec(() => $out);
export { $zz_out as zz_out };

export type zz_override = override;
const $zz_override: $.Schema<zz_override> = $.c.rec(() => $override);
export { $zz_override as zz_override };

export type zz_require = require;
const $zz_require: $.Schema<zz_require> = $.c.rec(() => $require);
export { $zz_require as zz_require };

export type zz_satisfies = satisfies;
const $zz_satisfies: $.Schema<zz_satisfies> = $.c.rec(() => $satisfies);
export { $zz_satisfies as zz_satisfies };

export type zz_set = set;
const $zz_set: $.Schema<zz_set> = $.c.rec(() => $set);
export { $zz_set as zz_set };

export type zz_source = source;
const $zz_source: $.Schema<zz_source> = $.c.rec(() => $source);
export { $zz_source as zz_source };

export type zz_using = using;
const $zz_using: $.Schema<zz_using> = $.c.rec(() => $using);
export { $zz_using as zz_using };

const $actor: $.Schema<$.Principal> = $.c.rec(() => $.c.service({ remove: $.c.func([$delete], [$.c.opt($delete)], "query"), pending: $.c.func([$Array], [$Promise], "query"), words: $.c.func([$of, $Contextual], [$Refused, $Forest], "update"), transfer: $.c.func([$TransferArg], [$TransferResult], "update") }));
export type Actor = {
  remove: ((arg0: $delete) => Promise<$delete | null>) & $.WithMode<"query">;
  pending: ((arg0: $Array) => Promise<$Promise>) & $.WithMode<"query">;
  words: ((arg0: of, arg1: Contextual) => Promise<[Refused, Forest]>) & $.WithMode<"update">;
  transfer: ((arg0: TransferArg) => Promise<TransferResult>) & $.WithMode<"update">;
};
export { $actor as actor };
