// Generated by candid-core-ts from a candid-core Contract. Do not edit.

export type Numbered = { _0_: null } | { _5_: bigint };

export type Status = { ok: null } | { busy: number } | { failed: string };

export type Tree = { leaf: bigint } | { node: { left: Tree; right: Tree } };
