// Generated by candid-core-ts from a candid-core Contract. Do not edit.
import { c, type Schema } from "@candid-core/schema";

export type Numbered = { tag: "_0_" } | { tag: "_5_"; value: bigint };
export const Numbered: Schema<Numbered> = c.rec(() => c.variant({ _0_: c.null, _5_: c.nat }));

export type Status = { tag: "ok" } | { tag: "busy"; value: number } | { tag: "failed"; value: string };
export const Status: Schema<Status> = c.rec(() => c.variant({ ok: c.null, busy: c.nat32, failed: c.text }));

export type Tree = { tag: "leaf"; value: bigint } | { tag: "node"; value: { left: Tree; right: Tree } };
export const Tree: Schema<Tree> = c.rec(() => c.variant({ leaf: c.nat, node: c.record({ left: Tree, right: Tree }) }));
